--------------------------------------------------------
--  DDL for Table W_COMM_DIGITAL_PROC_LKP
--------------------------------------------------------

  CREATE TABLE "DW"."W_COMM_DIGITAL_PROC_LKP" 
   (	"CUSTOMER_TIER" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_TYPE" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"KW_TIER" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"DIGITAL_PROCURING" NUMBER, 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANGED_BY" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_COMM_DIGITAL_PROC_LKP" TO "ODS" WITH GRANT OPTION;
