--------------------------------------------------------
--  DDL for Table W_CURRENCY_G
--------------------------------------------------------

  CREATE TABLE "DW"."W_CURRENCY_G" 
   (	"CURRENCY_WID" NUMBER(*,0), 
	"ISO_CODE" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CURRENCY_NAME" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CURRENCY_SRC_KEY" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CURRENCY_SYMBOL" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE_TYPE" NVARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"RATE_TO_USD" NUMBER(38,15), 
	"RATE_FROM_USD" NUMBER(38,15), 
	"DATE_WID" NUMBER(*,0), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_CURRENCY_G" TO "ODS";
  GRANT READ ON "DW"."W_CURRENCY_G" TO "ODS";
  GRANT SELECT ON "DW"."W_CURRENCY_G" TO "DW_RO";
  GRANT READ ON "DW"."W_CURRENCY_G" TO "DW_RO";
