--------------------------------------------------------
--  DDL for Table W_ETL_EMAIL_CONTROL
--------------------------------------------------------

  CREATE TABLE "DW"."W_ETL_EMAIL_CONTROL" 
   (	"TASK_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTIFY_ON_SUCCESS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTIFY_ON_FAILURE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SNOW_INCIDENT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"TASK_PRIORITY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"SUCCESS_NOTIFY_LIST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"FAILURE_NOTIFY_LIST" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CREATED_BY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANGED_ON_DT" DATE, 
	"CHANGED_BY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_ETL_EMAIL_CONTROL" TO "DW_RO";
  GRANT READ ON "DW"."W_ETL_EMAIL_CONTROL" TO "DW_RO";
  GRANT SELECT ON "DW"."W_ETL_EMAIL_CONTROL" TO "ODS";
  GRANT READ ON "DW"."W_ETL_EMAIL_CONTROL" TO "ODS";
