--------------------------------------------------------
--  DDL for Table W_ETL_REFRESH_LOG
--------------------------------------------------------

  CREATE TABLE "DW"."W_ETL_REFRESH_LOG" 
   (	"SR_NO" NUMBER, 
	"PROCESS_NAME" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_MODIFIED_DATE" DATE, 
	"CREATE_DT" DATE, 
	"SOURCE_ROW_VERSION" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT READ ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT READ ON "DW"."W_ETL_REFRESH_LOG" TO "DW_READ_ROLE";
  GRANT ON COMMIT REFRESH ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT ON COMMIT REFRESH ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT QUERY REWRITE ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT QUERY REWRITE ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT DEBUG ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT DEBUG ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT FLASHBACK ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT READ ON "DW"."W_ETL_REFRESH_LOG" TO "SVC_ODI";
  GRANT READ ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT READ ON "DW"."W_ETL_REFRESH_LOG" TO "DW_RO";
  GRANT REFERENCES ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT REFERENCES ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT UPDATE ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT UPDATE ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT SELECT ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT SELECT ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT SELECT ON "DW"."W_ETL_REFRESH_LOG" TO "DW_RO";
  GRANT INSERT ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT INSERT ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT INDEX ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT INDEX ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT DELETE ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT DELETE ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT FLASHBACK ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT ALTER ON "DW"."W_ETL_REFRESH_LOG" TO "ODSSTAGE";
  GRANT ALTER ON "DW"."W_ETL_REFRESH_LOG" TO "ODS";
  GRANT SELECT ON "DW"."W_ETL_REFRESH_LOG" TO "DW_SELECT_ROLE";
