--------------------------------------------------------
--  DDL for Table W_GL_ACCOUNT_HIER_DHL
--------------------------------------------------------

  CREATE TABLE "DW"."W_GL_ACCOUNT_HIER_DHL" 
   (	"ROW_WID" NUMBER(*,0), 
	"ACCOUNT_WID" NUMBER(*,0), 
	"ACCOUNT_TREE_WID" NUMBER(*,0), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_HIER_DHL" TO "ODS";
  GRANT READ ON "DW"."W_GL_ACCOUNT_HIER_DHL" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_HIER_DHL" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_ACCOUNT_HIER_DHL" TO "DW_RO";
