--------------------------------------------------------
--  DDL for Table W_GL_BUDGET_F
--------------------------------------------------------

  CREATE TABLE "DW"."W_GL_BUDGET_F" 
   (	"ACCOUNT_WID" NUMBER(*,0) DEFAULT 0, 
	"PROPERTY_WID" NUMBER(*,0) DEFAULT 0, 
	"CURRENCY_WID" NUMBER(*,0) DEFAULT 0, 
	"BOOK_WID" NUMBER(*,0) DEFAULT 0, 
	"DATE_WID" NUMBER(*,0) DEFAULT 0, 
	"BASE_BUDGET_AMOUNT" FLOAT(126), 
	"EXCHANGE_RATE_USD" FLOAT(126), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ID" NVARCHAR2(555) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_GL_BUDGET_F" TO "ODS";
  GRANT READ ON "DW"."W_GL_BUDGET_F" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_BUDGET_F" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_BUDGET_F" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_BUDGET_F" TO "DW_READ_ROLE";
