--------------------------------------------------------
--  DDL for Table W_GL_BOOK_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_GL_BOOK_D" 
   (	"ROW_WID" NUMBER(*,0), 
	"BOOK_SRC_KEY" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"BOOK_NAME" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_GL_BOOK_D" TO "ODS";
  GRANT READ ON "DW"."W_GL_BOOK_D" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_BOOK_D" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_BOOK_D" TO "DW_RO";
