--------------------------------------------------------
--  DDL for Table W_GL_ACCOUNT_DH
--------------------------------------------------------

  CREATE TABLE "DW"."W_GL_ACCOUNT_DH" 
   (	"ROW_WID" NUMBER(*,0), 
	"ACCOUNT_WID" NUMBER(*,0), 
	"L1_FINANCIAL_STATEMENT" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"L2_ACCOUNT_CLASS" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L2_ACCOUNT_CLASS_ORDER" NUMBER(*,0), 
	"L3_ACCOUNT_CATEGORY" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L3_ACCOUNT_CATEGORY_ORDER" NUMBER(*,0), 
	"L4_ACCOUNT_SUB_CATEGORY" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L4_ACCOUNT_SUB_CATEGORY_ORDER" NUMBER(*,0), 
	"L5_ACCOUNT_GROUP" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L5_ACCOUNT_GROUP_ORDER" NUMBER(*,0), 
	"L6_ACCOUNT_TYPE" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L6_ACCOUNT_TYPE_ORDER" NUMBER(*,0), 
	"L7_ACCOUNT_SUB_TYPE" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"L7_ACCOUNT_SUB_TYPE_ORDER" NUMBER(*,0), 
	"ACCOUNT_CODE" NVARCHAR2(16) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_NAME" NVARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_SRC_KEY" NUMBER(*,0), 
	"ACCOUNT_ORDER" NUMBER(*,0), 
	"ACCOUNT_DESCRIPTION" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_SIGN" NUMBER, 
	"NORMAL_BALANCE" NVARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_INTELLIGENCE" NVARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_GROUPING" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SIGN_FLAG" NUMBER(*,0), 
	"NORMAL_BALANCE_BIT" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"COMP_NONCOMP_HEADER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COMP_NONCOMP_ACCOUNT_GROUP" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ACCOUNTTREE_SRC_KEY" NVARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_DH" TO "ODS";
  GRANT READ ON "DW"."W_GL_ACCOUNT_DH" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_DH" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_ACCOUNT_DH" TO "DW_RO";
