--------------------------------------------------------
--  DDL for Table W_LEASE_TERMS_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_LEASE_TERMS_D" 
   (	"ROW_WID" NUMBER(*,0), 
	"REPORTED_DATE" DATE, 
	"LEASE_TYPE" NVARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"LEASE_SIGN_DATE" DATE, 
	"LEASE_START_DATE" DATE, 
	"LEASE_END_DATE" DATE, 
	"AMENDMENT_TYPE" NVARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"AMENDMENT_SIGN_DATE" DATE, 
	"AMENDMENT_START_DATE" DATE, 
	"AMENDMENT_END_DATE" DATE, 
	"AMENDMENT_EXPIRE_DATE" DATE, 
	"AMENDMENT_EXPIRE_REPORTED_DATE" DATE, 
	"MTM_FLAG" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EARLY_TERMINATION_OPTION_DATE" DATE, 
	"AMENDMENT_ORIGINAL_START_DATE" DATE, 
	"LOCKED_FLAG" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '0', 
	"LEASE_NUMBER" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LEASE_REMAINING_TERM" NUMBER, 
	"DATE_EXPIRATION_YEAR" NUMBER, 
	"LEGACY_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BUSINESS_UNIT" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_LEASE_TERMS_D" TO "ODS";
  GRANT READ ON "DW"."W_LEASE_TERMS_D" TO "ODS";
  GRANT SELECT ON "DW"."W_LEASE_TERMS_D" TO "DW_RO";
  GRANT READ ON "DW"."W_LEASE_TERMS_D" TO "DW_RO";
