--------------------------------------------------------
--  DDL for Table W_MONTH_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_MONTH_D" 
   (	"ROW_WID" NUMBER, 
	"YEAR" NUMBER(*,0), 
	"QUARTER" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MONTH" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"QUARTER_NAME" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"MONTH_NAME" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"MONTH_ORDER" NUMBER(*,0), 
	"MONTH_AGO_WID" NUMBER, 
	"MONTH_START_DATE" DATE, 
	"MONTH_END_DATE" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_MONTH_D" TO "ODS";
  GRANT READ ON "DW"."W_MONTH_D" TO "ODS";
  GRANT SELECT ON "DW"."W_MONTH_D" TO "DW_RO";
  GRANT READ ON "DW"."W_MONTH_D" TO "DW_RO";
