--------------------------------------------------------
--  DDL for Table W_PRODUCT_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_PRODUCT_D" 
   (	"ROW_WID" NUMBER(38,0), 
	"INVENTORY_ITEM_ID" NUMBER(18,0), 
	"ORGANIZATION_ID" NUMBER(18,0), 
	"INTEGRATION_ID" VARCHAR2(81 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_NUMBER" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_DESCRIPTION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"ORGANIZATION_CODE" VARCHAR2(18 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_CATALOG_CATEGORY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"TAX_CATALOG_CATEGORY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"IL_TAX_CATEGORY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ITEM_CLASS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LIST_PRICE_PER_UNIT" NUMBER, 
	"BOM_ITEM_TYPE" NUMBER, 
	"PRIMARY_UOM_CODE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICEABLE_ITEM_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"INVENTORY_ASSET_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PURCHASING_ITEM_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(38,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_PRODUCT_D" TO "ODS";
  GRANT READ ON "DW"."W_PRODUCT_D" TO "ODS";
  GRANT SELECT ON "DW"."W_PRODUCT_D" TO "DW_RO";
  GRANT READ ON "DW"."W_PRODUCT_D" TO "DW_RO";
