--------------------------------------------------------
--  DDL for Table W_SITE_CODE_MAP
--------------------------------------------------------

  CREATE TABLE "DW"."W_SITE_CODE_MAP" 
   (	"PROPERTY_HMY" NUMBER(38,0), 
	"PROPERTY_SCODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SITE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMALLY_KNOWNAS_SITE_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_SITE_CODE_MAP" TO "ODS";
  GRANT READ ON "DW"."W_SITE_CODE_MAP" TO "ODS";
  GRANT SELECT ON "DW"."W_SITE_CODE_MAP" TO "DW_RO";
  GRANT READ ON "DW"."W_SITE_CODE_MAP" TO "DW_RO";
