--------------------------------------------------------
--  DDL for View VW_GL_ACCOUNT_DH
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_GL_ACCOUNT_DH" ("ROW_WID", "ACCOUNT_WID", "L1_FINANCIAL_STATEMENT", "L2_ACCOUNT_CLASS", "L2_ACCOUNT_CLASS_ORDER", "L3_ACCOUNT_CATEGORY", "L3_ACCOUNT_CATEGORY_ORDER", "L4_ACCOUNT_SUB_CATEGORY", "L4_ACCOUNT_SUB_CATEGORY_ORDER", "L5_ACCOUNT_GROUP", "L5_ACCOUNT_GROUP_ORDER", "L6_ACCOUNT_TYPE", "L6_ACCOUNT_TYPE_ORDER", "L7_ACCOUNT_SUB_TYPE", "L7_ACCOUNT_SUB_TYPE_ORDER", "ACCOUNT_CODE", "ACCOUNT_NAME", "ACCOUNT_SRC_KEY", "ACCOUNT_ORDER", "ACCOUNT_DESCRIPTION", "ACCOUNT_SIGN", "NORMAL_BALANCE", "ACCOUNT_INTELLIGENCE", "ACCOUNT_GROUPING", "SIGN_FLAG", "NORMAL_BALANCE_BIT", "COMP_NONCOMP_HEADER", "COMP_NONCOMP_ACCOUNT_GROUP", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "ACCOUNTTREE_SRC_KEY") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        "ROW_WID",
        "ACCOUNT_WID",
        "L1_FINANCIAL_STATEMENT",
        "L2_ACCOUNT_CLASS",
        "L2_ACCOUNT_CLASS_ORDER",
        "L3_ACCOUNT_CATEGORY",
        "L3_ACCOUNT_CATEGORY_ORDER",
        "L4_ACCOUNT_SUB_CATEGORY",
        "L4_ACCOUNT_SUB_CATEGORY_ORDER",
        "L5_ACCOUNT_GROUP",
        "L5_ACCOUNT_GROUP_ORDER",
        "L6_ACCOUNT_TYPE",
        "L6_ACCOUNT_TYPE_ORDER",
        "L7_ACCOUNT_SUB_TYPE",
        "L7_ACCOUNT_SUB_TYPE_ORDER",
        "ACCOUNT_CODE",
        "ACCOUNT_NAME",
        "ACCOUNT_SRC_KEY",
        "ACCOUNT_ORDER",
        "ACCOUNT_DESCRIPTION",
        "ACCOUNT_SIGN",
        "NORMAL_BALANCE",
        "ACCOUNT_INTELLIGENCE",
        "ACCOUNT_GROUPING",
        "SIGN_FLAG",
        "NORMAL_BALANCE_BIT",
        "COMP_NONCOMP_HEADER",
        "COMP_NONCOMP_ACCOUNT_GROUP",
        "CREATED_ON_DT",
        "CHANGED_ON_DT",
        "ETL_UPDATE_DT",
        "ETL_INSERT_DT",
        "ETL_PROC_WID",
        "DATASOURCE",
        "ACCOUNTTREE_SRC_KEY"
    FROM
        w_gl_account_dh
;
  GRANT READ ON "DW"."VW_GL_ACCOUNT_DH" TO "ODS";
  GRANT READ ON "DW"."VW_GL_ACCOUNT_DH" TO "DW_RO";
