--------------------------------------------------------
--  DDL for View VW_GL_ACTUAL_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_GL_ACTUAL_F" ("ACCOUNT_WID", "CURRENCY_WID", "BOOK_WID", "PROPERTY_WID", "JOURNAL_TYPE", "INFRASTRUCTURE", "UNIT_TYPE", "ORG_SOURCE", "SUITE_ROOM", "POST_DATE_WID", "BASE_ACTUAL_AMOUNT", "EXCHANGE_RATE_USD", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "ACTUAL_SRC_KEY", "ACTUAL_AMOUNT", "ACTUAL_AMOUNT_USD", "BASE_ACTUAL_AMOUNT_USD") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        ACCOUNT_WID,
        CURRENCY_WID,
        BOOK_WID,
        PROPERTY_WID,
        JOURNAL_TYPE,
        INFRASTRUCTURE,
        UNIT_TYPE,
        ORG_SOURCE,
        SUITE_ROOM,
        POST_DATE_WID,
        BASE_ACTUAL_AMOUNT,
        EXCHANGE_RATE_USD,
        CREATED_ON_DT,
        CHANGED_ON_DT,
        ETL_UPDATE_DT,
        ETL_INSERT_DT,
        ETL_PROC_WID,
        DATASOURCE,
        ACTUAL_SRC_KEY,
        nvl(BASE_ACTUAL_AMOUNT * -1,0 ) ACTUAL_AMOUNT,
        nvl(BASE_ACTUAL_AMOUNT * -1,0 ) * EXCHANGE_RATE_USD  ACTUAL_AMOUNT_USD,
        nvl(BASE_ACTUAL_AMOUNT,0) * EXCHANGE_RATE_USD BASE_ACTUAL_AMOUNT_USD
    FROM
        w_gl_actual_f
;
  GRANT READ ON "DW"."VW_GL_ACTUAL_F" TO "ODS";
  GRANT READ ON "DW"."VW_GL_ACTUAL_F" TO "DW_RO";
