--------------------------------------------------------
--  DDL for View VW_GL_BUDGET_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_GL_BUDGET_F" ("ACCOUNT_WID", "PROPERTY_WID", "CURRENCY_WID", "BOOK_WID", "DATE_WID", "BASE_BUDGET_AMOUNT", "EXCHANGE_RATE_USD", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "ID", "BUDGET_AMOUNT", "BASE_BUDGET_AMOUNT_USD", "BUDGET_AMOUNT_USD") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        ACCOUNT_WID,
        PROPERTY_WID,
        CURRENCY_WID,
        BOOK_WID,
        DATE_WID,
        BASE_BUDGET_AMOUNT,
        EXCHANGE_RATE_USD,
        CREATED_ON_DT,
        CHANGED_ON_DT,
        ETL_UPDATE_DT,
        ETL_INSERT_DT,
        ETL_PROC_WID,
        DATASOURCE,
        ID,
        nvl(BASE_BUDGET_AMOUNT * -1, 0) Budget_Amount,
        nvl(BASE_BUDGET_AMOUNT,0) * EXCHANGE_RATE_USD BASE_BUDGET_AMOUNT_USD,
        nvl(BASE_BUDGET_AMOUNT * -1, 0) * EXCHANGE_RATE_USD Budget_Amount_USD
    FROM
        w_gl_budget_f
;
  GRANT READ ON "DW"."VW_GL_BUDGET_F" TO "ODS";
  GRANT READ ON "DW"."VW_GL_BUDGET_F" TO "DW_RO";
