--------------------------------------------------------
--  DDL for View VW_OPPORTUNITY_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_OPPORTUNITY_D" ("ROW_WID", "OPPORTUNITY_SRC_KEY", "OPPORTUNITY_NAME", "OPPORTUNITY_OWNER", "OPPORTUNITY_TYPE", "STAGE", "TRANSACTION_TYPE", "COMMENTS", "INVOICING_REMARKS", "FORECAST_CATEGORY", "PRIMARY_WIN_LOSS_REASON", "SECONDARY_WIN_LOSS_REASON", "OPPORTUNITY_STATUS", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "OPPORTUNITY_DESCRIPTION", "PROBABILITY") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        "ROW_WID",
        "OPPORTUNITY_SRC_KEY",
        "OPPORTUNITY_NAME",
        "OPPORTUNITY_OWNER",
        "OPPORTUNITY_TYPE",
        "STAGE",
        "TRANSACTION_TYPE",
        "COMMENTS",
        "INVOICING_REMARKS",
        "FORECAST_CATEGORY",
        "PRIMARY_WIN_LOSS_REASON",
        "SECONDARY_WIN_LOSS_REASON",
        "OPPORTUNITY_STATUS",
        "CREATED_ON_DT",
        "CHANGED_ON_DT",
        "ETL_UPDATE_DT",
        "ETL_INSERT_DT",
        "ETL_PROC_WID",
        "DATASOURCE",
        "OPPORTUNITY_DESCRIPTION",
        "PROBABILITY"
    FROM
        w_opportunity_d
;
  GRANT READ ON "DW"."VW_OPPORTUNITY_D" TO "ODS";
  GRANT READ ON "DW"."VW_OPPORTUNITY_D" TO "DW_RO";
