--------------------------------------------------------
--  DDL for View VW_PRODUCT_HIERARCHY_COLO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_PRODUCT_HIERARCHY_COLO" ("PRODUCT_SRC_KEY", "PRODUCT_SRC_CODE", "PRODUCT_SRC_DESC", "PRODUCT_TYPE_GROUP", "L1_COLOCATION", "L2_COLOCATION", "PRODUCT_HIER2_WID", "ROW_WID", "INVENTORY_ITEM_ID", "ORGANIZATION_ID", "INTEGRATION_ID", "ITEM_NUMBER", "ITEM_DESCRIPTION", "ORGANIZATION_CODE", "PRODUCT_CATALOG_CATEGORY", "TAX_CATALOG_CATEGORY", "IL_TAX_CATEGORY", "ITEM_TYPE", "ITEM_CLASS", "LIST_PRICE_PER_UNIT", "BOM_ITEM_TYPE", "PRIMARY_UOM_CODE", "INVOICEABLE_ITEM_FLAG", "INVENTORY_ASSET_FLAG", "PURCHASING_ITEM_FLAG", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "LINE_OF_BUSINESS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select 
       g.PRODUCT_src_key,
       g.PRODUCT_src_code, 
       g.PRODUCT_SRC_DESC,
       g.PRODUCT_type_group,
       h.level3_name l1_colocation,
       h.level4_name l2_colocation,
       g.PRODUCT_HIER2_WID,
       pr."ROW_WID",pr."INVENTORY_ITEM_ID",pr."ORGANIZATION_ID",pr."INTEGRATION_ID",pr."ITEM_NUMBER",pr."ITEM_DESCRIPTION",pr."ORGANIZATION_CODE",pr."PRODUCT_CATALOG_CATEGORY",pr."TAX_CATALOG_CATEGORY",pr."IL_TAX_CATEGORY",pr."ITEM_TYPE",pr."ITEM_CLASS",pr."LIST_PRICE_PER_UNIT",pr."BOM_ITEM_TYPE",pr."PRIMARY_UOM_CODE",pr."INVOICEABLE_ITEM_FLAG",pr."INVENTORY_ASSET_FLAG",pr."PURCHASING_ITEM_FLAG",pr."CREATED_ON_DT",pr."CHANGED_ON_DT",pr."ETL_UPDATE_DT",pr."ETL_INSERT_DT",pr."ETL_PROC_WID",pr."DATASOURCE",
       pr."LINE_OF_BUSINESS"
  from vw_product_d pr 
  left outer join  W_PRODUCT_HIERARCHY_MAP g on g.PRODUCT_SRC_KEY = INTEGRATION_ID and pr.datasource = g.datasource and  CURRENT_FLG = 'Y'
  left outer join w_PRODUCT_hierarchy_g h on g.PRODUCT_HIER2_WID  = h.row_wid
;
  GRANT READ ON "DW"."VW_PRODUCT_HIERARCHY_COLO" TO "ODS";
  GRANT READ ON "DW"."VW_PRODUCT_HIERARCHY_COLO" TO "DW_RO";
