--------------------------------------------------------
--  DDL for View VW_PRODUCT_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_PRODUCT_D" ("ROW_WID", "INVENTORY_ITEM_ID", "ORGANIZATION_ID", "INTEGRATION_ID", "ITEM_NUMBER", "ITEM_DESCRIPTION", "ORGANIZATION_CODE", "PRODUCT_CATALOG_CATEGORY", "TAX_CATALOG_CATEGORY", "IL_TAX_CATEGORY", "ITEM_TYPE", "ITEM_CLASS", "LIST_PRICE_PER_UNIT", "BOM_ITEM_TYPE", "PRIMARY_UOM_CODE", "INVOICEABLE_ITEM_FLAG", "INVENTORY_ASSET_FLAG", "PURCHASING_ITEM_FLAG", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "LINE_OF_BUSINESS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        ROW_WID,
        INVENTORY_ITEM_ID,
        ORGANIZATION_ID,
        INTEGRATION_ID,
        ITEM_NUMBER,
        ITEM_DESCRIPTION,
        ORGANIZATION_CODE,
        PRODUCT_CATALOG_CATEGORY,
        TAX_CATALOG_CATEGORY,
        IL_TAX_CATEGORY,
        ITEM_TYPE,
        ITEM_CLASS,
        LIST_PRICE_PER_UNIT,
        BOM_ITEM_TYPE,
        PRIMARY_UOM_CODE,
        INVOICEABLE_ITEM_FLAG,
        INVENTORY_ASSET_FLAG,
        PURCHASING_ITEM_FLAG,
        CREATED_ON_DT,
        CHANGED_ON_DT,
        ETL_UPDATE_DT,
        ETL_INSERT_DT,
        ETL_PROC_WID,
        DATASOURCE,
         CASE  
    WHEN  UPPER(Datasource) = 'YARDI' THEN 'Scale' 
    WHEN  UPPER(Datasource) = 'SFDC' THEN 'Scale' 
    WHEN  UPPER(Datasource) = 'APPTUS' THEN 'EMEA Colo' 
    WHEN  UPPER(Datasource) = 'FUSION' THEN 'NA Colo' ELSE 'Other' 
 END  Line_of_Business
    FROM
        w_product_d
;
  GRANT READ ON "DW"."VW_PRODUCT_D" TO "ODS";
  GRANT READ ON "DW"."VW_PRODUCT_D" TO "DW_RO";
