--------------------------------------------------------
--  DDL for View VW_PROPERTY_SNAPSHOT_CONTROL_G
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_PROPERTY_SNAPSHOT_CONTROL_G" ("SNAPSHOT_PERIOD", "SNAPSHOT_CHANGED_DT", "SNAPSHOT_CREATED_DT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT TO_CHAR(MONTH_ID), CHANGED_ON_DT,CREATED_ON_DT FROM W_SUPPL_SNAPSHOT_CONTROL_G WHERE PROPERTY_LOCK_FLG='N'
UNION ALL
SELECT 'LIVE', SYSDATE, SYSDATE FROM DUAL
;
  GRANT SELECT ON "DW"."VW_PROPERTY_SNAPSHOT_CONTROL_G" TO "ODS";
  GRANT READ ON "DW"."VW_PROPERTY_SNAPSHOT_CONTROL_G" TO "ODS";
  GRANT SELECT ON "DW"."VW_PROPERTY_SNAPSHOT_CONTROL_G" TO "DW_RO";
  GRANT READ ON "DW"."VW_PROPERTY_SNAPSHOT_CONTROL_G" TO "DW_RO";
