--------------------------------------------------------
--  DDL for View VW_REVENUE_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_REVENUE_F" ("CUSTOMER_WID", "SUBSCRIPTION_WID", "PROPERTY_WID", "PRODUCT_WID", "ALLOCATION_STATUS", "ALLOCATION_PENDING_REASON", "CUSTOMER_CONTRACT_DATE", "CONTR_CUR_NONEXEMPT_TRX_PRICE", "CONTRACT_MODIFICATION_DATE", "CONTR_CUR_TOTAL_BILLED_AMT", "EXCHANGE_RATE_DATE", "COMMENTS", "LAST_UPDATE_DATE", "STANDALONE_SALES_FLAG", "LATEST_VERSION_DATE", "CONTRACT_CLASSIFICATION_CODE", "FULL_SATISFACTION_DATE", "CONTR_CUR_MOD_DATE_ALLOC_AMT", "CONTRACT_CURRENCY_CODE", "EXCL_FROM_AUTO_WRITEOFF_FLAG", "CUSTOMER_CONTRACT_NUMBER", "SINGLE_OBLIGATION_FLAG", "LATEST_REVISION_INTENT_CODE", "SATISFACTION_STATUS", "HEADER_CREATED_BY", "CUSTOMER_CONTRACT_HEADER_ID", "LEGAL_ENTITY_ID", "CUSTOMER_CONTRACT_FREEZE_DATE", "LATEST_IMMATERIAL_CHANGE_CODE", "HEADER_LAST_UPDATED_BY", "LAST_ACTIVITY_DATE", "CONTRACT_GROUP_NUMBER", "ALLOCATION_TYPE", "CONTR_CUR_TOTAL_RECOG_REV_AMT", "EXCHANGE_RATE_TYPE", "CREATION_DATE", "REFERENCE", "REVIEW_STATUS", "PAYMENT_CONFIRM_FLAG", "ADJUSTMENT_STATUS_CODE", "CONTR_CUR_TRANSACTION_PRICE", "SOURCE_DOCUMENTS_LINES_LINE_NUM", "SOURCE_DOCUMENTS_LINES_RECURRING_FLAG", "SOURCE_DOCUMENTS_LINES_VERSION_FLAG", "SOURCE_DOCUMENTS_PAYMENT_TERM_NAME", "SOURCE_DOCUMENTS_LINES_DOCUMENT_DATE", "SOURCE_DOCUMENTS_LINES_TERMINATION_DATE", "SOURCE_DOCUMENTS_DOCUMENT_NUMBER", "SOURCE_DOCUMENTS_LINES_ADD_TO_CONTRACT_ACTION_CODE", "SOURCE_DOCUMENTS_LINES_RECURRING_PATTERN_CODE", "SOURCE_DOCUMENTS_DOCUMENT_DATE", "SOURCE_DOCUMENTS_LINES_ACCOUNTING_RULE_NAME", "SOURCE_DOCUMENTS_LINES_COMMENTS", "SOURCE_DOCUMENTS_LINES_UOM_CODE", "SOURCE_DOCUMENTS_LAST_UPDATE_DATE", "SOURCE_DOCUMENTS_SALES_AGREEMENT_NUMBER", "SOURCE_DOCUMENTS_LINES_ACCOUNTING_RULE_ID", "SOURCE_DOCUMENTS_LINES_ADD_TO_CONTRACT_FLAG", "SOURCE_DOCUMENTS_SOURCE_TYPE_CODE", "SOURCE_DOCUMENTS_LINES_DOCUMENT_LINE_ID", "SOURCE_DOCUMENTS_LINES_IMMATERIAL_CHANGE_CODE", "SOURCE_DOCUMENTS_LINES_RECURRING_FREQUENCY", "SOURCE_DOCUMENTS_LINES_LINE_TYPE", "SOURCE_DOCUMENTS_LINES_VERSION_NUMBER", "SOURCE_DOCUMENTS_SOURCE_SYSTEM", "SOURCE_DOCUMENTS_LINES_LAST_UPDATE_DATE", "SOURCE_DOCUMENTS_CURRENCY_CODE", "SOURCE_DOCUMENTS_LINES_RECUR_LINE_COPY_NUM", "SOURCE_DOCUMENTS_LINES_MANUAL_REVIEW_REQUIRED_FLAG", "SOURCE_DOCUMENTS_LINES_DELIVERY_STATUS", "SOURCE_DOCUMENTS_LINES_REVISION_INTENT_TYPE_CODE", "SOURCE_DOCUMENTS_LINES_LINE_LAST_UPDATE_DATE", "SOURCE_DOCUMENTS_LINES_DATA_TRANSFORMATION_STATUS", "SOURCE_DOCUMENTS_LINES_RULE_START_DATE", "SOURCE_DOCUMENTS_CUST_PO_NUMBER", "APPLICATION_APPLICATION_NAME", "SOURCE_DOCUMENTS_LINES_DELIVERY_DATE", "SOURCE_DOCUMENTS_LINES_SATISFACTION_MEASUREMENT_MODEL", "SOURCE_DOCUMENTS_LINES_BILL_TO_CUSTOMER_ID", "SOURCE_DOCUMENTS_LINES_DOC_ID_INT1", "SOURCE_DOCUMENTS_LINES_DOCUMENT_ID", "SOURCE_DOCUMENTS_LINES_ITEM_NUMBER", "SOURCE_DOCUMENTS_LINES_QUANTITY", "PRODUCT_SUBSCRIPTION_PRODUCT_ID", "PRODUCT_VERSION_TYPE", "PRODUCT_NUMBER", "SUBSCRIPTION_PRODUCT_PUID", "SALES_PRODUCT_TYPE", "PRODUCT_NAME", "PRODUCT_STATUS", "PRODUCT_START_DATE", "PRODUCT_END_DATE", "PRODUCT_CLOSE_SET_ID", "PRODUCT_CLOSE_REASON", "PRODUCT_CLOSE_CREDIT_METHOD", "PRODUCT_CANCEL_SET_ID", "PRODUCT_CANCEL_REASON", "PRODUCT_AMEND_REASON", "PRODUCT_AMEND_EFFECTIVE_DATE", "PRODUCT_AMEND_DESCRIPTION", "PRODUCT_AMEND_CREDIT_METHOD", "PRODUCT_QUANTITY", "PRODUCT_ITEM_UOM", "PRODUCT_INVENTORY_ITEM_ID", "PRODUCT_DEFINITION_ORG_ID", "PRODUCT_SOURCE_SYSTEM", "PRODUCT_SOURCE_KEY", "PRODUCT_SOURCE_NUMBER", "PRODUCT_MONTHLY_RECURRING_REVENUE", "PRODUCT_SOURCE_LINE_KEY", "PRODUCT_SOURCE_LINE_NUMBER", "PRODUCT_CLOSED_DATE", "PRODUCT_CANCELED_DATE", "PRODUCT_RENEWED_DATE", "PRODUCT_PRICE_LIST_ID", "PRODUCT_PRICE_UOM", "PRODUCT_UNIT_PRICE", "PRODUCT_PRICING_ERROR", "PRODUCT_OVERRIDE_PRICELIST_YN", "PRODUCT_PRICE_AS_OF", "PRODUCT_PRICE_TRANSACTION_ON", "PRODUCT_PRICE_DURING_BILLING_YN", "PRODUCT_PERPETUAL_YN", "PRODUCT_NET_PRICE", "PRODUCT_ESTIMATED_TAX", "PRODUCT_TOTAL", "PRODUCT_ONETIME_AMOUNT", "PRODUCT_RECURRING_AMOUNT", "PRODUCT_INVOICED_AMOUNT", "PRODUCT_CANCELED_AMOUNT", "PRODUCT_CLOSED_AMOUNT", "PRODUCT_CREDITED_AMOUNT", "PRODUCT_SUPPRESSED_CREDIT_AMOUNT", "PRODUCT_USAGE_INVOICED_AMOUNT", "PRODUCT_USAGE_CREDITED_AMOUNT", "PRODUCT_USAGE_SUPPRESSED_CREDIT_AMT", "PRODUCT_CURRENCY", "PRODUCT_BILL_TO_ACCT_ID", "PRODUCT_BILL_TO_SITE_USE_ID", "PRODUCT_SHIP_TO_PARTY_ID", "PRODUCT_SHIP_TO_PARTY_SITE_ID", "PRODUCT_TRANSACTION_TYPE_NAME", "PRODUCT_BILLING_DATE_CODE", "PRODUCT_BILL_ON_DAY", "PRODUCT_BILLING_OFFSET_DAYS", "PRODUCT_BILLING_DATE_CODE_USED", "PRODUCT_BILL_ON_DAY_USED", "PRODUCT_BILLING_OFFSET_DAYS_USED", "PRODUCT_BILLING_FREQ", "PRODUCT_BILLING_FREQ_USED", "PRODUCT_INVOICING_RULE_ID", "PRODUCT_INVOICING_RULE_ID_USED", "PRODUCT_ACCOUNTING_RULE_ID", "PRODUCT_INVOICE_TEXT", "PRODUCT_PAYMENT_TERM_ID", "PRODUCT_PAYMENT_METHOD", "PRODUCT_PO_NUMBER", "PRODUCT_WIRE_NUMBER", "PRODUCT_INSTR_ASSIGNMENT_ID", "PRODUCT_TRXN_EXTENSION_ID", "PRODUCT_PAYMENT_SET_ID", "PRODUCT_TAX_EXEMPTION_CONTROL", "PRODUCT_EXEMPT_CERTIFICATE_NUMBER", "PRODUCT_EXEMPT_REASON", "PRODUCT_OUTPUT_TAX_CLASSIFICATION", "PRODUCT_FISC_CLASSIFICATION", "PRODUCT_TYPE", "PRODUCT_TRX_BUSINESS_CATEGORY", "PRODUCT_TAX_ERROR", "PRODUCT_COVERAGE_SCHEDULE_ID", "PRODUCT_RENEWAL_TYPE", "PRODUCT_OBJECT_VERSION_NUMBER", "PRODUCT_CREATED_BY", "PRODUCT_CREATION_DATE", "PRODUCT_LAST_UPDATED_BY", "PRODUCT_LAST_UPDATE_DATE", "PRODUCT_LAST_UPDATE_LOGIN", "PRODUCT_CORP_CURRENCY_CODE", "PRODUCT_CURCY_CONV_RATE_TYPE", "PRODUCT_EXTERNAL_ASSET_KEY", "PRODUCT_EXTERNAL_PARENT_ASSET_KEY", "PRODUCT_EXTERNAL_ROOT_ASSET_KEY", "PRODUCT_NEXT_PRICING_DATE", "PRODUCT_PRICE_LIST_NAME", "PRODUCT_EXTERNAL_PRICE_BOOK_ID", "PRODUCT_EXTERNAL_PRICE_BOOK_NAME", "PRODUCT_PRICING_TERM_TYPE", "PRODUCT_PRICING_TERM_DURATION", "PRODUCT_PRICING_TERM_PERIOD", "PRODUCT_PRICING_TERM_START_DATE", "PRODUCT_PRICING_TERM_PRICING_METHOD", "PRODUCT_PRICING_TERM_ADJUSTMENT_PCT", "PRODUCT_ENABLE_PRICING_TERM_YN", "PRODUCT_NEXT_BILL_START_DATE", "PRODUCT_SUMMARIZED_BILLING_YN", "PRODUCT_SUSPENDED_DATE", "PRODUCT_SUSPEND_REASON", "PRODUCT_SUSPEND_CREDIT_METHOD", "PRODUCT_CHURN_PROBABILITY", "PRODUCT_EARLY_TERMINATION_PENALTY", "PRODUCT_GRACE_PERIOD", "PRODUCT_PENALTY_VALUE", "PRODUCT_EARLY_TERMINATION_FEE", "PRODUCT_CREDIT_ISSUED_YN", "PRODUCT_CHURN_PREDICTION_TREND", "PRODUCT_PRICE_ADJUSTMENT_TYPE", "PRODUCT_PRICE_ADJUSTMENT_BASIS", "PRODUCT_PRICE_ADJUSTMENT_PERCENT", "PRODUCT_INTERFACE_OFFSET_DAYS", "ASSET_IDENTIFICATION_NUMBER", "BILL_TO_CONTACT_ROLE_ID", "COPY_PRICING", "CUSTOMER_TERMINATION_NOTIFICATION_PERIOD", "LEGACY_PRODUCT_ID", "PURCHASE_ORDER_NUMBER", "SERVICE_ORDER_NUMBER", "SUB_CASE_NUMBER_TASK_ID", "EXCLUDE_FROM_OA_REPORTING", "CASE_NUMBER_PROJECT_ID", "OBLIG_PERFOBLIGATIONID", "DOC_LINES_DFF_SM_CHARGE_NAME", "OBILG_LINE_DISTS_PERFOBLIGATIONLINDISTSEOACCOUNTINGDATE", "OBILG_PERFOBLIGATIONSCONTRCURFMVAMT", "OBILG_PERFOBLIGATIONSCONTRCURNETLINEAMT", "OBILG_PERFOBLIGATIONSCONTRCURTOTALLOCAMT", "OBILG_PERFOBLIGATIONSCONTRCURTOTCARVEOUTAMT", "OBILG_PERFOBLIGATIONSCONTRCURTOTNETCONSIDERAMT", "OBILG_PERFOBLIGATIONSCONTRCURTOTALBILLEDAMT", "OBILG_PERFOBLIGATIONSCONTRCURTOTALRECOGREVAMT", "OBILG_PERFOBLIGATIONSCOSTAMOUNT", "PERFOBLIGATIONSPERFOBLIGATIONNUMBER", "CUSTCONTHEADERSCUSTOMERCONTRACTNUMBER", "PERFOBLIGATIONSCONTRCURTOTALLOCAMT", "PERFOBLIGATIONLINDISTSEOORIGINALACCOUNTINGDATE", "OBILG_LINE_PERFOBLIGATIONLINDISTSEOACCTDAMOUNT", "OBILG_LINE_PERFOBLIGATIONLINDISTSEOAMOUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
  nvl(c.row_wid,-1) customer_wid,
  fusion_oss_subscriptions.subscription_id               subscription_wid,
  nvl(p.row_wid,-1) property_wid,
  nvl(w_product_d.row_wid, -1) product_wid,
    custcontheadersallocationstatus                        allocation_status,
    custcontheadersallocationpendingreason                 allocation_pending_reason,
    custcontheaderscustomercontractdate                    customer_contract_date,
    customercontractheaderscontrcurnonexempttrxprice       contr_cur_nonexempt_trx_price,
    customercontractheaderscontractmodificationdate        contract_modification_date,
    custcontheaderscontrcurtotalbilledamt                  contr_cur_total_billed_amt,
    custcontheadersexchangeratedate                        exchange_rate_date,
    custcontheaderscomments                                comments,
    custcontheaderslastupdatedate                          last_update_date,
    custcontheadersstandalonesalesflag                     standalone_sales_flag,
    customercontractheaderslatestversiondate               latest_version_date,
    custcontheaderscontractclassificationcode              contract_classification_code,
    customercontractheadersfullsatisfactiondate            full_satisfaction_date,
    customercontractheaderscontrcurmoddateallocamt         contr_cur_mod_date_alloc_amt,
    custcontheaderscontractcurrencycode                    contract_currency_code,
    customercontractheadersexclfromautowriteoffflag        excl_from_auto_writeoff_flag,
    custcontheaderscustomercontractnumber                  customer_contract_number,
    custcontheaderssingleobligationflag                    single_obligation_flag,
    customercontractheaderslatestrevisionintentcode        latest_revision_intent_code,
    customercontractheaderssatisfactionstatus              satisfaction_status,
    custcontheaderscreatedby                               header_created_by,
    customercontractheaderid                               customer_contract_header_id,
    custcontheaderslegalentityid                           legal_entity_id,
    custcontheaderscustomercontractfreezedate              customer_contract_freeze_date,
    customercontractheaderslatestimmaterialchangecode      latest_immaterial_change_code,
    customercontractheaderslastupdatedby                   header_last_updated_by,
    customercontractheaderslastactivitydate                last_activity_date,
    customercontractheaderscontractgroupnumber             contract_group_number,
    custcontheadersallocationtype                          allocation_type,
    custcontheaderscontrcurtotalrecogrevamt                contr_cur_total_recog_rev_amt,
    --customercontractheaderscreatedby                       created_by,
    custcontheadersexchangeratetype                        exchange_rate_type,
    custcontheaderscreationdate                            creation_date,
    custcontheadersreference                               reference,
    custcontheadersreviewstatus                            review_status,
    custcontheaderspaymentconfirmflag                      payment_confirm_flag,
    customercontractheadersadjustmentstatuscode            adjustment_status_code,
    --custcontheaderslastupdatedby                           last_updated_by,
    custcontheaderscontrcurtransactionprice                contr_cur_transaction_price,
    sourcedoclineslinenum                                  source_documents_lines_line_num,
    sourcedoclinesrecurringflag                            source_documents_lines_recurring_flag,
    sourcedoclinesversionflag                              source_documents_lines_version_flag,
    sourcedocumentspaymenttermname                         source_documents_payment_term_name,
    sourcedoclinesdocumentdate                             source_documents_lines_document_date,
    sourcedoclinesterminationdate                          source_documents_lines_termination_date,
    sourcedocumentsdocumentnumber                          source_documents_document_number,
    sourcedoclinesaddtocontractactioncode                  source_documents_lines_add_to_contract_action_code,
    sourcedoclinesrecurringpatterncode                     source_documents_lines_recurring_pattern_code,
    sourcedocumentsdocumentdate                            source_documents_document_date,
    sourcedoclinesaccountingrulename                       source_documents_lines_accounting_rule_name,
    sourcedoclinescomments                                 source_documents_lines_comments,
    sourcedoclinesuomcode                                  source_documents_lines_uom_code,
    sourcedocumentslastupdatedate                          source_documents_last_update_date,
    sourcedocumentssalesagreementnumber                    source_documents_sales_agreement_number,
    sourcedoclinesaccountingruleid                         source_documents_lines_accounting_rule_id,
    sourcedoclinesaddtocontractflag                        source_documents_lines_add_to_contract_flag,
    sourcedocumentssourcetypecode                          source_documents_source_type_code,
    sourcedoclinesdocumentlineid                           source_documents_lines_document_line_id,
    sourcedoclinesimmaterialchangecode                     source_documents_lines_immaterial_change_code,
    sourcedoclinesrecurringfrequency                       source_documents_lines_recurring_frequency,
    sourcedoclineslinetype                                 source_documents_lines_line_type,
    sourcedoclinesversionnumber                            source_documents_lines_version_number,
    sourcedocumentssourcesystem                            source_documents_source_system,
    sourcedoclineslastupdatedate                           source_documents_lines_last_update_date,
    sourcedocumentscurrencycode                            source_documents_currency_code,
    sourcedoclinesrecurlinecopynum                         source_documents_lines_recur_line_copy_num,
    sourcedoclinesmanualreviewrequiredflag                 source_documents_lines_manual_review_required_flag,
    sourcedoclinesdeliverystatus                           source_documents_lines_delivery_status,
    sourcedoclinesrevisionintenttypecode                   source_documents_lines_revision_intent_type_code,
    sourcedoclineslinelastupdatedate                       source_documents_lines_line_last_update_date,
    sourcedoclinesdatatransformationstatus                 source_documents_lines_data_transformation_status,
    sourcedoclinesrulestartdate                            source_documents_lines_rule_start_date,
    sourcedocumentscustponumber                            source_documents_cust_po_number,
    applicationpeoapplicationname                          application_application_name,
    sourcedoclinesdeliverydate                             source_documents_lines_delivery_date,
    sourcedoclinessatisfactionmeasurementmodel             source_documents_lines_satisfaction_measurement_model,
    sourcedoclinesbilltocustomerid                         source_documents_lines_bill_to_customer_id,
    sourcedoclinesdocidint1                                source_documents_lines_doc_id_int1,
    sourcedoclinesdocumentid                               source_documents_lines_document_id,
    sourcedoclinesitemnumber                               source_documents_lines_item_number,
    sourcedoclinesquantity                                 source_documents_lines_quantity,
    
    
    fusion_oss_products.subscription_product_id            product_subscription_product_id,
        -- fusion_oss_products.subscription_id                    product_subscription_id,
    fusion_oss_products.version_type                       product_version_type,
    fusion_oss_products.product_number                     product_number,
    fusion_oss_products.subscription_product_puid          subscription_product_puid,
    fusion_oss_products.sales_product_type                 sales_product_type,
    fusion_oss_products.product_name                       product_name,
    fusion_oss_products.status                             product_status,
    CAST(to_timestamp_tz(fusion_oss_products.start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM') AS
    DATE) product_start_date,
    CAST(to_timestamp_tz(fusion_oss_products.end_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM') AS
    DATE) product_end_date,
    fusion_oss_products.close_set_id                       product_close_set_id,
    fusion_oss_products.close_reason                       product_close_reason,
    fusion_oss_products.close_credit_method                product_close_credit_method,
    fusion_oss_products.cancel_set_id                      product_cancel_set_id,
    fusion_oss_products.cancel_reason                      product_cancel_reason,
    fusion_oss_products.amend_reason                       product_amend_reason,
    CAST(to_timestamp_tz(fusion_oss_products.amend_effective_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_amend_effective_date,
    fusion_oss_products.amend_description                  product_amend_description,
    fusion_oss_products.amend_credit_method                product_amend_credit_method,
    fusion_oss_products.quantity                           product_quantity,
    fusion_oss_products.item_uom                           product_item_uom,
    fusion_oss_products.inventory_item_id                  product_inventory_item_id,
    fusion_oss_products.definition_org_id                  product_definition_org_id,
    fusion_oss_products.source_system                      product_source_system,
    fusion_oss_products.source_key                         product_source_key,
    fusion_oss_products.source_number                      product_source_number,
    fusion_oss_products.monthly_recurring_revenue          product_monthly_recurring_revenue,
    fusion_oss_products.source_line_key                    product_source_line_key,
    fusion_oss_products.source_line_number                 product_source_line_number,
    CAST(to_timestamp_tz(fusion_oss_products.closed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM')
    AS DATE) product_closed_date,
    CAST(to_timestamp_tz(fusion_oss_products.canceled_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_canceled_date,
    CAST(to_timestamp_tz(fusion_oss_products.renewed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_renewed_date,
    fusion_oss_products.price_list_id                      product_price_list_id,
    fusion_oss_products.price_uom                          product_price_uom,
    fusion_oss_products.unit_price                         product_unit_price,
    fusion_oss_products.pricing_error                      product_pricing_error,
    fusion_oss_products.override_pricelist_yn              product_override_pricelist_yn,
    fusion_oss_products.price_as_of                        product_price_as_of,
    fusion_oss_products.price_transaction_on               product_price_transaction_on,
    fusion_oss_products.price_during_billing_yn            product_price_during_billing_yn,
    fusion_oss_products.perpetual_yn                       product_perpetual_yn,
    fusion_oss_products.product_net_price                  product_net_price,
    fusion_oss_products.estimated_tax                      product_estimated_tax,
    fusion_oss_products.product_total                      product_total,
    fusion_oss_products.onetime_amount                     product_onetime_amount,
    fusion_oss_products.recurring_amount                   product_recurring_amount,
    fusion_oss_products.invoiced_amount                    product_invoiced_amount,
    fusion_oss_products.canceled_amount                    product_canceled_amount,
    fusion_oss_products.closed_amount                      product_closed_amount,
    fusion_oss_products.credited_amount                    product_credited_amount,
    fusion_oss_products.suppressed_credit_amount           product_suppressed_credit_amount,
    fusion_oss_products.usage_invoiced_amount              product_usage_invoiced_amount,
    fusion_oss_products.usage_credited_amount              product_usage_credited_amount,
    fusion_oss_products.usage_suppressed_credit_amt        product_usage_suppressed_credit_amt,
    fusion_oss_products.currency                           product_currency,
    fusion_oss_products.bill_to_acct_id                    product_bill_to_acct_id,
    fusion_oss_products.bill_to_site_use_id                product_bill_to_site_use_id,
    fusion_oss_products.ship_to_party_id                   product_ship_to_party_id,
    fusion_oss_products.ship_to_party_site_id              product_ship_to_party_site_id,
    fusion_oss_products.transaction_type_name              product_transaction_type_name,
    fusion_oss_products.billing_date_code                  product_billing_date_code,
    fusion_oss_products.bill_on_day                        product_bill_on_day,
    fusion_oss_products.billing_offset_days                product_billing_offset_days,
    fusion_oss_products.billing_date_code_used             product_billing_date_code_used,
    fusion_oss_products.bill_on_day_used                   product_bill_on_day_used,
    fusion_oss_products.billing_offset_days_used           product_billing_offset_days_used,
    fusion_oss_products.billing_freq                       product_billing_freq,
    fusion_oss_products.billing_freq_used                  product_billing_freq_used,
    fusion_oss_products.invoicing_rule_id                  product_invoicing_rule_id,
    fusion_oss_products.invoicing_rule_id_used             product_invoicing_rule_id_used,
    fusion_oss_products.accounting_rule_id                 product_accounting_rule_id,
    fusion_oss_products.invoice_text                       product_invoice_text,
    fusion_oss_products.payment_term_id                    product_payment_term_id,
    fusion_oss_products.payment_method                     product_payment_method,
    fusion_oss_products.po_number                          product_po_number,
    fusion_oss_products.wire_number                        product_wire_number,
    fusion_oss_products.instr_assignment_id                product_instr_assignment_id,
    fusion_oss_products.trxn_extension_id                  product_trxn_extension_id,
    fusion_oss_products.payment_set_id                     product_payment_set_id,
    fusion_oss_products.tax_exemption_control              product_tax_exemption_control,
    fusion_oss_products.exempt_certificate_number          product_exempt_certificate_number,
    fusion_oss_products.exempt_reason                      product_exempt_reason,
    fusion_oss_products.output_tax_classification          product_output_tax_classification,
    fusion_oss_products.product_fisc_classification        product_fisc_classification,
    fusion_oss_products.product_type                       product_type,
    fusion_oss_products.trx_business_category              product_trx_business_category,
    fusion_oss_products.tax_error                          product_tax_error,
    fusion_oss_products.coverage_schedule_id               product_coverage_schedule_id,
    fusion_oss_products.renewal_type                       product_renewal_type,
    fusion_oss_products.object_version_number              product_object_version_number,
    fusion_oss_products.created_by                         product_created_by,
    CAST(to_timestamp_tz(fusion_oss_products.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_creation_date,
    fusion_oss_products.last_updated_by                    product_last_updated_by,
    fusion_oss_products.last_update_date                   product_last_update_date,
    fusion_oss_products.last_update_login                  product_last_update_login,
    fusion_oss_products.corp_currency_code                 product_corp_currency_code,
    fusion_oss_products.curcy_conv_rate_type               product_curcy_conv_rate_type,
    fusion_oss_products.external_asset_key                 product_external_asset_key,
    fusion_oss_products.external_parent_asset_key          product_external_parent_asset_key,
    fusion_oss_products.external_root_asset_key            product_external_root_asset_key,
    CAST(to_timestamp_tz(fusion_oss_products.next_pricing_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_next_pricing_date,
    fusion_oss_products.price_list_name                    product_price_list_name,
    fusion_oss_products.external_price_book_id             product_external_price_book_id,
    fusion_oss_products.external_price_book_name           product_external_price_book_name,
    fusion_oss_products.pricing_term_type                  product_pricing_term_type,
    fusion_oss_products.pricing_term_duration              product_pricing_term_duration,
    fusion_oss_products.pricing_term_period                product_pricing_term_period,
    CAST(to_timestamp_tz(fusion_oss_products.pricing_term_start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_pricing_term_start_date,
    fusion_oss_products.pricing_term_pricing_method        product_pricing_term_pricing_method,
    fusion_oss_products.pricing_term_adjustment_pct        product_pricing_term_adjustment_pct,
    fusion_oss_products.enable_pricing_term_yn             product_enable_pricing_term_yn,
    CAST(to_timestamp_tz(fusion_oss_products.next_bill_start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_next_bill_start_date,
    fusion_oss_products.summarized_billing_yn              product_summarized_billing_yn,
    CAST(to_timestamp_tz(fusion_oss_products.suspended_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
    ) AS DATE) product_suspended_date,
    fusion_oss_products.suspend_reason                     product_suspend_reason,
    fusion_oss_products.suspend_credit_method              product_suspend_credit_method,
    fusion_oss_products.churn_probability                  product_churn_probability,
    fusion_oss_products.early_termination_penalty          product_early_termination_penalty,
    fusion_oss_products.grace_period                       product_grace_period,
    fusion_oss_products.penalty_value                      product_penalty_value,
    fusion_oss_products.early_termination_fee              product_early_termination_fee,
    fusion_oss_products.credit_issued_yn                   product_credit_issued_yn,
    fusion_oss_products.churn_prediction_trend             product_churn_prediction_trend,
    fusion_oss_products.price_adjustment_type              product_price_adjustment_type,
    fusion_oss_products.price_adjustment_basis             product_price_adjustment_basis,
    fusion_oss_products.price_adjustment_percent           product_price_adjustment_percent,
    fusion_oss_products.interface_offset_days              product_interface_offset_days,
    fusion_oss_products.extn_attribute_char003             Asset_Identification_Number,
    fusion_oss_products.extn_attribute_char004             Bill_To_Contact_Role_ID,
    fusion_oss_products.extn_attribute_char005             Copy_Pricing,
    fusion_oss_products.extn_attribute_char007             Customer_Termination_Notification_Period,
    fusion_oss_products.extn_attribute_char008             Legacy_Product_ID,
    fusion_oss_products.extn_attribute_char009             Purchase_Order_Number,
    fusion_oss_products.extn_attribute_char010             Service_Order_Number,
    fusion_oss_products.extn_attribute_char011             Sub_Case_Number_Task_ID,
    fusion_oss_products.extn_attribute_char012             Exclude_from_OA_Reporting,
    fusion_oss_products.extn_attribute_char013             Case_Number_Project_ID,
    fusion_vrm_obligations.PERFOBLIGATIONID        OBLIG_PERFOBLIGATIONID , 
    FUSION_VRM_SRC_DOC_LINES_DFF.SM_CHARGE_NAME_    DOC_LINES_DFF_SM_CHARGE_NAME,
    fusion_vrm_obligat_line_dists.PERFOBLIGATIONLINDISTSEOACCOUNTINGDATE OBILG_LINE_DISTS_PERFOBLIGATIONLINDISTSEOACCOUNTINGDATE ,
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURFMVAMT   OBILG_PERFOBLIGATIONSCONTRCURFMVAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURNETLINEAMT   OBILG_PERFOBLIGATIONSCONTRCURNETLINEAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURTOTALLOCAMT  OBILG_PERFOBLIGATIONSCONTRCURTOTALLOCAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURTOTCARVEOUTAMT   OBILG_PERFOBLIGATIONSCONTRCURTOTCARVEOUTAMT,
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURTOTNETCONSIDERAMT    OBILG_PERFOBLIGATIONSCONTRCURTOTNETCONSIDERAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURTOTALBILLEDAMT   OBILG_PERFOBLIGATIONSCONTRCURTOTALBILLEDAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCONTRCURTOTALRECOGREVAMT OBILG_PERFOBLIGATIONSCONTRCURTOTALRECOGREVAMT, 
    fusion_vrm_obligations.PERFOBLIGATIONSCOSTAMOUNT  OBILG_PERFOBLIGATIONSCOSTAMOUNT,
	fusion_vrm_obligations.PERFOBLIGATIONSPERFOBLIGATIONNUMBER			PERFOBLIGATIONSPERFOBLIGATIONNUMBER,
	fusion_vrm_cust_contra_headers.CUSTCONTHEADERSCUSTOMERCONTRACTNUMBER	CUSTCONTHEADERSCUSTOMERCONTRACTNUMBER,
	FUSION_VRM_OBLIGATIONS.PERFOBLIGATIONSCONTRCURTOTALLOCAMT           PERFOBLIGATIONSCONTRCURTOTALLOCAMT,
	fusion_vrm_obligat_line_dists.PERFOBLIGATIONLINDISTSEOORIGINALACCOUNTINGDATE  PERFOBLIGATIONLINDISTSEOORIGINALACCOUNTINGDATE,
    fusion_vrm_obligat_line_dists.PERFOBLIGATIONLINDISTSEOACCTDAMOUNT   OBILG_LINE_PERFOBLIGATIONLINDISTSEOACCTDAMOUNT, 
    fusion_vrm_obligat_line_dists.PERFOBLIGATIONLINDISTSEOAMOUNT        OBILG_LINE_PERFOBLIGATIONLINDISTSEOAMOUNT
FROM
    ods.fusion_vrm_cust_contra_headers
    INNER JOIN ods.fusion_oss_subscriptions ON fusion_oss_subscriptions.subscription_number = customercontractheaderscontractgroupnumber
    INNER JOIN ods.fusion_oss_products ON fusion_oss_products.subscription_id = fusion_oss_subscriptions.subscription_id
    INNER JOIN ods.fusion_vrm_source_doc_lines ON fusion_oss_products.subscription_id = sourcedoclinesdocidint1
                                                    AND sourcedoclinesitemnumber = product_name
                                                    AND item_uom = sourcedoclinesuomcode
                                                    AND fusion_oss_products.bill_to_acct_id = sourcedoclinesbilltocustomerid
                                                    and product_number = sourcedoclineslinenum 
                                                    AND sourcedoclinesquantity = quantity
    INNER JOIN ods.fusion_vrm_obligations       on fusion_vrm_obligations.perfobligationscustomercontractheaderid = fusion_vrm_cust_contra_headers.customercontractheaderid
    INNER JOIN ods.fusion_vrm_obligation_lines  on fusion_vrm_source_doc_lines.sourcedoclinesdocumentlineid = fusion_vrm_obligation_lines.perfobligationlinesdocumentlineid
                                                    and fusion_vrm_obligations.perfobligationid = fusion_vrm_obligation_lines.PERFOBLIGATIONSPERFOBLIGATIONID1
    INNER JOIN ods.fusion_vrm_obligat_line_dists on fusion_vrm_obligat_line_dists.perfobligationlindistseoperfobligationlineid = fusion_vrm_obligation_lines.perfobligationlineid 
                                                    and fusion_vrm_obligat_line_dists.PERFOBLIGATIONLINDISTSEOACCOUNTCLASS IN ('ORA_REV') 
    left outer  JOIN ods.FUSION_VRM_SRC_DOC_LINES_DFF  on FUSION_VRM_SRC_DOC_LINES_DFF.S_K_5000 = fusion_vrm_source_doc_lines.SOURCEDOCLINESDOCUMENTLINEID
    LEFT JOIN dw.w_customer_d c                     ON to_char(fusion_oss_subscriptions.primary_party_id) = c.l4_legal_entity_src_key and c.current_flag = 'Y'
left join dw.w_product_d on w_product_d.INTEGRATION_ID = fusion_oss_products.INVENTORY_ITEM_ID||'~'||fusion_oss_products.DEFINITION_ORG_ID
LEFT JOIN dw.w_property_d  p ON fusion_oss_subscriptions.extn_attribute_char005 = p.master_site_code
                                    AND p.live_flag = 1
                                    AND p.leaf_level = 'Location'
;
  GRANT SELECT ON "DW"."VW_REVENUE_F" TO "DW_RO";
  GRANT READ ON "DW"."VW_REVENUE_F" TO "DW_RO";
