--------------------------------------------------------
--  DDL for Trigger TRG_W_PRODUCT_HIER_MAP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DW"."TRG_W_PRODUCT_HIER_MAP" 
BEFORE INSERT OR UPDATE
ON DW.W_PRODUCT_HIERARCHY_MAP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
   IF INSERTING THEN
      SELECT W_PRODUCT_HIERARCHY_MAP_SEQ.NEXTVAL, SYSDATE, v('APP_USER'), v('APP_USER'), SYSDATE,'Y'
      INTO   :NEW.ROW_WID,:NEW.CREATED_ON_DT, :NEW.CREATED_BY,:NEW.CHANGED_BY, :NEW.CHANGED_ON_DT,:NEW.CURRENT_FLG
            FROM DUAL;
   END IF;
    IF UPDATING THEN
      SELECT SYSDATE, v('APP_USER')
      INTO :NEW.CHANGED_ON_DT, :NEW.CHANGED_BY
            FROM DUAL;
   END IF;
END;

/
ALTER TRIGGER "DW"."TRG_W_PRODUCT_HIER_MAP" ENABLE;
