--------------------------------------------------------
--  DDL for Trigger TRG_W_PROPERTY_OPEX_LKP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DW"."TRG_W_PROPERTY_OPEX_LKP" 
BEFORE INSERT OR UPDATE
ON dw.W_PROPERTY_OPEX_LKP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
   IF INSERTING THEN
      SELECT W_PROPERTY_OPEX_seq.NEXTVAL, SYSDATE, v('APP_USER'), v('APP_USER'), SYSDATE
      INTO :NEW.ROW_WID, :NEW.CREATED_ON_DT, :NEW.CREATED_BY,:NEW.CHANGED_BY, :NEW.CHANGED_ON_DT
            FROM DUAL;
   END IF;
    IF UPDATING THEN
      SELECT SYSDATE, v('APP_USER')
      INTO :NEW.CHANGED_ON_DT, :NEW.CHANGED_BY
            FROM DUAL;
   END IF;
END;
/
ALTER TRIGGER "DW"."TRG_W_PROPERTY_OPEX_LKP" ENABLE;
