--------------------------------------------------------
--  DDL for Index SYS_AI_2vpzgsy3rx1b9
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_2vpzgsy3rx1b9" ON "DW"."W_GL_ACCOUNT_DH" ("ACCOUNT_NAME", "L1_FINANCIAL_STATEMENT", "L2_ACCOUNT_CLASS", "L3_ACCOUNT_CATEGORY", "L4_ACCOUNT_SUB_CATEGORY", "L5_ACCOUNT_GROUP", "L6_ACCOUNT_TYPE", "L7_ACCOUNT_SUB_TYPE", "ACCOUNT_CODE") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  TABLESPACE "DATA"  ;
  ALTER INDEX "DW"."SYS_AI_2vpzgsy3rx1b9"  UNUSABLE;
