--------------------------------------------------------
--  DDL for Index SYS_AI_danngfhcbzfqt
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_danngfhcbzfqt" ON "DW"."W_OCCUPANCY_PRE_F" ("PROPERTY_WID", "CUSTOMER_WID", "LEASE_TERMS_WID", "DATASOURCE", "PRODUCT_WID", "PRODUCT_HIERARCHY_WID") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ;
