--------------------------------------------------------
--  DDL for Index SYS_AI_274xa17fv4y0s
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_274xa17fv4y0s" ON "DW"."W_GL_ACCOUNT_DH" ("L1_FINANCIAL_STATEMENT", "L2_ACCOUNT_CLASS", "L3_ACCOUNT_CATEGORY", "L4_ACCOUNT_SUB_CATEGORY", "L5_ACCOUNT_GROUP", "L6_ACCOUNT_TYPE", "L7_ACCOUNT_SUB_TYPE", "ACCOUNT_NAME") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ;
