--------------------------------------------------------
--  DDL for Index SYS_AI_fr3yryum54fx9
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_fr3yryum54fx9" ON "DW"."W_PRODUCT_D" ("ITEM_NUMBER", "INTEGRATION_ID") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
