--------------------------------------------------------
--  DDL for Index SYS_AI_8958q33475f3k
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_8958q33475f3k" ON "DW"."W_GL_ACCOUNT_DH" ("L4_ACCOUNT_SUB_CATEGORY", "L1_FINANCIAL_STATEMENT") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  TABLESPACE "DATA"  ;
  ALTER INDEX "DW"."SYS_AI_8958q33475f3k"  UNUSABLE;
