--------------------------------------------------------
--  DDL for Table W_ACCOUNT_RECEIVABLE_DETAILS_F_BKP02122021
--------------------------------------------------------

  CREATE TABLE "DW"."W_ACCOUNT_RECEIVABLE_DETAILS_F_BKP02122021" 
   (	"PROPERTY_WID" NUMBER(*,0), 
	"CUSTOMER_WID" NUMBER(*,0), 
	"CURRENCY_WID" NUMBER(*,0), 
	"INVOICE_NO" NUMBER(30,0), 
	"TRANS_NUMBER" VARCHAR2(155 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGE_CODE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGE_CODE_DESC" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGE_CODE_TYPE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGE_NOTES" VARCHAR2(999 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARGE_REFERENCE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_CODE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE" NUMBER(38,12), 
	"INVOICE_DATE_WID" NUMBER(*,0), 
	"DUE_DATE_WID" NUMBER(*,0), 
	"POST_MONTH_WID" NUMBER(30,0), 
	"NET_RECEIVABLE" NUMBER(38,12), 
	"TOTAL_AR" NUMBER(38,12), 
	"AGES_0_TO_30_OWED" NUMBER(38,12), 
	"AGES_31_TO_60_OWED" NUMBER(38,12), 
	"AGES_61_TO_90_OWED" NUMBER(38,12), 
	"AGES_91_TO_120_OWED" NUMBER(38,12), 
	"OVER_120_OWED" NUMBER(38,12), 
	"PRE_PAYMENTS" NUMBER(38,12), 
	"UNAPPLIED_RECEIPTS" NUMBER(38,12), 
	"DATE_OCCURRED_WID" NUMBER(*,0), 
	"I_TYPE" NUMBER(38,12), 
	"STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PULL_DATE_WID" NUMBER(*,0), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LEGACY_SRC_KEY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
