--------------------------------------------------------
--  DDL for Table W_ACCOUNT_RECEIVABLE_SUMMARY_F
--------------------------------------------------------

  CREATE TABLE "DW"."W_ACCOUNT_RECEIVABLE_SUMMARY_F" 
   (	"PROPERTY_WID" NUMBER(*,0), 
	"CUSTOMER_WID" NUMBER(*,0), 
	"CURRENCY_WID" NUMBER(*,0), 
	"CURRENCY_CODE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE" NUMBER(38,12), 
	"NET_RECEIVABLE" NUMBER(38,12), 
	"TOTAL_AR" NUMBER(38,12), 
	"AGES_0_TO_30_OWED" NUMBER(38,12), 
	"AGES_0_TO_30_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"AGES_0_TO_30_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AGES_31_TO_60_OWED" NUMBER(38,12), 
	"AGES_31_TO_60_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"AGES_31_TO_60_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AGES_61_TO_90_OWED" NUMBER(38,12), 
	"AGES_61_TO_90_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"AGES_61_TO_90_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"AGES_91_TO_120_OWED" NUMBER(38,12), 
	"AGES_91_TO_120_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"AGES_91_TO_120_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"OVER_120_OWED" NUMBER(38,12), 
	"OVER_120_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"OVER_120_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"PRE_PAYMENTS" NUMBER(38,12), 
	"UNAPPLIED_RECEIPTS" NUMBER(38,12), 
	"UNAPPLIED_RECEIPTS_STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UNAPPLIED_RECEIPTS_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"GENERAL_COMMENT" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"GENERAL_COMMENT_DATE_CREATED" DATE, 
	"GENERAL_COMMENT_CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PERIOD" DATE, 
	"PULL_DATE_WID" NUMBER(*,0), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LEGACY_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "ODS";
  GRANT READ ON "DW"."W_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "ODS";
  GRANT SELECT ON "DW"."W_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "DW_RO";
  GRANT READ ON "DW"."W_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "DW_RO";
