--------------------------------------------------------
--  DDL for Table W_CONTACT_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_CONTACT_D" 
   (	"ROW_WID" NUMBER(*,0), 
	"CUSTOMER_WID" NUMBER(*,0), 
	"CUSTOMER_NAME" VARCHAR2(360 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_FULL_NAME" VARCHAR2(360 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_FIRST_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_LAST_NAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(70 BYTE) COLLATE "USING_NLS_COMP", 
	"STATE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_EMAIL_ADDRESS" VARCHAR2(320 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE_TYPE" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_COUNTRY_CODE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_AREA_CODE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"PRIMARY_PHONE_NUMBER" NVARCHAR2(60) COLLATE "USING_NLS_COMP", 
	"RELATIONSHIP_TYPE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATIONSHIP_PRIMARY_FLAG" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"RELATIONSHIP_STATUS" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
	"USAGES" VARCHAR2(3000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_CONTACT_D" TO "ODS";
  GRANT READ ON "DW"."W_CONTACT_D" TO "ODS";
  GRANT SELECT ON "DW"."W_CONTACT_D" TO "DW_RO";
  GRANT READ ON "DW"."W_CONTACT_D" TO "DW_RO";
