--------------------------------------------------------
--  DDL for Table W_ETL_AUDIT_LOG
--------------------------------------------------------

  CREATE TABLE "DW"."W_ETL_AUDIT_LOG" 
   (	"LOAD_PLAN_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MAPPING_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SESSION_NO" NUMBER, 
	"SOURCE_COUNT" NUMBER, 
	"TARGET_COUNT" NUMBER, 
	"SESS_START_TIME" DATE, 
	"SESS_END_TIME" DATE, 
	"PKG_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_WID" NUMBER, 
	"PKG_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LP_INSTANCE_ID" NUMBER(20,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_ETL_AUDIT_LOG" TO "DW_RO";
  GRANT READ ON "DW"."W_ETL_AUDIT_LOG" TO "DW_RO";
  GRANT SELECT ON "DW"."W_ETL_AUDIT_LOG" TO "ODS";
  GRANT READ ON "DW"."W_ETL_AUDIT_LOG" TO "ODS";
