--------------------------------------------------------
--  DDL for Table W_GL_ACCOUNT_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_GL_ACCOUNT_D" 
   (	"ROW_WID" NUMBER(*,0), 
	"ACCOUNT_SRC_KEY" NUMBER(*,0), 
	"ACCOUNT_NAME" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_CODE" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_ORDER" NUMBER(*,0), 
	"ACCOUNT_TYPE" NVARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"SIGN_FLAG" NUMBER(*,0), 
	"INCLUDE_IN_ACCOUNT_TREE" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"REPORT_TYPE" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"ACCOUNT_GROUPING" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CAPITAL_EXPENDITURE_SUB_ACCOUNT" NVARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"CATEGORY" NVARCHAR2(25) COLLATE "USING_NLS_COMP", 
	"COMP_NON_COMP_HEADER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_D" TO "ODS";
  GRANT READ ON "DW"."W_GL_ACCOUNT_D" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_D" TO "DW_RO";
  GRANT READ ON "DW"."W_GL_ACCOUNT_D" TO "DW_RO";
