--------------------------------------------------------
--  DDL for Table W_LEASE_ACTIVITY_PRE_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_LEASE_ACTIVITY_PRE_D" 
   (	"LEASE_ACTIVITY_SRC_KEY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"SNAPSHOT_PERIOD" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"SNAPSHOT_DATE" DATE, 
	"LOCK_FLAG" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTRACT_NUMBER" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LEASE_REPORTING_TYPE" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"LEASE_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ACTIVITY_STATUS" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"LEASE_DESCRIPTION" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"LEASE_COMMENTS" NVARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"REPORT_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"SIGN_DATE" DATE, 
	"START_DATE_WID" NUMBER(*,0) DEFAULT 0, 
	"END_DATE_WID" NUMBER(*,0) DEFAULT 0, 
	"SIGN_DATE_WID" NUMBER(*,0) DEFAULT 0, 
	"LEASE_COMMENCEMENT_DATE" DATE, 
	"ORIGINAL_TERM_EXPIRATION_DATE" DATE, 
	"EXPIRATION_DATE" DATE, 
	"CONTRACTUAL_START_DATE" DATE, 
	"SUITES" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RENEWAL_TYPE" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CONTRACTUAL_RENT_START_DATE" DATE, 
	"RENT_START_DATE" DATE, 
	"ORIGINAL_TERM_END_DATE" DATE, 
	"REPORTED_FLAG" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"RENT_TREND_EXCLUDED_FLAG" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"NON_LEASE_DEAL" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COMMENCEMENT_DATE_STATUS" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"RETENTION_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"GENERATION" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CASH__RENT__STABILIZES" NUMBER(3,0), 
	"RELEASE_FLAG" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PUBLISHED_FLAG" NVARCHAR2(37) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CROSS_CONNECT_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"BUSINESS_UNIT" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TELX_CASE_NUMBER" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"LEASE_CURRENCY_CODE" NVARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"LEASE_EXCHANGE_RATE" NUMBER(18,6), 
	"SIGN_PERIOD" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REPORT_PERIOD" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COMMENCEMENT_PERIOD" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SIGN_YEAR" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REPORT_YEAR" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"COMMENCEMENT_YEAR" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"REDUNDANCY" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"SOURCE" NVARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORDER_LINE_NUMBER" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"PUBLISHED_LEASE_IDENTIFIER" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"YARDI_TCODE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"UNIT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEGACY_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_TYPE_GROUP" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT_TYPE_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"EXCLUDE_FROM_LEASESTATS" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT READ ON "DW"."W_LEASE_ACTIVITY_PRE_D" TO "ODS";
  GRANT READ ON "DW"."W_LEASE_ACTIVITY_PRE_D" TO "DW_RO";
