--------------------------------------------------------
--  DDL for Table W_OCCUPANCY_PRE_F
--------------------------------------------------------

  CREATE TABLE "DW"."W_OCCUPANCY_PRE_F" 
   (	"PROPERTY_WID" NUMBER(*,0) DEFAULT 0, 
	"CUSTOMER_WID" NUMBER(*,0), 
	"LEASE_TERMS_WID" NUMBER(*,0), 
	"REPORTED_DATE_WID" NUMBER(*,0), 
	"RENTABLE_SQ_FT" NUMBER(21,6), 
	"RENTABLE_SQ_M" NUMBER(21,6), 
	"BOMA_SQ_FT" NUMBER(21,6), 
	"RAISED_FLOOR_SQ_FT" NUMBER(21,6), 
	"KW" NUMBER(21,6), 
	"MONTHLY_GAAP_RENT_NATIVE" NUMBER(21,8), 
	"MONTHLY_RENT_NATIVE" NUMBER(21,8), 
	"MONTHLY_TERMED_CONNECTIVITY_NATIVE" NUMBER(21,8), 
	"RENT_AT_EXPIRATION_NATIVE" NUMBER(21,8), 
	"CURRENT_EXPIRING_LEASE_TERM_IN_MONTHS" NUMBER(38,8), 
	"FULL_LEASE_TERM_IN_MONTHS" NUMBER(21,8), 
	"LEASE_REMAINING_TERM_IN_MONTHS" NUMBER(21,8), 
	"CURRENCY_CODE" NVARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"EXCHANGE_RATE_USD" NUMBER(21,15), 
	"EARLY_TERMINATION_TERM_IN_MONTHS" NUMBER(21,8), 
	"EARLY_TERMINATION_RENT_AT_EXPIRATION" NUMBER(21,8), 
	"LOAD_FACTOR" NUMBER(38,20), 
	"LOCKED_FLAG" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"MONTHLY_NON_TERMED_CONNECTIVITY_REVENUE_NATIVE" NUMBER(38,20), 
	"SNAPSHOT_PERIOD" NVARCHAR2(40) COLLATE "USING_NLS_COMP", 
	"SNAPSHOT_DATE" DATE, 
	"LEGACY_SRC_KEY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_WID" NUMBER(*,0), 
	"PRODUCT_HIERARCHY_WID" NUMBER(38,0) DEFAULT -1
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_OCCUPANCY_PRE_F" TO "ODS";
  GRANT READ ON "DW"."W_OCCUPANCY_PRE_F" TO "ODS";
  GRANT SELECT ON "DW"."W_OCCUPANCY_PRE_F" TO "DW_RO";
  GRANT READ ON "DW"."W_OCCUPANCY_PRE_F" TO "DW_RO";
