--------------------------------------------------------
--  DDL for Table W_OPPORTUNITY_D
--------------------------------------------------------

  CREATE TABLE "DW"."W_OPPORTUNITY_D" 
   (	"ROW_WID" NUMBER(*,0), 
	"OPPORTUNITY_SRC_KEY" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_NAME" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_OWNER" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STAGE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"COMMENTS" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"INVOICING_REMARKS" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"FORECAST_CATEGORY" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRIMARY_WIN_LOSS_REASON" NVARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"SECONDARY_WIN_LOSS_REASON" NVARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_STATUS" NVARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_DESCRIPTION" CLOB COLLATE "USING_NLS_COMP", 
	"PROBABILITY" NUMBER(38,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("OPPORTUNITY_DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "DW"."W_OPPORTUNITY_D" TO "ODS";
  GRANT READ ON "DW"."W_OPPORTUNITY_D" TO "ODS";
  GRANT SELECT ON "DW"."W_OPPORTUNITY_D" TO "DW_RO";
  GRANT READ ON "DW"."W_OPPORTUNITY_D" TO "DW_RO";
