--------------------------------------------------------
--  DDL for Table W_OPPORTUNITY_F
--------------------------------------------------------

  CREATE TABLE "DW"."W_OPPORTUNITY_F" 
   (	"OPPORTUNITY_WID" NUMBER(*,0), 
	"CUSTOMER_WID" NUMBER(*,0), 
	"PROPERTY_WID" NUMBER(*,0), 
	"TOTAL_KW" NUMBER(18,6), 
	"AMOUNT" NUMBER(18,6), 
	"ANNUALIZED_GAAP_REVENUE" NUMBER(18,6), 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER(*,0), 
	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPPORTUNITY_CLOSE_WID" NUMBER(38,0), 
	"COMMENCEMENT_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_OPPORTUNITY_F" TO "ODS";
  GRANT READ ON "DW"."W_OPPORTUNITY_F" TO "ODS";
  GRANT SELECT ON "DW"."W_OPPORTUNITY_F" TO "DW_RO";
  GRANT READ ON "DW"."W_OPPORTUNITY_F" TO "DW_RO";
