--------------------------------------------------------
--  DDL for Table W_ORDER_LOOKUP_CODES
--------------------------------------------------------

  CREATE TABLE "DW"."W_ORDER_LOOKUP_CODES" 
   (	"LOOKUP_TYPE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"LOOKUP_VALUE" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMENTS" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_BY" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
