--------------------------------------------------------
--  DDL for Table W_PRODUCT_HIERARCHY_G
--------------------------------------------------------

  CREATE TABLE "DW"."W_PRODUCT_HIERARCHY_G" 
   (	"ROW_WID" NUMBER, 
	"HIERARCHY_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"LEVEL1_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEVEL2_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEVEL3_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LEVEL4_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EFF_FROM_DT" DATE, 
	"EFF_TO_DT" DATE, 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"CREATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANGED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_PRODUCT_HIERARCHY_G" TO "ODS";
  GRANT READ ON "DW"."W_PRODUCT_HIERARCHY_G" TO "ODS";
  GRANT SELECT ON "DW"."W_PRODUCT_HIERARCHY_G" TO "DW_RO";
  GRANT READ ON "DW"."W_PRODUCT_HIERARCHY_G" TO "DW_RO";
