--------------------------------------------------------
--  DDL for Table W_PROPERTY_OPEX_LKP
--------------------------------------------------------

  CREATE TABLE "DW"."W_PROPERTY_OPEX_LKP" 
   (	"ROW_WID" NUMBER, 
	"EFF_FROM_DT" DATE, 
	"EFF_TO_DT" DATE, 
	"PROPERTY_CODE" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"ADDRESS1" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"OPEX_PER_KW" NUMBER, 
	"OPEX_LESS_UTILITIES_PER_KW" NUMBER, 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"CREATED_BY" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANGED_BY" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_PROPERTY_OPEX_LKP" TO "ODS";
  GRANT SELECT ON "DW"."W_PROPERTY_OPEX_LKP" TO "DW_RO";
