--------------------------------------------------------
--  DDL for Table W_PRODUCT_HIERARCHY_MAP_BKUP
--------------------------------------------------------

  CREATE TABLE "DW"."W_PRODUCT_HIERARCHY_MAP_BKUP" 
   (	"DATASOURCE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRODUCT_SRC_KEY" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_SRC_CODE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRODUCT_SRC_DESC" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_TYPE_GROUP" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"L4_PRODUCT_TYPE" NVARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"PRODUCT_HIER_WID" NUMBER, 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"CREATED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANGED_BY" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"PRODUCT_HIER2_WID" NUMBER, 
	"PRODUCT_HIER3_WID" NUMBER, 
	"ROW_WID" NUMBER, 
	"CURRENT_FLG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"EFF_FROM_DT" DATE, 
	"EFF_TO_DT" DATE, 
	"SFDC_PRODUCT_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INCLUDE_EXCLUDE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SQFT" NUMBER, 
	"QUANTITY_IS_SQFT" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"INCLUDE_IN_LA" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INCLUDE_IN_OA" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"ASSET_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
