--------------------------------------------------------
--  DDL for Table W_SUITE_METRICS_F
--------------------------------------------------------

  CREATE TABLE "DW"."W_SUITE_METRICS_F" 
   (	"PROPERTY_WID" NUMBER(38,0), 
	"SUITE" NVARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"SUITE_SRC_KEY" NVARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"SUITE_SQ_FT" NUMBER(21,6), 
	"SUITE_KW" NUMBER(21,6), 
	"LOAD_FACTOR" NUMBER, 
	"SNAPSHOT_DATE" DATE, 
	"CREATED_ON_DT" DATE, 
	"CHANGED_ON_DT" DATE, 
	"ETL_UPDATE_DT" DATE, 
	"ETL_INSERT_DT" DATE, 
	"ETL_PROC_WID" NUMBER, 
	"DATASOURCE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SNAPSHOT_PERIOD" NVARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"SELLABLE_SQ_FT" NUMBER(22,7), 
	"COLO_SQ_FT" NUMBER(22,7), 
	"SUITE_SRC" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "DW"."W_SUITE_METRICS_F" TO "ODS";
  GRANT READ ON "DW"."W_SUITE_METRICS_F" TO "ODS";
  GRANT SELECT ON "DW"."W_SUITE_METRICS_F" TO "DW_RO";
  GRANT READ ON "DW"."W_SUITE_METRICS_F" TO "DW_RO";
