--------------------------------------------------------
--  DDL for Sequence W_GL_ACCOUNT_HIER_DHL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_GL_ACCOUNT_HIER_DHL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 151011 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_HIER_DHL_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_HIER_DHL_SEQ" TO "DW_RO";
