--------------------------------------------------------
--  DDL for Sequence W_OPPORUNITY_F_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_OPPORUNITY_F_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_OPPORUNITY_F_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_OPPORUNITY_F_SEQ" TO "DW_RO";
