--------------------------------------------------------
--  DDL for Sequence W_PROPERTY_D_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_PROPERTY_D_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 442141399 CACHE 1000 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_PROPERTY_D_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_PROPERTY_D_SEQ" TO "DW_RO";
