--------------------------------------------------------
--  DDL for Sequence W_UNIT_HIER_MAP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_UNIT_HIER_MAP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_UNIT_HIER_MAP_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_UNIT_HIER_MAP_SEQ" TO "DW_RO";
