--------------------------------------------------------
--  DDL for Procedure HISTORY_LOAD_DEFAULT_DIM_RECORDS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DW"."HISTORY_LOAD_DEFAULT_DIM_RECORDS" 
as

begin




DELETE FROM W_CURRENCY_D WHERE ROW_WID = -1;

commit;

delete from dw.w_currency_d where iso_code = 'Functional';

commit;

INSERT INTO W_CURRENCY_D (ROW_WID,ISO_CODE,CURRENCY_NAME,CURRENCY_SRC_KEY,CURRENCY_SYMBOL,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT -1 as ROW_WID
, '(Unknown)' as ISO_CODE
, '(Unknown)' as CURRENCY_NAME
,  null as CURRENCY_SRC_KEY
, '(Unknown)' as CURRENCY_SYMBOL
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE FROM DUAL ; 

COMMIT;

INSERT INTO W_CURRENCY_D (ROW_WID,ISO_CODE,CURRENCY_NAME,CURRENCY_SRC_KEY,CURRENCY_SYMBOL,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT w_currency_d_seq.nextval as ROW_WID
, 'Functional' as ISO_CODE
, 'Functional' as CURRENCY_NAME
, '0' as CURRENCY_SRC_KEY
, null as CURRENCY_SYMBOL
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE FROM DUAL ; 

COMMIT;


DELETE FROM W_CUSTOMER_D WHERE ROW_WID = -1;

INSERT INTO W_CUSTOMER_D (ROW_WID,MARKET_SEGMENT1,MARKET_SEGMENT2,MARKET_SEGMENT3,L1_GLOBAL_ULTIMATE_CUSTOMER_SRC_KEY,L1_GLOBAL_ULTIMATE_CUSTOMER_NAME,L2_PARENT_CUSTOMER_SRC_KEY,L2_PARENT_CUSTOMER_CODE,L2_PARENT_CUSTOMER_NAME,L3_CUSTOMER_SRC_KEY,L3_CUSTOMER_CODE,L3_CUSTOMER_NAME,L4_LEGAL_ENTITY_SRC_KEY,L4_LEGAL_ENTITY_CODE,L4_LEGAL_ENTITY_NAME,DIVERSITY,DIVERSITY_CATEGORY,DIVERSITY_SUBCATEGORY,IS_GLOBAL_ULTIMATE,COMPANY_OWNERSHIP_TYPE_NAME,ACCOUNT_OWNER,SALES_SECTOR,ACTIVE_FLAG,ACCOUNT_REFERENCE_NUMBER,ACCOUNT_REVENUE_RANGE,CUSTOMER_SUCCESS_DIRECTOR,CUSTOMER_SUCCESS_MANAGER,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT -1 as ROW_WID
, '(Not Assigned)' as MARKET_SEGMENT1
, '(Not Assigned)' as MARKET_SEGMENT2
, '(Not Assigned)' as MARKET_SEGMENT3
, '(Not Assigned)' as L1_GLOBAL_ULTIMATE_CUSTOMER_SRC_KEY
, '(Not Assigned)' as L1_GLOBAL_ULTIMATE_CUSTOMER_NAME
, '(Not Assigned)' as L2_PARENT_CUSTOMER_SRC_KEY
, '(Not Assigned)' as L2_PARENT_CUSTOMER_CODE
, '(Not Assigned)' as L2_PARENT_CUSTOMER_NAME
, '(Not Assigned)' as L3_CUSTOMER_SRC_KEY
, '(Not Assigned)' as L3_CUSTOMER_CODE
, '(Not Assigned)' as L3_CUSTOMER_NAME
, '(Not Assigned)' as L4_LEGAL_ENTITY_SRC_KEY
, '(Not Assigned)' as L4_LEGAL_ENTITY_CODE
, '(Not Assigned)' as L4_LEGAL_ENTITY_NAME
, '(Not Assigned)' as DIVERSITY
, '(Not Assigned)' as DIVERSITY_CATEGORY
, '(Not Assigned)' as DIVERSITY_SUBCATEGORY
, -1 as IS_GLOBAL_ULTIMATE
, '(Not Assigned)' as COMPANY_OWNERSHIP_TYPE_NAME
, '(Not Assigned)' as ACCOUNT_OWNER
, '(Not Assigned)' as SALES_SECTOR
, '(Not Assigned)' as ACTIVE_FLAG
, '(Not Assigned)' as ACCOUNT_REFERENCE_NUMBER
, '(Not Assigned)' as ACCOUNT_REVENUE_RANGE
, '(Not Assigned)' as CUSTOMER_SUCCESS_DIRECTOR
, '(Not Assigned)' as CUSTOMER_SUCCESS_MANAGER
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
 FROM DUAL ; 

COMMIT;


DELETE FROM W_GL_ACCOUNT_D WHERE ROW_WID = -1;

INSERT INTO W_GL_ACCOUNT_D (ROW_WID,ACCOUNT_SRC_KEY,ACCOUNT_NAME,ACCOUNT_CODE,ACCOUNT_ORDER,ACCOUNT_TYPE,SIGN_FLAG,INCLUDE_IN_ACCOUNT_TREE,REPORT_TYPE,ACCOUNT_GROUPING,CAPITAL_EXPENDITURE_SUB_ACCOUNT,CATEGORY,COMP_NON_COMP_HEADER,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT -1 as ROW_WID
, -1 as ACCOUNT_SRC_KEY
, '(Unknown)' as ACCOUNT_NAME
, '(Unknown)' as ACCOUNT_CODE
, -1 as ACCOUNT_ORDER
, '(Unknown)' as ACCOUNT_TYPE
, -1 as SIGN_FLAG
, '(Unknown)' as INCLUDE_IN_ACCOUNT_TREE
, '(Unknown)' as REPORT_TYPE
, '(Unknown)' as ACCOUNT_GROUPING
, '(Unknown)' as CAPITAL_EXPENDITURE_SUB_ACCOUNT
, '(Unknown)' as CATEGORY
, '(Unknown)' as COMP_NON_COMP_HEADER
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE FROM DUAL ; 

COMMIT;


DELETE FROM W_GL_BOOK_D WHERE ROW_WID = -1;

INSERT INTO W_GL_BOOK_D (ROW_WID,BOOK_SRC_KEY,BOOK_NAME,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT -1 as ROW_WID
, null as BOOK_SRC_KEY
, '(Unknown)' as BOOK_NAME
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE FROM DUAL ; 

COMMIT;


DELETE FROM W_GL_BOOK_LIST_D WHERE ROW_WID = -1;

INSERT INTO W_GL_BOOK_LIST_D (ROW_WID,BOOK_LIST_SRC_KEY,BOOK_LIST_NAME,BOOK_LIST_CODE,TYPE,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,BOOK_WID) 
SELECT -1 as ROW_WID
, null as BOOK_LIST_SRC_KEY
, '(Unknown)' as BOOK_LIST_NAME
, '(Unknown)' as BOOK_LIST_CODE
, '(Unknown)' as TYPE
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, -1 as BOOK_WID FROM DUAL ; 

COMMIT;


DELETE FROM W_LEASE_ACTIVITY_D WHERE ROW_WID = -1;

INSERT INTO W_LEASE_ACTIVITY_D (ROW_WID,LEASE_ACTIVITY_SRC_KEY,SNAPSHOT_PERIOD,SNAPSHOT_DATE,CONTRACT_NUMBER,LEASE_REPORTING_TYPE,TRANSACTION_TYPE,LEASE_TYPE,ACTIVITY_STATUS,LEASE_DESCRIPTION,LEASE_COMMENTS,REPORT_DATE,START_DATE,END_DATE,SIGN_DATE,START_DATE_WID,END_DATE_WID,SIGN_DATE_WID,LEASE_COMMENCEMENT_DATE,ORIGINAL_TERM_EXPIRATION_DATE,EXPIRATION_DATE,CONTRACTUAL_START_DATE,SUITES,RENEWAL_TYPE,CONTRACTUAL_RENT_START_DATE,RENT_START_DATE,ORIGINAL_TERM_END_DATE,REPORTED_FLAG,RENT_TREND_EXCLUDED_FLAG,NON_LEASE_DEAL,COMMENCEMENT_DATE_STATUS,RETENTION_TYPE,GENERATION,CASH__RENT__STABILIZES,RELEASE_FLAG,PUBLISHED_FLAG,PRODUCT_TYPE,CROSS_CONNECT_TYPE,BUSINESS_UNIT,TELX_CASE_NUMBER,LEASE_CURRENCY_CODE,LEASE_EXCHANGE_RATE,SIGN_PERIOD,REPORT_PERIOD,COMMENCEMENT_PERIOD,SIGN_YEAR,REPORT_YEAR,COMMENCEMENT_YEAR,REDUNDANCY,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,SOURCE,ORDER_LINE_NUMBER,PUBLISHED_LEASE_IDENTIFIER,CUSTOMER_TYPE,YARDI_TCODE) 
SELECT -1 as ROW_WID
, null as LEASE_ACTIVITY_SRC_KEY
, null as SNAPSHOT_PERIOD
, null as SNAPSHOT_DATE
, '(Unknown)' as CONTRACT_NUMBER
, '(Unknown)' as LEASE_REPORTING_TYPE
, '(Unknown)' as TRANSACTION_TYPE
, '(Unknown)' as LEASE_TYPE
, '(Unknown)' as ACTIVITY_STATUS
, '(Unknown)' as LEASE_DESCRIPTION
, '(Unknown)' as LEASE_COMMENTS
, null as REPORT_DATE
, null as START_DATE
, null as END_DATE
, null as SIGN_DATE
, -1 as START_DATE_WID
, -1 as END_DATE_WID
, -1 as SIGN_DATE_WID
, null as LEASE_COMMENCEMENT_DATE
, null as ORIGINAL_TERM_EXPIRATION_DATE
, null as EXPIRATION_DATE
, null as CONTRACTUAL_START_DATE
, '(Unknown)' as SUITES
, '(Unknown)' as RENEWAL_TYPE
, null as CONTRACTUAL_RENT_START_DATE
, null as RENT_START_DATE
, null as ORIGINAL_TERM_END_DATE
, '(Unknown)' as REPORTED_FLAG
, '(Unknown)' as RENT_TREND_EXCLUDED_FLAG
, '(Unknown)' as NON_LEASE_DEAL
, '(Unknown)' as COMMENCEMENT_DATE_STATUS
, '(Unknown)' as RETENTION_TYPE
, '(Unknown)' as GENERATION
, -1 as CASH__RENT__STABILIZES
, '(Unknown)' as RELEASE_FLAG
, '(Unknown)' as PUBLISHED_FLAG
, '(Unknown)' as PRODUCT_TYPE
, '(Unknown)' as CROSS_CONNECT_TYPE
, '(Unknown)' as BUSINESS_UNIT
, '(Unknown)' as TELX_CASE_NUMBER
, '(Unknown)' as LEASE_CURRENCY_CODE
, -1 as LEASE_EXCHANGE_RATE
, '(Unknown)' as SIGN_PERIOD
, '(Unknown)' as REPORT_PERIOD
, '(Unknown)' as COMMENCEMENT_PERIOD
, '(Unknown)' as SIGN_YEAR
, '(Unknown)' as REPORT_YEAR
, '(Unknown)' as COMMENCEMENT_YEAR
, '(Unknown)' as REDUNDANCY
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, '(Unknown)' as SOURCE
, '(Unknown)' as ORDER_LINE_NUMBER
, '(Unknown)' as PUBLISHED_LEASE_IDENTIFIER
, '(Unknown)' as CUSTOMER_TYPE
, '(Unknown)' as YARDI_TCODE FROM DUAL ; 

COMMIT;


DELETE FROM W_LEASE_TERMS_D WHERE ROW_WID = -1;

INSERT INTO W_LEASE_TERMS_D (ROW_WID,REPORTED_DATE,LEASE_TYPE,LEASE_SIGN_DATE,LEASE_START_DATE,LEASE_END_DATE,AMENDMENT_TYPE,AMENDMENT_SIGN_DATE,AMENDMENT_START_DATE,AMENDMENT_END_DATE,AMENDMENT_EXPIRE_DATE,AMENDMENT_EXPIRE_REPORTED_DATE,MTM_FLAG,EARLY_TERMINATION_OPTION_DATE,AMENDMENT_ORIGINAL_START_DATE,LOCKED_FLAG,LEASE_NUMBER,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,UNIT,LEASE_REMAINING_TERM,DATE_EXPIRATION_YEAR) 
SELECT -1 as ROW_WID
, null as REPORTED_DATE
, '(Not Assigned)' as LEASE_TYPE
, null as LEASE_SIGN_DATE
, null as LEASE_START_DATE
, null as LEASE_END_DATE
, '(Not Assigned)' as AMENDMENT_TYPE
, null as AMENDMENT_SIGN_DATE
, null as AMENDMENT_START_DATE
, null as AMENDMENT_END_DATE
, null as AMENDMENT_EXPIRE_DATE
, null as AMENDMENT_EXPIRE_REPORTED_DATE
, null as MTM_FLAG
, null as EARLY_TERMINATION_OPTION_DATE
, null as AMENDMENT_ORIGINAL_START_DATE
, '1' as LOCKED_FLAG
, '(Not Assigned)' as LEASE_NUMBER
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, -1 as UNIT
, -1 as LEASE_REMAINING_TERM
, -1 as DATE_EXPIRATION_YEAR FROM DUAL ; 

COMMIT;


DELETE FROM W_OPPORTUNITY_D WHERE ROW_WID = -1;

INSERT INTO W_OPPORTUNITY_D (ROW_WID,OPPORTUNITY_SRC_KEY,OPPORTUNITY_NAME,OPPORTUNITY_OWNER,OPPORTUNITY_TYPE,STAGE,TRANSACTION_TYPE,COMMENTS,INVOICING_REMARKS,FORECAST_CATEGORY,PRIMARY_WIN_LOSS_REASON,SECONDARY_WIN_LOSS_REASON,OPPORTUNITY_STATUS,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,OPPORTUNITY_DESCRIPTION,PROBABILITY) 
SELECT -1 as ROW_WID
, null as OPPORTUNITY_SRC_KEY
, '(Unknown)' as OPPORTUNITY_NAME
, '(Unknown)' as OPPORTUNITY_OWNER
, '(Unknown)' as OPPORTUNITY_TYPE
, '(Unknown)' as STAGE
, '(Unknown)' as TRANSACTION_TYPE
, '(Unknown)' as COMMENTS
, '(Unknown)' as INVOICING_REMARKS
, '(Unknown)' as FORECAST_CATEGORY
, '(Unknown)' as PRIMARY_WIN_LOSS_REASON
, '(Unknown)' as SECONDARY_WIN_LOSS_REASON
, '(Unknown)' as OPPORTUNITY_STATUS
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, null as OPPORTUNITY_DESCRIPTION
, -1 as PROBABILITY FROM DUAL ; 

COMMIT;


DELETE FROM W_PRODUCT_D WHERE ROW_WID = -1;

INSERT INTO W_PRODUCT_D (ROW_WID,INVENTORY_ITEM_ID,ORGANIZATION_ID,INTEGRATION_ID,ITEM_NUMBER,ITEM_DESCRIPTION,ORGANIZATION_CODE,PRODUCT_CATALOG_CATEGORY,TAX_CATALOG_CATEGORY,IL_TAX_CATEGORY,ITEM_TYPE,ITEM_CLASS,LIST_PRICE_PER_UNIT,BOM_ITEM_TYPE,PRIMARY_UOM_CODE,INVOICEABLE_ITEM_FLAG,INVENTORY_ASSET_FLAG,PURCHASING_ITEM_FLAG,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE) 
SELECT -1 as ROW_WID
, -1 as INVENTORY_ITEM_ID
, -1 as ORGANIZATION_ID
, '(Unknown)' as INTEGRATION_ID
, '(Unknown)' as ITEM_NUMBER
, '(Unknown)' as ITEM_DESCRIPTION
, '(Unknown)' as ORGANIZATION_CODE
, '(Unknown)' as PRODUCT_CATALOG_CATEGORY
, '(Unknown)' as TAX_CATALOG_CATEGORY
, '(Unknown)' as IL_TAX_CATEGORY
, '(Unknown)' as ITEM_TYPE
, '(Unknown)' as ITEM_CLASS
, -1 as LIST_PRICE_PER_UNIT
, -1 as BOM_ITEM_TYPE
, null as PRIMARY_UOM_CODE
, null as INVOICEABLE_ITEM_FLAG
, null as INVENTORY_ASSET_FLAG
, null as PURCHASING_ITEM_FLAG
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE FROM DUAL ; 

COMMIT;


DELETE FROM W_PROPERTY_D WHERE ROW_WID = -1;

INSERT INTO W_PROPERTY_D (ROW_WID,PROPERTY_SRC_KEY,LIVE_FLAG,LEAF_LEVEL,SUITE,SUITE_TYPE,BUILDING,FLOOR,FLOOR_SRC_KEY,SUITE_SRC_KEY,BUILDING_SRC_KEY,PROPERTY_TYPE,PROPERTY_CODE,PROPERTY_NAME,ADDRESS1,ADDRESS2,CITY,STATE,COUNTRY,ZIP_POSTAL_CODE,ACQUIRED_DATE,LEGAL_ENTITY,LONGITUDE,LATITUDE,SAME_STORE,DOMESTIC_INTRL,STABILIZATION_DATE,STABILIZED_CURRENT_YEAR,STABILIZED_NEXT_YEAR,DISPOSITION_DATE,GLOBAL_MARKET,MARKET,REGION,OWNERSHIP_TYPE,LEASED_OWNED,SOURCE_CURRENCY_PROPERTY,HRIS_DIVISION,ELT,DIVISION,ENTITY_TYPE,COUNTRY_CODE,OWNERSHIP_PERCENT,PORTFOLIO_OWNERSHIP_PERCENTAGE,LINE_OF_BUSINESS,PROPERTY_MANAGER,DATA_CENTER_MANAGER,EXTERNALLY_REPORTED,REGIONAL_MANAGER,ENTITY_PARENT,CAMPUS,DIRECTOR,REAL_ESTATE_MANAGER,ASSISTANT_REM,PROPERTY_ASSISTANT,SITE_CODE,FORMALLY_KNOWN_AS_SITE_CODE,ASSET_MANAGER,SAP_WAREHOUSE_CODE,GEOGRAPHIC_DIVISION,LEGAL_ENTITY_NAME,REPORTED_REGION,REPORTED_MARKET,LOCKED,LOCKED_TIMESTAMP,SNAPSHOT_DATE,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,UNIT_TYPE_SRC_KEY,UNIT_SRC_KEY,UNIT_TYPE,UNIT,UNIT_DESC,UNIT_STATUS,MASTER_SITE_CODE,SNAPSHOT_PERIOD) 
SELECT -1 as ROW_WID
, 0 as PROPERTY_SRC_KEY
, 1 as LIVE_FLAG
, '(Inactive)' as LEAF_LEVEL
, '(Inactive)' as SUITE
, '(Inactive)' as SUITE_TYPE
, '(Inactive)' as BUILDING
, '(Inactive)' as FLOOR
, 0 as FLOOR_SRC_KEY
, 0 as SUITE_SRC_KEY
, 0 as BUILDING_SRC_KEY
, '(Inactive)' as PROPERTY_TYPE
, '(Unk)' as PROPERTY_CODE
, '(Inactive)' as PROPERTY_NAME
, '(Inactive)' as ADDRESS1
, '(Inactive)' as ADDRESS2
, '(Inactive)' as CITY
, '(Inactive)' as STATE
, '(Inactive)' as COUNTRY
, '(Inactive)' as ZIP_POSTAL_CODE
, null as ACQUIRED_DATE
, '(Inactive)' as LEGAL_ENTITY
, -1 as LONGITUDE
, -1 as LATITUDE
, '(Inactive)' as SAME_STORE
, '(Inactive)' as DOMESTIC_INTRL
, null as STABILIZATION_DATE
, '(Inactive)' as STABILIZED_CURRENT_YEAR
, '(Inactive)' as STABILIZED_NEXT_YEAR
, null as DISPOSITION_DATE
, '(Inactive)' as GLOBAL_MARKET
, '(Inactive)' as MARKET
, '(Inactive)' as REGION
, '(Inactive)' as OWNERSHIP_TYPE
, '(Inactive)' as LEASED_OWNED
, '(Inactive)' as SOURCE_CURRENCY_PROPERTY
, '(Inactive)' as HRIS_DIVISION
, '(Inactive)' as ELT
, '(Inactive)' as DIVISION
, '(Inactive)' as ENTITY_TYPE
, '(Inactive)' as COUNTRY_CODE
, '(Inactive)' as OWNERSHIP_PERCENT
, -1 as PORTFOLIO_OWNERSHIP_PERCENTAGE
, '(Inactive)' as LINE_OF_BUSINESS
, '(Inactive)' as PROPERTY_MANAGER
, '(Inactive)' as DATA_CENTER_MANAGER
, '(Inactive)' as EXTERNALLY_REPORTED
, '(Inactive)' as REGIONAL_MANAGER
, '(Inactive)' as ENTITY_PARENT
, '(Inactive)' as CAMPUS
, '(Inactive)' as DIRECTOR
, '(Inactive)' as REAL_ESTATE_MANAGER
, '(Inactive)' as ASSISTANT_REM
, '(Inactive)' as PROPERTY_ASSISTANT
, '(Inactive)' as SITE_CODE
, '(Inactive)' as FORMALLY_KNOWN_AS_SITE_CODE
, '(Inactive)' as ASSET_MANAGER
, '(Inactive)' as SAP_WAREHOUSE_CODE
, '(Inactive)' as GEOGRAPHIC_DIVISION
, '(Inactive)' as LEGAL_ENTITY_NAME
, '(Inactive)' as REPORTED_REGION
, '(Inactive)' as REPORTED_MARKET
, null as LOCKED
, null as LOCKED_TIMESTAMP
, null as SNAPSHOT_DATE
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, 0 as UNIT_TYPE_SRC_KEY
, 0 as UNIT_SRC_KEY
, '(Inactive)' as UNIT_TYPE
, '(Inactive)' as UNIT
, '(Inactive)' as UNIT_DESC
, '(Inactive)' as UNIT_STATUS
, '(Inactive)' as MASTER_SITE_CODE
, null as SNAPSHOT_PERIOD FROM DUAL ; 

COMMIT;


DELETE FROM W_PROPERTY_LIST_D WHERE ROW_WID = -1;

INSERT INTO W_PROPERTY_LIST_D (ROW_WID,PROPERTY_LIST_SRC_KEY,PROPERTY_LIST_CODE,PROPERTY_LIST_NAME,PROPERTY_CODE,CREATED_ON_DT,CHANGED_ON_DT,ETL_UPDATE_DT,ETL_INSERT_DT,ETL_PROC_WID,DATASOURCE,PROPERTY_SRC_KEY) 
SELECT -1 as ROW_WID
, 0 as PROPERTY_LIST_SRC_KEY
, '(Unk)' as PROPERTY_LIST_CODE
, '(Inactive)' as PROPERTY_LIST_NAME
, '(Unk)' as PROPERTY_CODE
, sysdate as CREATED_ON_DT
, sysdate as CHANGED_ON_DT
, sysdate as ETL_UPDATE_DT
, sysdate as ETL_INSERT_DT
, -1 as ETL_PROC_WID
, 'HISTORY LOAD' as DATASOURCE
, 0 as PROPERTY_SRC_KEY FROM DUAL ; 

COMMIT;




end
;

/

  GRANT EXECUTE ON "DW"."HISTORY_LOAD_DEFAULT_DIM_RECORDS" TO "SVC_ODI";
  GRANT DEBUG ON "DW"."HISTORY_LOAD_DEFAULT_DIM_RECORDS" TO "DW_RO";
