--------------------------------------------------------
--  DDL for Index SYS_AI_4m8jkbg4wy1y1
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_4m8jkbg4wy1y1" ON "DW"."W_PROPERTY_D" ("FORMALLY_KNOWN_AS_SITE_CODE") AUTO 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
