--------------------------------------------------------
--  DDL for Index SYS_AI_2pg2syy1njqky
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_2pg2syy1njqky" ON "DW"."W_PROPERTY_D" ("PROPERTY_CODE", "DATASOURCE", "SNAPSHOT_DATE", "SUITE", "BUILDING") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
