--------------------------------------------------------
--  DDL for Index SYS_AI_0hr3ad9u6s420
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_0hr3ad9u6s420" ON "DW"."W_PROPERTY_D" ("LOCKED", "LIVE_FLAG") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
