--------------------------------------------------------
--  DDL for Index SYS_AI_cr6cu8d23xpuq
--------------------------------------------------------

  CREATE INDEX "DW"."SYS_AI_cr6cu8d23xpuq" ON "DW"."W_PROPERTY_D" ("LEAF_LEVEL", "SNAPSHOT_PERIOD", "PROPERTY_CODE", "UNIT") AUTO 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 INVISIBLE COMPUTE STATISTICS COMPRESS ADVANCED LOW 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ;
