--------------------------------------------------------
--  DDL for Sequence W_GL_ACCOUNT_DH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_GL_ACCOUNT_DH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 154787 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_DH_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_GL_ACCOUNT_DH_SEQ" TO "DW_RO";
