--------------------------------------------------------
--  DDL for Sequence W_LEASE_ACTIVITY_D_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DW"."W_LEASE_ACTIVITY_D_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35197076 CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "DW"."W_LEASE_ACTIVITY_D_SEQ" TO "ODS";
  GRANT SELECT ON "DW"."W_LEASE_ACTIVITY_D_SEQ" TO "DW_RO";
