--------------------------------------------------------
--  DDL for View VW_ACCOUNT_RECEIVABLE_DETAILS_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_ACCOUNT_RECEIVABLE_DETAILS_F" ("PROPERTY_WID", "CUSTOMER_WID", "CURRENCY_WID", "INVOICE_NO", "TRANS_NUMBER", "CHARGE_CODE", "CHARGE_CODE_DESC", "CHARGE_CODE_TYPE", "CHARGE_NOTES", "CHARGE_UNIT", "CHARGE_REFERENCE", "CURRENCY_CODE", "EXCHANGE_RATE", "INVOICE_DATE_WID", "DUE_DATE_WID", "POST_MONTH_WID", "NET_RECEIVABLE", "TOTAL_AR", "AGES_0_TO_30_OWED", "AGES_31_TO_60_OWED", "AGES_61_TO_90_OWED", "AGES_91_TO_120_OWED", "OVER_120_OWED", "PRE_PAYMENTS", "UNAPPLIED_RECEIPTS", "DATE_OCCURRED_WID", "I_TYPE", "STATUS", "PULL_DATE_WID", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "LEGACY_SRC_KEY", "DATE_OCCURRED", "DUE_DATE", "SNAPSHOT_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        PROPERTY_WID,
        CUSTOMER_WID,
        CURRENCY_WID,
        INVOICE_NO,
        TRANS_NUMBER,
        CHARGE_CODE,
        CHARGE_CODE_DESC,
        CHARGE_CODE_TYPE,
        CHARGE_NOTES,
        CHARGE_UNIT,
        CHARGE_REFERENCE,
        CURRENCY_CODE,
        EXCHANGE_RATE,
        INVOICE_DATE_WID,
        DUE_DATE_WID,
        POST_MONTH_WID,
        NET_RECEIVABLE,
        TOTAL_AR,
        AGES_0_TO_30_OWED,
        AGES_31_TO_60_OWED,
        AGES_61_TO_90_OWED,
        AGES_91_TO_120_OWED,
        OVER_120_OWED,
        PRE_PAYMENTS,
        UNAPPLIED_RECEIPTS,
        DATE_OCCURRED_WID,
        I_TYPE,
        STATUS,
        PULL_DATE_WID,
        CREATED_ON_DT,
        CHANGED_ON_DT,
        ETL_UPDATE_DT,
        ETL_INSERT_DT,
        ETL_PROC_WID,
        DATASOURCE,
        LEGACY_SRC_KEY,
        TO_DATE(DATE_OCCURRED_WID,'YYYYMMDD') DATE_OCCURRED,
    TO_DATE(DUE_DATE_WID,'YYYYMMDD') DUE_DATE,
        TO_DATE ( PULL_DATE_WID,'YYYYMMDD' ) SNAPSHOT_DATE
    FROM
        w_account_receivable_details_f
;
  GRANT READ ON "DW"."VW_ACCOUNT_RECEIVABLE_DETAILS_F" TO "ODS";
  GRANT READ ON "DW"."VW_ACCOUNT_RECEIVABLE_DETAILS_F" TO "DW_RO";
