--------------------------------------------------------
--  DDL for View VW_ACCOUNT_RECEIVABLE_SUMMARY_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_ACCOUNT_RECEIVABLE_SUMMARY_F" ("PROPERTY_WID", "CUSTOMER_WID", "CURRENCY_WID", "CURRENCY_CODE", "EXCHANGE_RATE", "NET_RECEIVABLE", "TOTAL_AR", "AGES_0_TO_30_OWED", "AGES_0_TO_30_STATUS", "AGES_0_TO_30_COMMENT", "AGES_31_TO_60_OWED", "AGES_31_TO_60_STATUS", "AGES_31_TO_60_COMMENT", "AGES_61_TO_90_OWED", "AGES_61_TO_90_STATUS", "AGES_61_TO_90_COMMENT", "AGES_91_TO_120_OWED", "AGES_91_TO_120_STATUS", "AGES_91_TO_120_COMMENT", "OVER_120_OWED", "OVER_120_STATUS", "OVER_120_COMMENT", "PRE_PAYMENTS", "UNAPPLIED_RECEIPTS", "UNAPPLIED_RECEIPTS_STATUS", "UNAPPLIED_RECEIPTS_COMMENT", "GENERAL_COMMENT", "GENERAL_COMMENT_DATE_CREATED", "GENERAL_COMMENT_CREATED_BY", "PERIOD", "PULL_DATE_WID", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE", "LEGACY_SRC_KEY", "AGES_30_PLUS_TOTAL_AMOUNT", "AGES_60_PLUS_TOTAL_AMOUNT", "AGES_90_PLUS_TOTAL_AMOUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        PROPERTY_WID,
        CUSTOMER_WID,
        CURRENCY_WID,
        CURRENCY_CODE,
        nvl(EXCHANGE_RATE,1) EXCHANGE_RATE,
        nvl(NET_RECEIVABLE,0) NET_RECEIVABLE,
        nvl(TOTAL_AR,0) TOTAL_AR,
        nvl(AGES_0_TO_30_OWED,0) AGES_0_TO_30_OWED,
        AGES_0_TO_30_STATUS,
        AGES_0_TO_30_COMMENT,
        nvl(AGES_31_TO_60_OWED,0) AGES_31_TO_60_OWED,
        AGES_31_TO_60_STATUS,
        AGES_31_TO_60_COMMENT,
        nvl(AGES_61_TO_90_OWED,0) AGES_61_TO_90_OWED,
        AGES_61_TO_90_STATUS,
        AGES_61_TO_90_COMMENT,
        nvl(AGES_91_TO_120_OWED,0) AGES_91_TO_120_OWED,
        AGES_91_TO_120_STATUS,
        AGES_91_TO_120_COMMENT,
        nvl(OVER_120_OWED,0) OVER_120_OWED,
        OVER_120_STATUS,
        OVER_120_COMMENT,
        nvl(PRE_PAYMENTS,0) PRE_PAYMENTS,
        nvl(UNAPPLIED_RECEIPTS,0) UNAPPLIED_RECEIPTS,
        UNAPPLIED_RECEIPTS_STATUS,
        UNAPPLIED_RECEIPTS_COMMENT,
        GENERAL_COMMENT,
        GENERAL_COMMENT_DATE_CREATED,
        GENERAL_COMMENT_CREATED_BY,
        PERIOD,
        PULL_DATE_WID,
        CREATED_ON_DT,
        CHANGED_ON_DT,
        ETL_UPDATE_DT,
        ETL_INSERT_DT,
        ETL_PROC_WID,
        DATASOURCE,
        LEGACY_SRC_KEY,
        nvl(Ages_31_To_60_Owed , 0) +  nvl(Ages_61_To_90_Owed , 0) +  nvl(Ages_91_To_120_Owed, 0) +  nvl(Over_120_Owed , 0) AGES_30_plus_total_amount,
        nvl(Ages_61_To_90_Owed , 0) +  nvl(Ages_91_To_120_Owed, 0) +  nvl(Over_120_Owed , 0) AGES_60_plus_total_amount,
        nvl(Ages_91_To_120_Owed, 0) +  nvl(Over_120_Owed , 0) AGES_90_plus_total_amount
    FROM
        w_account_receivable_summary_f
;
  GRANT READ ON "DW"."VW_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "ODS";
  GRANT READ ON "DW"."VW_ACCOUNT_RECEIVABLE_SUMMARY_F" TO "DW_RO";
