--------------------------------------------------------
--  DDL for View VW_CONTACT_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_CONTACT_D" ("ROW_WID", "CUSTOMER_WID", "CUSTOMER_NAME", "CONTACT_FULL_NAME", "CONTACT_FIRST_NAME", "CONTACT_LAST_NAME", "CONTACT_SRC_KEY", "ADDRESS", "CITY", "COUNTRY", "STATE", "PRIMARY_EMAIL_ADDRESS", "PHONE_TYPE", "PRIMARY_PHONE_COUNTRY_CODE", "PRIMARY_PHONE_AREA_CODE", "PRIMARY_PHONE_NUMBER", "RELATIONSHIP_TYPE", "RELATIONSHIP_PRIMARY_FLAG", "STATUS", "RELATIONSHIP_STATUS", "USAGES", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "ROW_WID","CUSTOMER_WID","CUSTOMER_NAME","CONTACT_FULL_NAME","CONTACT_FIRST_NAME","CONTACT_LAST_NAME","CONTACT_SRC_KEY","ADDRESS","CITY","COUNTRY","STATE","PRIMARY_EMAIL_ADDRESS","PHONE_TYPE","PRIMARY_PHONE_COUNTRY_CODE","PRIMARY_PHONE_AREA_CODE","PRIMARY_PHONE_NUMBER","RELATIONSHIP_TYPE","RELATIONSHIP_PRIMARY_FLAG","STATUS","RELATIONSHIP_STATUS","USAGES","CREATED_ON_DT","CHANGED_ON_DT","ETL_UPDATE_DT","ETL_INSERT_DT","ETL_PROC_WID","DATASOURCE" from w_contact_d
;
  GRANT READ ON "DW"."VW_CONTACT_D" TO "ODS";
  GRANT READ ON "DW"."VW_CONTACT_D" TO "DW_RO";
