--------------------------------------------------------
--  DDL for View VW_CURRENCY_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_CURRENCY_D" ("ROW_WID", "ISO_CODE", "CURRENCY_NAME", "CURRENCY_SRC_KEY", "CURRENCY_SYMBOL", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "ROW_WID","ISO_CODE","CURRENCY_NAME","CURRENCY_SRC_KEY","CURRENCY_SYMBOL","CREATED_ON_DT","CHANGED_ON_DT","ETL_UPDATE_DT","ETL_INSERT_DT","ETL_PROC_WID","DATASOURCE" from w_currency_d
;
  GRANT READ ON "DW"."VW_CURRENCY_D" TO "ODS";
  GRANT READ ON "DW"."VW_CURRENCY_D" TO "DW_RO";
