--------------------------------------------------------
--  DDL for View VW_DATE_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_DATE_D" ("ROW_WID", "DATE_VALUE", "YEAR", "QUARTER", "MONTH", "QUARTER_NAME", "MONTH_NAME", "MONTH_ORDER", "DAY_OF_WEEK", "DAY_NAME", "DAY_AGO_DATE", "DAY_AGO_WID", "YEAR_AGO_DATE", "YEAR_AGO_WID", "QUARTER_AGO_DATE", "QUARTER_AGO_WID", "MONTH_AGO_DATE", "MONTH_AGO_WID", "WEEK_AGO_DATE", "WEEK_AGO_WID", "HOLIDAY_FLAG", "FIRST_DAY_MONTH_FLAG", "LAST_DAY_MONTH_FLAG", "FIRST_DAY_QUARTER_FLAG", "LAST_DAY_QUARTER_FLAG", "FIRST_DAY_YEAR_FLAG", "LAST_DAY_YEAR_FLAG", "ETL_UPDATE_DT", "ETL_INSERT_DT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        "ROW_WID",
        "DATE_VALUE",
        "YEAR",
        "QUARTER",
        "MONTH",
        "QUARTER_NAME",
        "MONTH_NAME",
        "MONTH_ORDER",
        "DAY_OF_WEEK",
        "DAY_NAME",
        "DAY_AGO_DATE",
        "DAY_AGO_WID",
        "YEAR_AGO_DATE",
        "YEAR_AGO_WID",
        "QUARTER_AGO_DATE",
        "QUARTER_AGO_WID",
        "MONTH_AGO_DATE",
        "MONTH_AGO_WID",
        "WEEK_AGO_DATE",
        "WEEK_AGO_WID",
        "HOLIDAY_FLAG",
        "FIRST_DAY_MONTH_FLAG",
        "LAST_DAY_MONTH_FLAG",
        "FIRST_DAY_QUARTER_FLAG",
        "LAST_DAY_QUARTER_FLAG",
        "FIRST_DAY_YEAR_FLAG",
        "LAST_DAY_YEAR_FLAG",
        "ETL_UPDATE_DT",
        "ETL_INSERT_DT"
    FROM
        w_date_d
;
  GRANT READ ON "DW"."VW_DATE_D" TO "ODS";
  GRANT READ ON "DW"."VW_DATE_D" TO "DW_RO";
