--------------------------------------------------------
--  DDL for View VW_GL_ACCOUNT_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_GL_ACCOUNT_D" ("ROW_WID", "ACCOUNT_SRC_KEY", "ACCOUNT_NAME", "ACCOUNT_CODE", "ACCOUNT_ORDER", "ACCOUNT_TYPE", "SIGN_FLAG", "INCLUDE_IN_ACCOUNT_TREE", "REPORT_TYPE", "ACCOUNT_GROUPING", "CAPITAL_EXPENDITURE_SUB_ACCOUNT", "CATEGORY", "COMP_NON_COMP_HEADER", "CREATED_ON_DT", "CHANGED_ON_DT", "ETL_UPDATE_DT", "ETL_INSERT_DT", "ETL_PROC_WID", "DATASOURCE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        "ROW_WID",
        "ACCOUNT_SRC_KEY",
        "ACCOUNT_NAME",
        "ACCOUNT_CODE",
        "ACCOUNT_ORDER",
        "ACCOUNT_TYPE",
        "SIGN_FLAG",
        "INCLUDE_IN_ACCOUNT_TREE",
        "REPORT_TYPE",
        "ACCOUNT_GROUPING",
        "CAPITAL_EXPENDITURE_SUB_ACCOUNT",
        "CATEGORY",
        "COMP_NON_COMP_HEADER",
        "CREATED_ON_DT",
        "CHANGED_ON_DT",
        "ETL_UPDATE_DT",
        "ETL_INSERT_DT",
        "ETL_PROC_WID",
        "DATASOURCE"
    FROM
        w_gl_account_d
;
  GRANT READ ON "DW"."VW_GL_ACCOUNT_D" TO "ODS";
  GRANT READ ON "DW"."VW_GL_ACCOUNT_D" TO "DW_RO";
