--------------------------------------------------------
--  DDL for View VW_ORDER_LINES_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_ORDER_LINES_F" ("CUSTOMER_WID", "ORDER_NUMBER", "SOURCE_ORDER_NUMBER", "CUSTOMER_PO_NUMBER", "HEADER_ID", "FULFILL_LINE_SHIP_SET_NAME", "FULFILL_LINE_CREATION_DATE", "HEADER_SOLD_TO_CUSTOMER_ID", "FULFILL_LINE_PARTIAL_SHIP_ALLOWED_FLAG", "LINE_CATEGORY_CODE", "HEADER_ORG_ID", "COVERAGE_FLINE_DETAILS_SERVICE_DURATION_PERIOD_CODE", "HEADER_LAST_UPDATE_DATE", "FULFILL_LINE_PROMISE_ARRIVAL_DATE", "HEADER_LEGAL_ENTITY_ID", "DOCUMENT_REFERENCES_DOC_SUBLINE_ID", "FULFILL_LINE_PARENT_STATUS_CODE", "HEADER_CREATION_DATE", "FULFILL_LINE_LAST_UPDATED_BY", "LINE_CREATION_DATE", "BILL_TO_CUSTOMER_ACCOUNT_LAST_UPDATE_DATE", "COVERAGE_FLINE_DETAILS_SOURCE_REVISION_NUMBER", "FULFILL_LINE_FULFILL_ORG_ID", "DOS_SUPPLY_TRACKING_LINE_SUPPLY_TYPE", "HEADER_CUSTOMER_PO_NUMBER", "FULFILL_LINE_PROMISE_SHIP_DATE", "DOCUMENT_REFERENCES_DOC_LINE_CONTEXT_ID", "LINE_SOURCE_LINE_ID", "DOCUMENT_REFERENCES_DOC_REF_TYPE", "HEADER_SOURCE_ORDER_SYSTEM", "HEADER_STATUS_CODE", "FULFILL_LINE_BILL_TO_SITE_USE_ID", "FULFILL_LINE_ACTION_TYPE_CODE", "COVERED_FLINE_DETAILS_SALES_PRODUCT_TYPE_CODE", "FULFILL_LINE_SHIP_MODE_OF_TRANSPORT", "FULFILL_LINE_CATEGORY_CODE", "COVERED_TRADING_PARTNER_ITEM_TP_ITEM_DESC", "HEADER_TRANSACTIONAL_CURRENCY_CODE", "FULFILL_LINE_FULFILL_FLAG", "FULFILL_LINE_FREIGHT_TERMS_CODE", "FULFILL_LINE_SHIPPED_QTY", "FULFILL_LINE_SERVICE_CANCEL_DATE", "HEADER_SOURCE_ORG_ID", "COVERED_FLINE_DETAILS_CONTRACT_START_DATE", "FULFILL_LINE_CONTRACT_START_DATE", "FULFILL_LINE_CUSTOMER_PO_NUMBER", "HEADER_LAST_UPDATED_BY", "COVERAGE_TRADING_PARTNER_ITEM_TP_ITEM_DESC", "COVERAGE_FLINE_DETAILS_SALES_PRODUCT_TYPE_CODE", "FULFILL_LINE_SOURCE_LINE_ID", "FULFILL_LINE_STATUS_CODE", "LINE_SOURCE_ORDER_NUMBER", "HEADER_ORDER_NUMBER", "DOC_REFERENCES_SUPPLY_DOC_USER_KEY", "COVERAGE_FLINE_DETAILS_FULFILL_LINE_NUMBER", "FULFILL_LINE_ITEM_TYPE_CODE", "LINE_CREATED_BY", "DOCUMENT_REFERENCES_DOC_LINE_ID", "LINE_ITEM_TYPE_CODE", "COVERAGE_FLINE_DETAILS_DOC_REF_TYPE", "FULFILL_LINE_SALES_PRODUCT_TYPE_CODE", "FULFILL_LINE_CONTRACT_END_DATE", "LINE_INVENTORY_ITEM_ID", "FULFILL_LINE_UNREFERENCED_RETURN_FLAG", "COVERED_FLINE_DETAILS_SOURCE_LINE_NUMBER", "HEADER_SALESPERSON_ID", "FULFILL_LINE_SCHEDULING_REASON_CODE", "DOCUMENT_REFERENCES_DOC_SUBLINE_ALT_USER_KEY", "FULFILL_LINE_LATEST_ACCEPTABLE_SHIP_DATE", "FULFILL_LINE_ASSET_GROUP_NUMBER", "FULFILL_LINE_SHIP_TO_SITE_USE_ID", "FULFILL_LINE_REQUEST_CANCEL_DATE", "FULFILL_LINE_SERVICE_DURATION", "LINE_OPEN_FLAG", "FULFILL_LINE_CUSTOMER_PO_LINE_NUMBER", "FULFILL_LINE_ID", "FULFILL_LINE_REQUEST_SHIP_DATE", "COVERAGE_FLINE_DETAILS_CONFIG_ITEM_REFERENCE", "DOCUMENT_REFERENCES_DOC_LINE_USER_KEY", "COVERED_FLINE_DETAILS_SERVICE_DURATION", "FULFILL_LINE_CANCELED_QTY", "FULFILL_LINE_UNIT_SELLING_PRICE", "DOC_REFERENCES_DROP_SHIP_DOC_LINE_USER_KEY", "TRADING_PARTNER_ITEM_TP_ITEM_DESC", "HEADER_SUBMITTED_FLAG", "FULFILL_LINE_PARENT_FULFILL_LINE_ID_PK", "FULFILL_LINE_PARENT_FULFILL_LINE_NUMBER", "FULFILL_LINE_PACKING_INSTRUCTIONS", "HEADER_ORDERED_DATE", "FULFILL_LINE_SCHEDULE_ARRIVAL_DATE", "COVERED_FLINE_DETAILS_CONFIG_ITEM_REFERENCE", "HEADER_SOLD_TO_PARTY_CONTACT_ID", "FULFILL_LINE_FULFILLMENT_DATE", "FULFILL_LINE_TAX_EXEMPT_FLAG", "FULFILL_LINE_TAX_EXEMPTION_REASON_CODE", "LINE_CANCELED_FLAG", "HEADER_SUBMITTED_BY", "COVERED_FLINE_DETAILS_SOURCE_REVISION_NUMBER", "COVERAGE_FLINE_DETAILS_CONTRACT_START_DATE", "TRADING_PARTNER_ITEM_TP_ITEM_NUMBER", "HEADER_SUBMITTED_DATE", "FULFILL_LINE_REQUEST_ARRIVAL_DATE", "FULFILL_LINE_ROOT_PARENT_STATUS_CODE", "CUSTOMER_ITEM_TP_ITEM_DESC", "HEADER_SOLD_TO_CONTACT_ID", "FULFILL_LINE_ASSET_TRACKED_FLAG", "LINE_FULFILLMENT_DATE", "COVERED_FLINE_DETAILS_FULFILL_LINE_NUMBER", "COVERED_TRADING_PARTNER_ITEM_TP_ITEM_NUMBER", "FULFILL_LINE_LINE_TYPE_CODE", "FULFILL_LINE_SOURCE_ORDER_NUMBER", "DOS_SUPPLY_BUY_ORDER_DTLS_PURCHASE_ORDER_LINE_NUMBER", "HEADER_CREATED_BY", "LINE_SOURCE_SCHEDULE_NUMBER", "FULFILL_LINE_RESERVED_QTY", "FULFILL_LINE_DEMAND_CLASS_CODE", "FULFILL_LINE_SHIP_TO_PARTY_SITE_ID", "FULFILL_LINE_CREATED_BY", "LINE_LINE_NUMBER", "COVERAGE_FLINE_DETAILS_SOURCE_ORDER_NUMBER", "FULFILL_LINE_ACTUAL_SHIP_DATE", "LINE_ORDERED_QTY", "HEADER_SALES_CHANNEL_CODE", "LINE_CANCELED_QTY", "COVERED_FLINE_DETAILS_SERVICE_DURATION_PERIOD_CODE", "FULFILL_LINE_RESERVABLE_FLAG", "FULFILL_LINE_CANCELED_FLAG", "FULFILL_LINE_PAYMENT_TERM_ID", "DOCUMENT_REFERENCES_DOC_CONTEXT_ID", "COVERED_FLINE_DETAILS_CONTRACT_END_DATE", "BILL_TO_CUSTOMER_ACCOUNT_ACCOUNT_ESTABLISHED_DATE", "COVERAGE_TRADING_PARTNER_ITEM_TP_ITEM_NUMBER", "FULFILL_LINE_UNIT_LIST_PRICE", "FULFILL_LINE_ORDERED_QTY", "FULFILL_LINE_SHIP_TO_PARTY_CONTACT_ID", "LINE_UNIT_SELLING_PRICE", "FULFILL_LINE_FULFILLMENT_SPLIT_REF_ID", "FULFILL_LINE_RETURN_REASON_CODE", "FULFILL_LINE_ON_HOLD", "FULFILL_LINE_ROOT_PARENT_FULFILL_LINE_NUMBER", "DOCUMENT_REFERENCES_DOC_ID", "COVERAGE_FLINE_DETAILS_SERVICE_DURATION", "HEADER_SOURCE_DOCUMENT_TYPE_CODE", "FULFILL_LINE_ORDERED_UOM", "LINE_DISPLAY_LINE_NUMBER", "HEADER_ORDER_TYPE_CODE", "HEADER_CHANGE_VERSION_NUMBER", "DOCUMENT_REFERENCES_DOC_SUBLINE_CONTEXT_ID", "FULFILL_LINE_SOURCE_ORDER_ID", "HEADER_ORIG_SYS_DOCUMENT_REF", "DOCUMENT_REFERENCES_DOC_SUBLINE_USER_KEY", "FULFILL_LINE_EARLIEST_ACCEPTABLE_SHIP_DATE", "FULFILL_LINE_TAX_CLASSIFICATION_CODE", "FULFILL_LINE_HEADER_ID", "FULFILL_LINE_SHIPPING_INSTRUCTIONS", "LINE_HEADER_ID", "FULFILL_LINE_SHIPPABLE_FLAG", "FULFILL_LINE_ESTIMATE_FULFILLMENT_COST", "FULFILL_LINE_LAST_UPDATE_DATE", "LINE_SHIPPED_QTY", "FULFILL_LINE_ITEM_SUB_TYPE_CODE", "FULFILL_LINE_ROOT_PARENT_FULFILL_LINE_ID_PK", "FULFILL_LINE_ACTUAL_COMPLETION_DATE", "COVERED_FLINE_DETAILS_SOURCE_SCHEDULE_NUMBER", "FULFILL_LINE_ROOT_PARENT_FULFILL_LINE_ID", "LINE_LAST_UPDATED_BY", "FULFILL_LINE_RMA_DELIVERED_QTY", "FULFILL_LINE_SCHEDULE_SHIP_DATE", "DOC_REFERENCES_DROP_SHIP_DOC_SUBLINE_USER_KEY", "LINE_UNIT_LIST_PRICE", "HEADER_CONVERSION_TYPE_CODE", "FULFILL_LINE_LINE_ID", "FULFILL_LINE_FULFILLED_QTY", "FULFILL_LINE_OPEN_FLAG", "FULFILL_LINE_INVENTORY_ITEM_ID", "DOCUMENT_REFERENCES_DOC_ALT_USER_KEY", "DOS_SUPPLY_BUY_ORDER_DTLS_PURCHASE_ORDER_NUMBER", "FULFILL_LINE_SUPPLIER_ID", "HEADER_SOLD_TO_PARTY_ID", "DOCUMENT_REFERENCES_DOC_LINE_ALT_USER_KEY", "LINE_LINE_ID", "COVERAGE_FLINE_DETAILS_SOURCE_LINE_NUMBER", "HEADER_CANCELED_FLAG", "LINE_LAST_UPDATE_DATE", "FULFILL_LINE_SHIP_CLASS_OF_SERVICE", "COVERED_FLINE_DETAILS_SOURCE_ORDER_NUMBER", "LINE_SCHEDULE_SHIP_DATE", "DOS_SUPPLY_BUY_ORDER_DTLS_PURCHASE_ORDER_SCHEDULE_NUMBER", "COVERED_FLINE_DETAILS_DOC_REF_TYPE", "FULFILL_LINE_FULFILL_LINE_NUMBER", "DOC_REFERENCES_DROPSHIP_DOC_USER_KEY", "LINE_ACTUAL_SHIP_DATE", "DOCUMENT_REFERENCES_DOC_USER_KEY", "HEADER_OPEN_FLAG", "COVERAGE_FLINE_DETAILS_SOURCE_SCHEDULE_NUMBER", "FULFILL_LINE_SHIP_TO_PARTY_ID", "FULFILL_LINE_EXEMPTION_CERTIFICATE_NUMBER", "FULFILL_LINE_LATEST_ACCEPTABLE_ARRIVAL_DATE", "FULFILL_LINE_SERVICE_DURATION_PERIOD_CODE", "HEADER_CONVERSION_RATE", "FULFILL_LINE_SOURCE_LINE_NUMBER", "LINE_ORDERED_UOM", "LINE_SOURCE_LINE_NUMBER", "HEADER_ON_HOLD", "LINE_SOURCE_ORDER_ID", "COVERAGE_FLINE_DETAILS_CONTRACT_END_DATE", "LINE_STATUS_CODE", "LINE_ON_HOLD", "STATUS_TRANSLATION_DISPLAY_NAME", "CONTEXT_CODE", "PROGRAM_NAME", "PROGRAM_APP_NAME", "SFDC_CASE_NUMBER", "SUBSCRIPTION_NUMBER", "SFDC_CASE_ID", "LINE_ID", "LINE_EXTENDED_AMOUNT", "CHARGE_SUBTYPE_CODE", "PRICE_PERIODICITY_CODE", "CAN_ADJUST_FLAG", "GSA_UNIT_PRICE", "LAST_UPDATE_DATE", "ORDER_CHARGE_ID", "SOURCE_CHARGE_ID", "CREATED_BY", "PRIMARY_FLAG", "PRICED_QUANTITY_UOM_CODE", "AVG_UNIT_SELLING_PRICE", "PARENT_ENTITY_CODE", "ROLLUP_FLAG", "PARENT_ENTITY_ID", "CHARGE_CURRENCY_CODE", "COBJECT_VERSION_NUMBER", "REFERENCE_ORDER_CHARGE_ID", "SEQUENCE_NUMBER", "CHARGE_DEFINITION_CODE", "CHARGE_APPLIES_TO", "PRICE_TYPE_CODE", "CHARGE_TYPE_CODE", "LAST_UPDATE_LOGIN", "CCREATION_DATE", "DELTA_TYPE", "MODIFIED_FLAG", "PRICED_QUANTITY", "CHEADER_HEADER_ID", "CUNIT_LIST_PRICE", "CLINE_LINE_ID", "CFULFILL_LINE_LINEID", "FCULFILL_LINE_LINETYPE_CODE", "CLINE_LINETYPE_CODE", "HEADER_CURRENCY_EXT_AMOUNT", "HEADER_CURR_DURATION_EXT_AMT", "CHARGE_CURRENCY_UNIT_PRICE", "HEADER_CURRENCY_UNIT_PRICE", "PRICE_ELEMENT_CODE", "MRC", "NRC") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT  nvl(w_customer_d.row_wid, - 1) customer_wid,
        fusion_doo_headers_all.ordernumber                                              order_number,
        fusion_doo_headers_all.sourceordernumber                                        source_order_number,
        fusion_doo_headers_all.customerponumber                                         customer_po_number,
        fusion_doo_headers_all.headerid                                                 header_id,
       -- fusion_ib_cse_assets_b.customerassetenddate                                     customer_asset_end_date,
        --fusion_ib_cse_assets_b.customerassetstartdate                                   customer_asset_start_date,
        fusion_doo_fulfill_lines_all.fulfilllineshipsetname                             fulfill_line_ship_set_name,
        fusion_doo_fulfill_lines_all.fulfilllinecreationdate                            fulfill_line_creation_date,
        fusion_doo_fulfill_lines_all.headersoldtocustomerid                             header_sold_to_customer_id,
        fusion_doo_fulfill_lines_all.fulfilllinepartialshipallowedflag                  fulfill_line_partial_ship_allowed_flag,
        fusion_doo_fulfill_lines_all.linecategorycode                                   line_category_code,
        fusion_doo_fulfill_lines_all.headerorgid                                        header_org_id,
        fusion_doo_fulfill_lines_all.coverageflinedetailsservicedurationperiodcode      coverage_fline_details_service_duration_period_code,
        fusion_doo_fulfill_lines_all.headerlastupdatedate                               header_last_update_date,
        fusion_doo_fulfill_lines_all.fulfilllinepromisearrivaldate                      fulfill_line_promise_arrival_date,
        fusion_doo_fulfill_lines_all.headerlegalentityid                                header_legal_entity_id,
        fusion_doo_fulfill_lines_all.documentreferencesdocsublineid                     document_references_doc_subline_id,
        fusion_doo_fulfill_lines_all.fulfilllineparentstatuscode                        fulfill_line_parent_status_code,
        fusion_doo_fulfill_lines_all.headercreationdate                                 header_creation_date,
        fusion_doo_fulfill_lines_all.fulfilllinelastupdatedby                           fulfill_line_last_updated_by,
        fusion_doo_fulfill_lines_all.linecreationdate                                   line_creation_date,
        fusion_doo_fulfill_lines_all.billtocustomeraccountlastupdatedate                bill_to_customer_account_last_update_date,
        fusion_doo_fulfill_lines_all.coverageflinedetailssourcerevisionnumber           coverage_fline_details_source_revision_number,
        fusion_doo_fulfill_lines_all.fulfilllinefulfillorgid                            fulfill_line_fulfill_org_id,
        fusion_doo_fulfill_lines_all.dossupplytrackinglinesupplytype                    dos_supply_tracking_line_supply_type,
        fusion_doo_fulfill_lines_all.headercustomerponumber                             header_customer_po_number,
        fusion_doo_fulfill_lines_all.fulfilllinepromiseshipdate                         fulfill_line_promise_ship_date,
        fusion_doo_fulfill_lines_all.documentreferencesdoclinecontextid                 document_references_doc_line_context_id,
        fusion_doo_fulfill_lines_all.linesourcelineid                                   line_source_line_id,
        fusion_doo_fulfill_lines_all.documentreferencesdocreftype                       document_references_doc_ref_type,
        fusion_doo_fulfill_lines_all.headersourceordersystem                            header_source_order_system,
        fusion_doo_fulfill_lines_all.headerstatuscode                                   header_status_code,
        fusion_doo_fulfill_lines_all.fulfilllinebilltositeuseid                         fulfill_line_bill_to_site_use_id,
        fusion_doo_fulfill_lines_all.fulfilllineactiontypecode                          fulfill_line_action_type_code,
        fusion_doo_fulfill_lines_all.coveredflinedetailssalesproducttypecode            covered_fline_details_sales_product_type_code,
        fusion_doo_fulfill_lines_all.fulfilllineshipmodeoftransport                     fulfill_line_ship_mode_of_transport,
        fusion_doo_fulfill_lines_all.fulfilllinecategorycode                            fulfill_line_category_code,
        fusion_doo_fulfill_lines_all.coveredtradingpartneritemtpitemdesc                covered_trading_partner_item_tp_item_desc,
        fusion_doo_fulfill_lines_all.headertransactionalcurrencycode                    header_transactional_currency_code,
        fusion_doo_fulfill_lines_all.fulfilllinefulfillflag                             fulfill_line_fulfill_flag,
        fusion_doo_fulfill_lines_all.fulfilllinefreighttermscode                        fulfill_line_freight_terms_code,
        fusion_doo_fulfill_lines_all.fulfilllineshippedqty                              fulfill_line_shipped_qty,
        fusion_doo_fulfill_lines_all.fulfilllineservicecanceldate                       fulfill_line_service_cancel_date,
        fusion_doo_fulfill_lines_all.headersourceorgid                                  header_source_org_id,
        fusion_doo_fulfill_lines_all.coveredflinedetailscontractstartdate               covered_fline_details_contract_start_date,
        fusion_doo_fulfill_lines_all.fulfilllinecontractstartdate                       fulfill_line_contract_start_date,
        fusion_doo_fulfill_lines_all.fulfilllinecustomerponumber                        fulfill_line_customer_po_number,
        fusion_doo_fulfill_lines_all.headerlastupdatedby                                header_last_updated_by,
        fusion_doo_fulfill_lines_all.coveragetradingpartneritemtpitemdesc               coverage_trading_partner_item_tp_item_desc,
        fusion_doo_fulfill_lines_all.coverageflinedetailssalesproducttypecode           coverage_fline_details_sales_product_type_code,
        fusion_doo_fulfill_lines_all.fulfilllinesourcelineid                            fulfill_line_source_line_id,
        fusion_doo_fulfill_lines_all.fulfilllinestatuscode                              fulfill_line_status_code,
        fusion_doo_fulfill_lines_all.linesourceordernumber                              line_source_order_number,
        fusion_doo_fulfill_lines_all.headerordernumber                                  header_order_number,
        fusion_doo_fulfill_lines_all.docreferencessupplydocuserkey                      doc_references_supply_doc_user_key,
        fusion_doo_fulfill_lines_all.coverageflinedetailsfulfilllinenumber              coverage_fline_details_fulfill_line_number,
        fusion_doo_fulfill_lines_all.fulfilllineitemtypecode                            fulfill_line_item_type_code,
        fusion_doo_fulfill_lines_all.linecreatedby                                      line_created_by,
        fusion_doo_fulfill_lines_all.documentreferencesdoclineid                        document_references_doc_line_id,
        fusion_doo_fulfill_lines_all.lineitemtypecode                                   line_item_type_code,
        fusion_doo_fulfill_lines_all.coverageflinedetailsdocreftype                     coverage_fline_details_doc_ref_type,
        fusion_doo_fulfill_lines_all.fulfilllinesalesproducttypecode                    fulfill_line_sales_product_type_code,
        fusion_doo_fulfill_lines_all.fulfilllinecontractenddate                         fulfill_line_contract_end_date,
        fusion_doo_fulfill_lines_all.lineinventoryitemid                                line_inventory_item_id,
        fusion_doo_fulfill_lines_all.fulfilllineunreferencedreturnflag                  fulfill_line_unreferenced_return_flag,
        fusion_doo_fulfill_lines_all.coveredflinedetailssourcelinenumber                covered_fline_details_source_line_number,
        fusion_doo_fulfill_lines_all.headersalespersonid                                header_salesperson_id,
        fusion_doo_fulfill_lines_all.fulfilllineschedulingreasoncode                    fulfill_line_scheduling_reason_code,
        fusion_doo_fulfill_lines_all.documentreferencesdocsublinealtuserkey             document_references_doc_subline_alt_user_key,
        fusion_doo_fulfill_lines_all.fulfilllinelatestacceptableshipdate                fulfill_line_latest_acceptable_ship_date,
        fusion_doo_fulfill_lines_all.fulfilllineassetgroupnumber                        fulfill_line_asset_group_number,
        fusion_doo_fulfill_lines_all.fulfilllineshiptositeuseid                         fulfill_line_ship_to_site_use_id,
        fusion_doo_fulfill_lines_all.fulfilllinerequestcanceldate                       fulfill_line_request_cancel_date,
        fusion_doo_fulfill_lines_all.fulfilllineserviceduration                         fulfill_line_service_duration,
        fusion_doo_fulfill_lines_all.lineopenflag                                       line_open_flag,
        fusion_doo_fulfill_lines_all.fulfilllinecustomerpolinenumber                    fulfill_line_customer_po_line_number,
        fusion_doo_fulfill_lines_all.fulfilllineid                                      fulfill_line_id,
        fusion_doo_fulfill_lines_all.fulfilllinerequestshipdate                         fulfill_line_request_ship_date,
        fusion_doo_fulfill_lines_all.coverageflinedetailsconfigitemreference            coverage_fline_details_config_item_reference,
        fusion_doo_fulfill_lines_all.documentreferencesdoclineuserkey                   document_references_doc_line_user_key,
        fusion_doo_fulfill_lines_all.coveredflinedetailsserviceduration                 covered_fline_details_service_duration,
        fusion_doo_fulfill_lines_all.fulfilllinecanceledqty                             fulfill_line_canceled_qty,
        fusion_doo_fulfill_lines_all.fulfilllineunitsellingprice                        fulfill_line_unit_selling_price,
        fusion_doo_fulfill_lines_all.docreferencesdropshipdoclineuserkey                doc_references_drop_ship_doc_line_user_key,
        fusion_doo_fulfill_lines_all.tradingpartneritemtpitemdesc                       trading_partner_item_tp_item_desc,
        fusion_doo_fulfill_lines_all.headersubmittedflag                                header_submitted_flag,
        fusion_doo_fulfill_lines_all.fulfilllineparentfulfilllineidpk                   fulfill_line_parent_fulfill_line_id_pk,
        fusion_doo_fulfill_lines_all.fulfilllineparentfulfilllinenumber                 fulfill_line_parent_fulfill_line_number,
        fusion_doo_fulfill_lines_all.fulfilllinepackinginstructions                     fulfill_line_packing_instructions,
        fusion_doo_fulfill_lines_all.headerordereddate                                  header_ordered_date,
        fusion_doo_fulfill_lines_all.fulfilllineschedulearrivaldate                     fulfill_line_schedule_arrival_date,
        fusion_doo_fulfill_lines_all.coveredflinedetailsconfigitemreference             covered_fline_details_config_item_reference,
        fusion_doo_fulfill_lines_all.headersoldtopartycontactid                         header_sold_to_party_contact_id,
        fusion_doo_fulfill_lines_all.fulfilllinefulfillmentdate                         fulfill_line_fulfillment_date,
        fusion_doo_fulfill_lines_all.fulfilllinetaxexemptflag                           fulfill_line_tax_exempt_flag,
        fusion_doo_fulfill_lines_all.fulfilllinetaxexemptionreasoncode                  fulfill_line_tax_exemption_reason_code,
        fusion_doo_fulfill_lines_all.linecanceledflag                                   line_canceled_flag,
        fusion_doo_fulfill_lines_all.headersubmittedby                                  header_submitted_by,
        fusion_doo_fulfill_lines_all.coveredflinedetailssourcerevisionnumber            covered_fline_details_source_revision_number,
        fusion_doo_fulfill_lines_all.coverageflinedetailscontractstartdate              coverage_fline_details_contract_start_date,
        fusion_doo_fulfill_lines_all.tradingpartneritemtpitemnumber                     trading_partner_item_tp_item_number,
        fusion_doo_fulfill_lines_all.headersubmitteddate                                header_submitted_date,
        fusion_doo_fulfill_lines_all.fulfilllinerequestarrivaldate                      fulfill_line_request_arrival_date,
        fusion_doo_fulfill_lines_all.fulfilllinerootparentstatuscode                    fulfill_line_root_parent_status_code,
        fusion_doo_fulfill_lines_all.customeritemtpitemdesc                             customer_item_tp_item_desc,
        fusion_doo_fulfill_lines_all.headersoldtocontactid                              header_sold_to_contact_id,
        fusion_doo_fulfill_lines_all.fulfilllineassettrackedflag                        fulfill_line_asset_tracked_flag,
        fusion_doo_fulfill_lines_all.linefulfillmentdate                                line_fulfillment_date,
        fusion_doo_fulfill_lines_all.coveredflinedetailsfulfilllinenumber               covered_fline_details_fulfill_line_number,
        fusion_doo_fulfill_lines_all.coveredtradingpartneritemtpitemnumber              covered_trading_partner_item_tp_item_number,
        fusion_doo_fulfill_lines_all.fulfilllinelinetypecode                            fulfill_line_line_type_code,
        fusion_doo_fulfill_lines_all.fulfilllinesourceordernumber                       fulfill_line_source_order_number,
        fusion_doo_fulfill_lines_all.dossupplybuyorderdtlspurchaseorderlinenumber       dos_supply_buy_order_dtls_purchase_order_line_number,
        fusion_doo_fulfill_lines_all.headercreatedby                                    header_created_by,
        fusion_doo_fulfill_lines_all.linesourceschedulenumber                           line_source_schedule_number,
        fusion_doo_fulfill_lines_all.fulfilllinereservedqty                             fulfill_line_reserved_qty,
        fusion_doo_fulfill_lines_all.fulfilllinedemandclasscode                         fulfill_line_demand_class_code,
        fusion_doo_fulfill_lines_all.fulfilllineshiptopartysiteid                       fulfill_line_ship_to_party_site_id,
        fusion_doo_fulfill_lines_all.fulfilllinecreatedby                               fulfill_line_created_by,
        fusion_doo_fulfill_lines_all.linelinenumber                                     line_line_number,
        fusion_doo_fulfill_lines_all.coverageflinedetailssourceordernumber              coverage_fline_details_source_order_number,
        fusion_doo_fulfill_lines_all.fulfilllineactualshipdate                          fulfill_line_actual_ship_date,
        fusion_doo_fulfill_lines_all.lineorderedqty                                     line_ordered_qty,
        fusion_doo_fulfill_lines_all.headersaleschannelcode                             header_sales_channel_code,
        fusion_doo_fulfill_lines_all.linecanceledqty                                    line_canceled_qty,
        fusion_doo_fulfill_lines_all.coveredflinedetailsservicedurationperiodcode       covered_fline_details_service_duration_period_code,
        fusion_doo_fulfill_lines_all.fulfilllinereservableflag                          fulfill_line_reservable_flag,
        fusion_doo_fulfill_lines_all.fulfilllinecanceledflag                            fulfill_line_canceled_flag,
        fusion_doo_fulfill_lines_all.fulfilllinepaymenttermid                           fulfill_line_payment_term_id,
        fusion_doo_fulfill_lines_all.documentreferencesdoccontextid                     document_references_doc_context_id,
        fusion_doo_fulfill_lines_all.coveredflinedetailscontractenddate                 covered_fline_details_contract_end_date,
        fusion_doo_fulfill_lines_all.billtocustomeraccountaccountestablisheddate        bill_to_customer_account_account_established_date,
        fusion_doo_fulfill_lines_all.coveragetradingpartneritemtpitemnumber             coverage_trading_partner_item_tp_item_number,
        fusion_doo_fulfill_lines_all.fulfilllineunitlistprice                           fulfill_line_unit_list_price,
        fusion_doo_fulfill_lines_all.fulfilllineorderedqty                              fulfill_line_ordered_qty,
        fusion_doo_fulfill_lines_all.fulfilllineshiptopartycontactid                    fulfill_line_ship_to_party_contact_id,
        fusion_doo_fulfill_lines_all.lineunitsellingprice                               line_unit_selling_price,
        fusion_doo_fulfill_lines_all.fulfilllinefulfillmentsplitrefid                   fulfill_line_fulfillment_split_ref_id,
        fusion_doo_fulfill_lines_all.fulfilllinereturnreasoncode                        fulfill_line_return_reason_code,
        fusion_doo_fulfill_lines_all.fulfilllineonhold                                  fulfill_line_on_hold,
        fusion_doo_fulfill_lines_all.fulfilllinerootparentfulfilllinenumber             fulfill_line_root_parent_fulfill_line_number,
        fusion_doo_fulfill_lines_all.documentreferencesdocid                            document_references_doc_id,
        fusion_doo_fulfill_lines_all.coverageflinedetailsserviceduration                coverage_fline_details_service_duration,
        fusion_doo_fulfill_lines_all.headersourcedocumenttypecode                       header_source_document_type_code,
        fusion_doo_fulfill_lines_all.fulfilllineordereduom                              fulfill_line_ordered_uom,
        fusion_doo_fulfill_lines_all.linedisplaylinenumber                              line_display_line_number,
        fusion_doo_fulfill_lines_all.headerordertypecode                                header_order_type_code,
        fusion_doo_fulfill_lines_all.headerchangeversionnumber                          header_change_version_number,
        fusion_doo_fulfill_lines_all.documentreferencesdocsublinecontextid              document_references_doc_subline_context_id,
        fusion_doo_fulfill_lines_all.fulfilllinesourceorderid                           fulfill_line_source_order_id,
        fusion_doo_fulfill_lines_all.headerorigsysdocumentref                           header_orig_sys_document_ref,
        fusion_doo_fulfill_lines_all.documentreferencesdocsublineuserkey                document_references_doc_subline_user_key,
        fusion_doo_fulfill_lines_all.fulfilllineearliestacceptableshipdate              fulfill_line_earliest_acceptable_ship_date,
        fusion_doo_fulfill_lines_all.fulfilllinetaxclassificationcode                   fulfill_line_tax_classification_code,
        fusion_doo_fulfill_lines_all.fulfilllineheaderid                                fulfill_line_header_id,
        fusion_doo_fulfill_lines_all.fulfilllineshippinginstructions                    fulfill_line_shipping_instructions,
        fusion_doo_fulfill_lines_all.lineheaderid                                       line_header_id,
        fusion_doo_fulfill_lines_all.fulfilllineshippableflag                           fulfill_line_shippable_flag,
        fusion_doo_fulfill_lines_all.fulfilllineestimatefulfillmentcost                 fulfill_line_estimate_fulfillment_cost,
        fusion_doo_fulfill_lines_all.fulfilllinelastupdatedate                          fulfill_line_last_update_date,
        fusion_doo_fulfill_lines_all.lineshippedqty                                     line_shipped_qty,
        fusion_doo_fulfill_lines_all.fulfilllineitemsubtypecode                         fulfill_line_item_sub_type_code,
        fusion_doo_fulfill_lines_all.fulfilllinerootparentfulfilllineidpk               fulfill_line_root_parent_fulfill_line_id_pk,
        fusion_doo_fulfill_lines_all.fulfilllineactualcompletiondate                    fulfill_line_actual_completion_date,
        fusion_doo_fulfill_lines_all.coveredflinedetailssourceschedulenumber            covered_fline_details_source_schedule_number,
        fusion_doo_fulfill_lines_all.fulfilllinerootparentfulfilllineid                 fulfill_line_root_parent_fulfill_line_id,
        fusion_doo_fulfill_lines_all.linelastupdatedby                                  line_last_updated_by,
        fusion_doo_fulfill_lines_all.fulfilllinermadeliveredqty                         fulfill_line_rma_delivered_qty,
        fusion_doo_fulfill_lines_all.fulfilllinescheduleshipdate                        fulfill_line_schedule_ship_date,
        fusion_doo_fulfill_lines_all.docreferencesdropshipdocsublineuserkey             doc_references_drop_ship_doc_subline_user_key,
        fusion_doo_fulfill_lines_all.lineunitlistprice                                  line_unit_list_price,
        fusion_doo_fulfill_lines_all.headerconversiontypecode                           header_conversion_type_code,
        fusion_doo_fulfill_lines_all.fulfilllinelineid                                  fulfill_line_line_id,
        fusion_doo_fulfill_lines_all.fulfilllinefulfilledqty                            fulfill_line_fulfilled_qty,
        fusion_doo_fulfill_lines_all.fulfilllineopenflag                                fulfill_line_open_flag,
        fusion_doo_fulfill_lines_all.fulfilllineinventoryitemid                         fulfill_line_inventory_item_id,
        fusion_doo_fulfill_lines_all.documentreferencesdocaltuserkey                    document_references_doc_alt_user_key,
        fusion_doo_fulfill_lines_all.dossupplybuyorderdtlspurchaseordernumber           dos_supply_buy_order_dtls_purchase_order_number,
        fusion_doo_fulfill_lines_all.fulfilllinesupplierid                              fulfill_line_supplier_id,
        fusion_doo_fulfill_lines_all.headersoldtopartyid                                header_sold_to_party_id,
        fusion_doo_fulfill_lines_all.documentreferencesdoclinealtuserkey                document_references_doc_line_alt_user_key,
        fusion_doo_fulfill_lines_all.linelineid                                         line_line_id,
        fusion_doo_fulfill_lines_all.coverageflinedetailssourcelinenumber               coverage_fline_details_source_line_number,
        fusion_doo_fulfill_lines_all.headercanceledflag                                 header_canceled_flag,
        fusion_doo_fulfill_lines_all.linelastupdatedate                                 line_last_update_date,
        fusion_doo_fulfill_lines_all.fulfilllineshipclassofservice                      fulfill_line_ship_class_of_service,
        fusion_doo_fulfill_lines_all.coveredflinedetailssourceordernumber               covered_fline_details_source_order_number,
        fusion_doo_fulfill_lines_all.linescheduleshipdate                               line_schedule_ship_date,
        fusion_doo_fulfill_lines_all.dossupplybuyorderdtlspurchaseorderschedulenumber   dos_supply_buy_order_dtls_purchase_order_schedule_number,
        fusion_doo_fulfill_lines_all.coveredflinedetailsdocreftype                      covered_fline_details_doc_ref_type,
        fusion_doo_fulfill_lines_all.fulfilllinefulfilllinenumber                       fulfill_line_fulfill_line_number,
        fusion_doo_fulfill_lines_all.docreferencesdropshipdocuserkey                    doc_references_dropship_doc_user_key,
        fusion_doo_fulfill_lines_all.lineactualshipdate                                 line_actual_ship_date,
        fusion_doo_fulfill_lines_all.documentreferencesdocuserkey                       document_references_doc_user_key,
        fusion_doo_fulfill_lines_all.headeropenflag                                     header_open_flag,
        fusion_doo_fulfill_lines_all.coverageflinedetailssourceschedulenumber           coverage_fline_details_source_schedule_number,
        fusion_doo_fulfill_lines_all.fulfilllineshiptopartyid                           fulfill_line_ship_to_party_id,
        fusion_doo_fulfill_lines_all.fulfilllineexemptioncertificatenumber              fulfill_line_exemption_certificate_number,
        fusion_doo_fulfill_lines_all.fulfilllinelatestacceptablearrivaldate             fulfill_line_latest_acceptable_arrival_date,
        fusion_doo_fulfill_lines_all.fulfilllineservicedurationperiodcode               fulfill_line_service_duration_period_code,
        fusion_doo_fulfill_lines_all.headerconversionrate                               header_conversion_rate,
        fusion_doo_fulfill_lines_all.fulfilllinesourcelinenumber                        fulfill_line_source_line_number,
        fusion_doo_fulfill_lines_all.lineordereduom                                     line_ordered_uom,
        fusion_doo_fulfill_lines_all.linesourcelinenumber                               line_source_line_number,
        fusion_doo_fulfill_lines_all.headeronhold                                       header_on_hold,
        fusion_doo_fulfill_lines_all.linesourceorderid                                  line_source_order_id,
        fusion_doo_fulfill_lines_all.coverageflinedetailscontractenddate                coverage_fline_details_contract_end_date,
        fusion_doo_fulfill_lines_all.linestatuscode                                     line_status_code,
        fusion_doo_fulfill_lines_all.lineonhold                                         line_on_hold,
        fusion_doo_line_statuses.statustranslationdisplayname                           status_translation_display_name,
        CONTEXT_CODE,
PROGRAM_NAME,
PROGRAM_APP_NAME,
decode(context_code,'Reference IDs',ATTRIBUTE_CHAR8,null)  SFDC_Case_Number,
decode(context_code,'Reference IDs',ATTRIBUTE_CHAR9,null)  Subscription_Number,
decode(context_code,'Reference IDs',ATTRIBUTE_CHAR11,null)  SFDC_Case_ID,
FUSION_DOO_LINES_ALL.LINEID LINE_ID,
FUSION_DOO_LINES_ALL.LINEEXTENDEDAMOUNT LINE_EXTENDED_AMOUNT,
--FUSION_DOO_ORDER_TOTALS.ORDERTOTALTOTALAMOUNT TOTAL_AMOUNT,
---FUSION_DOO_ORDER_TOTALS.ORDERTOTALTOTALCODE TOTAL_CODE,
--FUSION_DOO_ORDER_CHARGES.OrderChargeLastUpdatedBy     LAST_UPDATED_BY,
FUSION_DOO_ORDER_CHARGES.OrderChargeChargeSubtypeCode     CHARGE_SUBTYPE_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargePricePeriodicityCode     PRICE_PERIODICITY_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeCanAdjustFlag     CAN_ADJUST_FLAG,
FUSION_DOO_ORDER_CHARGES.OrderChargeGsaUnitPrice     GSA_UNIT_PRICE,
FUSION_DOO_ORDER_CHARGES.OrderChargeLastUpdateDate     LAST_UPDATE_DATE,
FUSION_DOO_ORDER_CHARGES.OrderChargeOrderChargeId     ORDER_CHARGE_ID,
FUSION_DOO_ORDER_CHARGES.OrderChargeSourceChargeId     SOURCE_CHARGE_ID,
FUSION_DOO_ORDER_CHARGES.OrderChargeCreatedBy     CREATED_BY,
FUSION_DOO_ORDER_CHARGES.OrderChargePrimaryFlag     PRIMARY_FLAG,
FUSION_DOO_ORDER_CHARGES.OrderChargePricedQuantityUomCode     PRICED_QUANTITY_UOM_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeAvgUnitSellingPrice     AVG_UNIT_SELLING_PRICE,
FUSION_DOO_ORDER_CHARGES.OrderChargeParentEntityCode     PARENT_ENTITY_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeRollupFlag     ROLLUP_FLAG,
FUSION_DOO_ORDER_CHARGES.OrderChargeParentEntityId     PARENT_ENTITY_ID,
FUSION_DOO_ORDER_CHARGES.OrderChargeChargeCurrencyCode     CHARGE_CURRENCY_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeObjectVersionNumber     COBJECT_VERSION_NUMBER,
FUSION_DOO_ORDER_CHARGES.OrderChargeReferenceOrderChargeId     REFERENCE_ORDER_CHARGE_ID,
FUSION_DOO_ORDER_CHARGES.OrderChargeSequenceNumber     SEQUENCE_NUMBER,
FUSION_DOO_ORDER_CHARGES.OrderChargeChargeDefinitionCode     CHARGE_DEFINITION_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeChargeAppliesTo     CHARGE_APPLIES_TO,
FUSION_DOO_ORDER_CHARGES.OrderChargePriceTypeCode     PRICE_TYPE_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeChargeTypeCode     CHARGE_TYPE_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeLastUpdateLogin     LAST_UPDATE_LOGIN,
FUSION_DOO_ORDER_CHARGES.OrderChargeCreationDate     CCREATION_DATE,
FUSION_DOO_ORDER_CHARGES.OrderChargeDeltaType     DELTA_TYPE,
FUSION_DOO_ORDER_CHARGES.OrderChargeModifiedFlag     MODIFIED_FLAG,
FUSION_DOO_ORDER_CHARGES.OrderChargePricedQuantity     PRICED_QUANTITY,
---FUSION_DOO_ORDER_CHARGES.FulfillLineRootParentFulfillLineIdPk     FULFILL_LINE_ID,
FUSION_DOO_ORDER_CHARGES.HeaderHeaderId     CHEADER_HEADER_ID,
FUSION_DOO_ORDER_CHARGES.LineUnitListPrice     CUNIT_LIST_PRICE,
FUSION_DOO_ORDER_CHARGES.LineLineId     CLINE_LINE_ID,
FUSION_DOO_ORDER_CHARGES.FulfillLineLineId     CFULFILL_LINE_LINEID,
FUSION_DOO_ORDER_CHARGES.FulfillLineLineTypeCode     FCULFILL_LINE_LINETYPE_CODE,
FUSION_DOO_ORDER_CHARGES.LineLineTypeCode     CLINE_LINETYPE_CODE,
FUSION_DOO_ORDER_CHARGES.OrderChargeComponentHeaderCurrencyExtAmount     HEADER_CURRENCY_EXT_AMOUNT,
FUSION_DOO_ORDER_CHARGES.OrderChargeComponentHeaderCurrDurationExtAmt     HEADER_CURR_DURATION_EXT_AMT,
FUSION_DOO_ORDER_CHARGES.OrderChargeComponentChargeCurrencyUnitPrice     CHARGE_CURRENCY_UNIT_PRICE,
FUSION_DOO_ORDER_CHARGES.OrderChargeComponentHeaderCurrencyUnitPrice     HEADER_CURRENCY_UNIT_PRICE,
FUSION_DOO_ORDER_CHARGES.OrderChargeComponentPriceElementCode     PRICE_ELEMENT_CODE,
(CASE WHEN FUSION_DOO_ORDER_CHARGES.ORDERCHARGECHARGEDEFINITIONCODE = 'QP_RECURRING_SALE_PRICE' AND 
       FUSION_DOO_ORDER_CHARGES.ORDERCHARGECOMPONENTPRICEELEMENTCODE = 'QP_LIST_PRICE'       
       THEN FUSION_DOO_ORDER_CHARGES.ORDERCHARGECOMPONENTHEADERCURRENCYEXTAMOUNT ELSE 0 END) MRC,
       (CASE WHEN FUSION_DOO_ORDER_CHARGES.ORDERCHARGECHARGEDEFINITIONCODE = 'QP_SALE_PRICE' AND 
	   FUSION_DOO_ORDER_CHARGES.ORDERCHARGECOMPONENTPRICEELEMENTCODE = 'QP_LIST_PRICE' 
	   THEN FUSION_DOO_ORDER_CHARGES.ORDERCHARGECOMPONENTHEADERCURRENCYEXTAMOUNT ELSE 0 END) NRC
    FROM
    ods.fusion_doo_headers_all
left JOIN ods.fusion_doo_fulfill_lines_all ON fusion_doo_fulfill_lines_all.fulfilllineheaderid = fusion_doo_headers_all.headerid
left join ods.FUSION_DOO_LINES_ALL on  FUSION_DOO_LINES_ALL.LINEID = fusion_doo_fulfill_lines_all.LINELINEID and FUSION_DOO_LINES_ALL.HEADERHEADERID = fusion_doo_headers_all.headerid
left JOIN ods.fusion_doo_line_statuses ON fusion_doo_line_statuses.statustranslationlanguage = 'US' and
fusion_doo_line_statuses.fulfilllinestatusstatuscode = fusion_doo_fulfill_lines_all.fulfilllinestatuscode
left join ods.FUSION_DOO_FULFL_LINES_EFF on FUSION_DOO_FULFL_LINES_EFF.FULFILL_LINE_ID = fusion_doo_fulfill_lines_all.FULFILLLINEID
left join ODS.FUSION_DOO_ORDER_CHARGES  on  FUSION_DOO_ORDER_CHARGES.ORDERCHARGEPARENTENTITYID=fusion_doo_fulfill_lines_all.FULFILLLINEID
LEFT JOIN dw.w_customer_d ON to_char(fusion_doo_headers_all.soldtopartyid) = w_customer_d.l4_legal_entity_src_key and w_customer_d.current_flag = 'Y'
		/*left join ods.fusion_ib_cse_assets_b on        fusion_doo_fulfill_lines_all.fulfilllineheaderid = fusion_ib_cse_assets_b.salesorderid
		left join ods.fusion_ib_cse_assets_b on        fusion_doo_fulfill_lines_all.fulfilllineid = fusion_ib_cse_assets_b.salesorderlineid */
;
  GRANT READ ON "DW"."VW_ORDER_LINES_F" TO "DW_RO";
  GRANT SELECT ON "DW"."VW_ORDER_LINES_F" TO "DW_RO";
