--------------------------------------------------------
--  DDL for View VW_SUBSCRIPTIONS_F
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_SUBSCRIPTIONS_F" ("CUSTOMER_WID", "PROPERTY_WID", "PRODUCT_WID", "SUBSCRIPTION_WID", "ALTERNATE_SUBSCRIPTION_ID", "SUBSCRIPTIONS_MAJOR_VERSION", "SUBSCRIPTIONS_VERSION_TYPE", "SUBSCRIPTIONS_NUMBER", "SUBSCRIPTIONS_PROFILE_ID", "SUBSCRIPTIONS_START_DATE", "SUBSCRIPTIONS_END_DATE", "SUBSCRIPTIONS_STATUS", "SUBSCRIPTIONS_SHORT_DESCRIPTION", "SUBSCRIPTIONS_DESCRIPTION", "SUBSCRIPTIONS_VERSION_DESCRIPTION", "SUBSCRIPTIONS_ELECTRONIC_SIGN_YN", "SUBSCRIPTIONS_TEMPLATE_YN", "SUBSCRIPTIONS_CLOSE_SET_ID", "SUBSCRIPTIONS_CLOSE_REASON", "SUBSCRIPTIONS_CLOSE_CREDIT_METHOD", "SUBSCRIPTIONS_CANCEL_SET_ID", "SUBSCRIPTIONS_CANCEL_REASON", "SUBSCRIPTIONS_APPROVAL_NOTE", "SUBSCRIPTIONS_TEMPLATE_USED", "SUBSCRIPTIONS_BUSINESS_UNIT_ID", "SUBSCRIPTIONS_PRIMARY_PARTY_ID", "SUBSCRIPTIONS_LEGAL_ENTITY_ID", "SUBSCRIPTIONS_DEFINITION_ORG_ID", "SUBSCRIPTIONS_PARTIAL_PERIOD_TYPE", "SUBSCRIPTIONS_PARTIAL_PERIOD_START", "SUBSCRIPTIONS_USER_STATUS", "SUBSCRIPTIONS_ASSIGNEE_ID", "SUBSCRIPTIONS_ASSIGNEE_TYPE", "SUBSCRIPTIONS_STATE_TRANSITION_FLOW_STATE", "SUBSCRIPTIONS_SOURCE_SYSTEM", "SUBSCRIPTIONS_SOURCE_KEY", "SUBSCRIPTIONS_ENABLE_UI_ACTIONS_YN", "SUBSCRIPTIONS_SOURCE_NUMBER", "SUBSCRIPTIONS_APPROVED_DATE", "SUBSCRIPTIONS_SIGNED_DATE", "SUBSCRIPTIONS_CANCELED_DATE", "SUBSCRIPTIONS_RENEWED_DATE", "SUBSCRIPTIONS_CLOSED_DATE", "SUBSCRIPTIONS_PRICING_STRATEGY_ID", "SUBSCRIPTIONS_PRICING_SEGMENT", "SUBSCRIPTIONS_PRICED_ON_DATE", "SUBSCRIPTIONS_PRICING_SEGMENT_EXPLAN", "SUBSCRIPTIONS_PRICING_STRATEGY_EXPLAN", "SUBSCRIPTIONS_PRICING_SYSTEM", "SUBSCRIPTIONS_SEGMENT_EXPLAN_MSG_NAME", "SUBSCRIPTIONS_CURRENCY", "SUBSCRIPTIONS_NET_PRICE", "SUBSCRIPTIONS_ESTIMATED_TAX", "SUBSCRIPTIONS_CANCELED_AMOUNT", "SUBSCRIPTIONS_CLOSED_AMOUNT", "SUBSCRIPTIONS_TOTAL", "SUBSCRIPTIONS_INVOICED_AMOUNT", "SUBSCRIPTIONS_CREDITED_AMOUNT", "SUBSCRIPTIONS_SUPPRESSED_CREDIT_AMOUNT", "SUBSCRIPTIONS_USAGE_INVOICED_AMOUNT", "SUBSCRIPTIONS_USAGE_CREDITED_AMOUNT", "SUBSCRIPTIONS_USAGE_SUPPRESSED_CREDIT_AMT", "SUBSCRIPTIONS_BILL_TO_ACCT_ID", "SUBSCRIPTIONS_BILL_TO_SITE_USE_ID", "SUBSCRIPTIONS_SHIP_TO_PARTY", "SUBSCRIPTIONS_SHIP_TO_PARTY_SITE_ID", "SUBSCRIPTIONS_TRANSACTION_TYPE_NAME", "SUBSCRIPTIONS_INVOICING_RULE_ID", "SUBSCRIPTIONS_ACCOUNTING_RULE_ID", "SUBSCRIPTIONS_BILLING_FREQUENCY", "SUBSCRIPTIONS_BILL_SERVICE", "SUBSCRIPTIONS_BILLING_SYSTEM", "SUBSCRIPTIONS_BILLING_DATE_CODE", "SUBSCRIPTIONS_BILL_ON_DAY", "SUBSCRIPTIONS_BILLING_OFFSET_DAYS", "SUBSCRIPTIONS_INVOICE_TEXT", "SUBSCRIPTIONS_COVERAGE_INVOICE_TEXT", "SUBSCRIPTIONS_PAYMENT_TERM_ID", "SUBSCRIPTIONS_PAYMENT_METHOD", "SUBSCRIPTIONS_PO_NUMBER", "SUBSCRIPTIONS_WIRE_NUMBER", "SUBSCRIPTIONS_TRXN_EXTENSION_ID", "SUBSCRIPTIONS_INSTR_ASSIGNMENT_ID", "SUBSCRIPTIONS_CURR_CONVERSION_RATE_TYPE", "SUBSCRIPTIONS_CURR_CONVERSION_RATE", "SUBSCRIPTIONS_CURR_CONVERSION_RATE_DATE", "SUBSCRIPTIONS_TAX_EXEMPTION_CONTROL", "SUBSCRIPTIONS_EXEMPT_CERTIFICATE_NUMBER", "SUBSCRIPTIONS_EXEMPT_REASON", "SUBSCRIPTIONS_OUTPUT_TAX_CLASSIFICATION", "SUBSCRIPTIONS_DOC_FISCAL_CLASSIFICATION", "SUBSCRIPTIONS_RENEWAL_PRICING_METHOD_USED", "SUBSCRIPTIONS_PRICE_ADJUSTMENT_TYPE_USED", "SUBSCRIPTIONS_PRICE_ADJUSTMENT_PCT_USED", "SUBSCRIPTIONS_DAYS_BEFORE_EXPIRY_USED", "SUBSCRIPTIONS_RENEWAL_PROCESS_USED", "SUBSCRIPTIONS_DAYS_BEFORE_EXPIRY", "SUBSCRIPTIONS_QUOTE_TO_CONTACT_ID", "SUBSCRIPTIONS_QUOTE_TO_CC_EMAIL", "SUBSCRIPTIONS_RENEWAL_PROCESS", "SUBSCRIPTIONS_RENEWAL_SALES_REP", "SUBSCRIPTIONS_MIN_RENEWAL_DURATION_USED", "SUBSCRIPTIONS_MIN_RENEWAL_PERIOD_USED", "SUBSCRIPTIONS_COMMUNICATION_CHANNEL", "SUBSCRIPTIONS_CUSTOMER_ACCEPTANCE", "SUBSCRIPTIONS_ENABLE_RENEWAL_REMINDERS_YN", "SUBSCRIPTIONS_INTERNAL_APPROVAL", "SUBSCRIPTIONS_NEGOTIATION_LANGUAGE", "SUBSCRIPTIONS_RENEWAL_CUSTOMER_ACCEPTANCE", "SUBSCRIPTIONS_RENEWAL_INTERNAL_APPROVAL", "SUBSCRIPTIONS_RENEWAL_PRICE_ADJ_TYPE", "SUBSCRIPTIONS_RENEWAL_PRICE_ADJ_BASIS", "SUBSCRIPTIONS_RENEWAL_PRICE_ADJ_PERCENT", "SUBSCRIPTIONS_LAYOUT_TEMPLATE", "SUBSCRIPTIONS_TERMS_LAYOUT_TEMPLATE", "SUBSCRIPTIONS_PERPETUAL_YN", "SUBSCRIPTIONS_TASK_ID", "SUBSCRIPTIONS_CORRELATION_ID", "SUBSCRIPTIONS_PRICING_ERROR", "SUBSCRIPTIONS_OBJECT_VERSION_NUMBER", "SUBSCRIPTIONS_CREATED_BY", "SUBSCRIPTIONS_CREATION_DATE", "SUBSCRIPTIONS_LAST_UPDATED_BY", "SUBSCRIPTIONS_LAST_UPDATE_DATE", "SUBSCRIPTIONS_LAST_UPDATE_LOGIN", "SUBSCRIPTIONS_CORP_CURRENCY_CODE", "SUBSCRIPTIONS_CURCY_CONV_RATE_TYPE", "CUSTOMER_TERMINATION_NOTIFICATION_PERIOD", "PRICE_INCREASE_NOTIFICATION_DAY", "RENEWAL_DURATION", "HARD_COMMENCEMENT_DATE", "FACILITY_ADDRESS", "LOCATION", "MSA_CONTRACT_NUMBER", "SUITE_IDENTIFIER", "PARTIES_SUBSCRIPTION_PARTY_ID", "PARTIES_PARTY_PUID", "PARTIES_VERSION_TYPE", "PARTIES_PARTY_ROLE", "PARTIES_PARTY_ID", "PARTIES_SIGNED_BY", "PARTIES_SIGNED_DATE", "PARTIES_PRIMARY_YN", "PARTIES_INTERNAL_YN", "PARTIES_SIGNER_ROLE", "PARTIES_OBJECT_VERSION_NUMBER", "PARTIES_CREATED_BY", "PARTIES_CREATION_DATE", "PARTIES_LAST_UPDATED_BY", "PARTIES_LAST_UPDATE_DATE", "PARTIES_LAST_UPDATE_LOGIN", "PRODUCTS_SUBSCRIPTION_PRODUCT_ID", "PRODUCTS_VERSION_TYPE", "PRODUCTS_PRODUCT_NUMBER", "PRODUCTS_SUBSCRIPTION_PRODUCT_PUID", "PRODUCTS_SALES_PRODUCT_TYPE", "PRODUCTS_PRODUCT_NAME", "PRODUCTS_STATUS", "PRODUCTS_START_DATE", "PRODUCTS_END_DATE", "PRODUCTS_CLOSE_SET_ID", "PRODUCTS_CLOSE_REASON", "PRODUCTS_CLOSE_CREDIT_METHOD", "PRODUCTS_CANCEL_SET_ID", "PRODUCTS_CANCEL_REASON", "PRODUCTS_AMEND_REASON", "PRODUCTS_AMEND_EFFECTIVE_DATE", "PRODUCTS_AMEND_DESCRIPTION", "PRODUCTS_AMEND_CREDIT_METHOD", "PRODUCTS_QUANTITY", "PRODUCTS_ITEM_UOM", "PRODUCTS_INVENTORY_ITEM_ID", "PRODUCTS_DEFINITION_ORG_ID", "PRODUCTS_SOURCE_SYSTEM", "PRODUCTS_SOURCE_KEY", "PRODUCTS_SOURCE_NUMBER", "PRODUCTS_MONTHLY_RECURRING_REVENUE", "PRODUCTS_SOURCE_LINE_KEY", "PRODUCTS_SOURCE_LINE_NUMBER", "PRODUCTS_CLOSED_DATE", "PRODUCTS_CANCELED_DATE", "PRODUCTS_RENEWED_DATE", "PRODUCTS_PRICE_LIST_ID", "PRODUCTS_PRICE_UOM", "PRODUCTS_UNIT_PRICE", "PRODUCTS_PRICING_ERROR", "PRODUCTS_OVERRIDE_PRICELIST_YN", "PRODUCTS_PRICE_AS_OF", "PRODUCTS_PRICE_TRANSACTION_ON", "PRODUCTS_PRICE_DURING_BILLING_YN", "PRODUCTS_PERPETUAL_YN", "PRODUCTS_PRODUCT_NET_PRICE", "PRODUCTS_ESTIMATED_TAX", "PRODUCTS_PRODUCT_TOTAL", "PRODUCTS_ONETIME_AMOUNT", "PRODUCTS_RECURRING_AMOUNT", "PRODUCTS_INVOICED_AMOUNT", "PRODUCTS_CANCELED_AMOUNT", "PRODUCTS_CLOSED_AMOUNT", "PRODUCTS_CREDITED_AMOUNT", "PRODUCTS_SUPPRESSED_CREDIT_AMOUNT", "PRODUCTS_USAGE_INVOICED_AMOUNT", "PRODUCTS_USAGE_CREDITED_AMOUNT", "PRODUCTS_USAGE_SUPPRESSED_CREDIT_AMT", "PRODUCTS_CURRENCY", "PRODUCTS_BILL_TO_ACCT_ID", "PRODUCTS_BILL_TO_SITE_USE_ID", "PRODUCTS_SHIP_TO_PARTY_ID", "PRODUCTS_SHIP_TO_PARTY_SITE_ID", "PRODUCTS_TRANSACTION_TYPE_NAME", "PRODUCTS_BILLING_DATE_CODE", "PRODUCTS_BILL_ON_DAY", "PRODUCTS_BILLING_OFFSET_DAYS", "PRODUCTS_BILLING_DATE_CODE_USED", "PRODUCTS_BILL_ON_DAY_USED", "PRODUCTS_BILLING_OFFSET_DAYS_USED", "PRODUCTS_BILLING_FREQ", "PRODUCTS_BILLING_FREQ_USED", "PRODUCTS_INVOICING_RULE_ID", "PRODUCTS_INVOICING_RULE_ID_USED", "PRODUCTS_ACCOUNTING_RULE_ID", "PRODUCTS_INVOICE_TEXT", "PRODUCTS_PAYMENT_TERM_ID", "PRODUCTS_PAYMENT_METHOD", "PRODUCTS_PO_NUMBER", "PRODUCTS_WIRE_NUMBER", "PRODUCTS_INSTR_ASSIGNMENT_ID", "PRODUCTS_TRXN_EXTENSION_ID", "PRODUCTS_PAYMENT_SET_ID", "PRODUCTS_TAX_EXEMPTION_CONTROL", "PRODUCTS_EXEMPT_CERTIFICATE_NUMBER", "PRODUCTS_EXEMPT_REASON", "PRODUCTS_OUTPUT_TAX_CLASSIFICATION", "PRODUCTS_PRODUCT_FISC_CLASSIFICATION", "PRODUCTS_PRODUCT_TYPE", "PRODUCTS_TRX_BUSINESS_CATEGORY", "PRODUCTS_TAX_ERROR", "PRODUCTS_COVERAGE_SCHEDULE_ID", "PRODUCTS_RENEWAL_TYPE", "PRODUCTS_OBJECT_VERSION_NUMBER", "PRODUCTS_CREATED_BY", "PRODUCTS_CREATION_DATE", "PRODUCTS_LAST_UPDATED_BY", "PRODUCTS_LAST_UPDATE_DATE", "PRODUCTS_LAST_UPDATE_LOGIN", "PRODUCTS_CORP_CURRENCY_CODE", "PRODUCTS_CURCY_CONV_RATE_TYPE", "PRODUCTS_EXTERNAL_ASSET_KEY", "PRODUCTS_EXTERNAL_PARENT_ASSET_KEY", "PRODUCTS_EXTERNAL_ROOT_ASSET_KEY", "PRODUCTS_NEXT_PRICING_DATE", "PRODUCTS_PRICE_LIST_NAME", "PRODUCTS_EXTERNAL_PRICE_BOOK_ID", "PRODUCTS_EXTERNAL_PRICE_BOOK_NAME", "PRODUCTS_PRICING_TERM_TYPE", "PRODUCTS_PRICING_TERM_DURATION", "PRODUCTS_PRICING_TERM_PERIOD", "PRODUCTS_PRICING_TERM_START_DATE", "PRODUCTS_PRICING_TERM_PRICING_METHOD", "PRODUCTS_PRICING_TERM_ADJUSTMENT_PCT", "PRODUCTS_ENABLE_PRICING_TERM_YN", "PRODUCTS_NEXT_BILL_START_DATE", "PRODUCTS_SUMMARIZED_BILLING_YN", "PRODUCTS_SUSPENDED_DATE", "PRODUCTS_SUSPEND_REASON", "PRODUCTS_SUSPEND_CREDIT_METHOD", "PRODUCTS_CHURN_PROBABILITY", "PRODUCTS_EARLY_TERMINATION_PENALTY", "PRODUCTS_GRACE_PERIOD", "PRODUCTS_PENALTY_VALUE", "PRODUCTS_EARLY_TERMINATION_FEE", "PRODUCTS_CREDIT_ISSUED_YN", "PRODUCTS_CHURN_PREDICTION_TREND", "PRODUCTS_PRICE_ADJUSTMENT_TYPE", "PRODUCTS_PRICE_ADJUSTMENT_BASIS", "PRODUCTS_PRICE_ADJUSTMENT_PERCENT", "PRODUCTS_INTERFACE_OFFSET_DAYS", "TRANSACTION_DESCRIPTION", "CHARGE_ID", "CHARGE_PUID", "CHARGES_VERSION_TYPE", "CHARGE_CURRENCY", "CHARGE_APPLIES_TO", "CHARGES_CAN_ADJUST_FLAG", "CHARGE_DEFINITION", "CHARGES_SEQUENCE_NUMBER", "CHARGE_SUBTYPE", "CHARGE_TYPE", "CHARGE_NAME", "CHARGES_EXTERNAL_KEY", "CHARGES_EXTERNAL_PARENT_KEY", "CHARGES_UNIT_LIST_PRICE", "CHARGES_ALLOWANCE", "CHARGES_BLOCK_SIZE", "CHARGES_TIERED_YN", "CHARGES_TIER_TYPE", "CHARGES_LOCK_USAGE_TIERS_YN", "CHARGES_PARENT_ENTITY", "CHARGES_PARENT_ENTITY_ID", "CHARGES_PRICED_QUANTITY", "CHARGES_PRICED_QUANTITY_UOM", "CHARGES_PRICE_PERIODICITY", "CHARGES_PRICE_TYPE", "CHARGES_PRIMARY_FLAG", "CHARGES_ROLLUP_FLAG", "CHARGES_PAYMENT_SET_ID", "CHARGES_OBJECT_VERSION_NUMBER", "CHARGES_CREATED_BY", "CHARGES_CREATION_DATE", "CHARGES_LAST_UPDATED_BY", "CHARGES_LAST_UPDATE_DATE", "CHARGES_LAST_UPDATE_LOGIN", "CHARGES_CORP_CURRENCY_CODE", "CHARGES_CURCY_CONV_RATE_TYPE", "LINES_BILL_LINE_ID", "LINES_BILL_LINE_PUID", "LINES_VERSION_TYPE", "LINES_CHARGE_ID", "LINES_SEQUENCE_NUMBER", "LINES_BILL_INSTANCE_NUMBER", "LINES_DATE_TO_INTERFACE", "LINES_DATE_BILLED_FROM", "LINES_DATE_BILLED_TO", "LINES_AMOUNT", "LINES_RECURRING_FLAG", "LINES_LIST_PRICE", "LINES_USAGE_YN", "LINES_USAGE_ACQUIRED_YN", "LINES_USAGE_PRICED_YN", "LINES_SENT_YN", "LINES_TRX_CLASS", "LINES_TRX_DATE", "LINES_TRX_NUMBER", "LINES_TRX_TAX", "LINES_TRX_AMOUNT", "LINES_INVOICE_TEXT", "LINES_INVOICE_BILL_LINE_ID", "LINES_CHARGE_DEFINITION", "LINES_USAGE_CAPTURE_DATE", "LINES_USAGE_QUANTITY", "LINES_CHARGE_PERIOD", "LINES_PRICING_ERROR", "LINES_REVENUE_LINE_ID", "LINES_OBJECT_VERSION_NUMBER", "LINES_CREATED_BY", "LINES_CREATION_DATE", "LINES_LAST_UPDATED_BY", "LINES_LAST_UPDATE_DATE", "LINES_LAST_UPDATE_LOGIN", "LINES_CURRENCY_CODE", "LINES_CORP_CURRENCY_CODE", "LINES_CURCY_CONV_RATE_TYPE", "ADJUSTMENT_BILL_ADJUSTMENT_ID", "ADJUSTMENT_BILL_ADJUSTMENT_PUID", "ADJUSTMENT_CHARGE_ADJUSTMENT_ID", "ADJUSTMENT_CHARGE_KEY", "ADJUSTMENT_NAME", "ADJUSTMENT_VALUE", "ADJUSTMENT_TYPE", "ADJUSTMENT_BASIS_ELEMENT", "ADJUSTMENT_REASON", "ADJUSTMENT_EFFECTIVITY", "ADJUSTMENT_NUMBER_OF_PERIODS", "ADJUSTMENT_PERIOD_FROM", "ADJUSTMENT_PERIOD_UNTIL", "ADJUSTMENT_VALID_FROM", "ADJUSTMENT_VALID_UNTIL", "ADJUSTMENT_EFFECTIVE_DAY_FROM", "ADJUSTMENT_EFFECTIVE_DAY_TO", "ADJUSTMENT_EFFECTIVE_MONTH_FROM", "ADJUSTMENT_EFFECTIVE_MONTH_TO", "ADJUSTMENT_SEQUENCE_NUMBER", "ADJUSTMENT_AMOUNT", "ADJUSTMENT_AUTO_ADJUSTMENT_YN", "ADJUSTMENT_OBJECT_VERSION_NUMBER", "ADJUSTMENT_CREATED_BY", "ADJUSTMENT_CREATION_DATE", "ADJUSTMENT_LAST_UPDATED_BY", "ADJUSTMENT_LAST_UPDATE_DATE", "ADJUSTMENT_LAST_UPDATE_LOGIN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        nvl(c.row_wid, - 1) customer_wid,
        nvl(p.row_wid, - 1) property_wid,
        nvl(w_product_d.row_wid, -1) product_wid,
        fusion_oss_subscriptions.subscription_id	subscription_wid	,
fusion_oss_subscriptions.alternate_subscription_id	alternate_subscription_id	,
fusion_oss_subscriptions.major_version	subscriptions_major_version	,
fusion_oss_subscriptions.version_type	subscriptions_version_type	,
fusion_oss_subscriptions.subscription_number	subscriptions_number	,
fusion_oss_subscriptions.subscription_profile_id	subscriptions_profile_id	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_start_date	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.end_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_end_date	,
fusion_oss_subscriptions.status	subscriptions_status	,
fusion_oss_subscriptions.short_description	subscriptions_short_description	,
fusion_oss_subscriptions.description	subscriptions_description	,
fusion_oss_subscriptions.version_description	subscriptions_version_description	,
fusion_oss_subscriptions.electronic_sign_yn	subscriptions_electronic_sign_yn	,
fusion_oss_subscriptions.template_yn	subscriptions_template_yn	,
fusion_oss_subscriptions.close_set_id	subscriptions_close_set_id	,
fusion_oss_subscriptions.close_reason	subscriptions_close_reason	,
fusion_oss_subscriptions.close_credit_method	subscriptions_close_credit_method	,
fusion_oss_subscriptions.cancel_set_id	subscriptions_cancel_set_id	,
fusion_oss_subscriptions.cancel_reason	subscriptions_cancel_reason	,
fusion_oss_subscriptions.approval_note	subscriptions_approval_note	,
fusion_oss_subscriptions.template_used	subscriptions_template_used	,
fusion_oss_subscriptions.business_unit_id	subscriptions_business_unit_id	,
fusion_oss_subscriptions.primary_party_id	subscriptions_primary_party_id	,
fusion_oss_subscriptions.legal_entity_id	subscriptions_legal_entity_id	,
fusion_oss_subscriptions.definition_org_id	subscriptions_definition_org_id	,
fusion_oss_subscriptions.partial_period_type	subscriptions_partial_period_type	,
fusion_oss_subscriptions.partial_period_start	subscriptions_partial_period_start	,
fusion_oss_subscriptions.user_status	subscriptions_user_status	,
fusion_oss_subscriptions.assignee_id	subscriptions_assignee_id	,
fusion_oss_subscriptions.assignee_type	subscriptions_assignee_type	,
fusion_oss_subscriptions.state_transition_flow_state	subscriptions_state_transition_flow_state	,
fusion_oss_subscriptions.source_system	subscriptions_source_system	,
fusion_oss_subscriptions.source_key	subscriptions_source_key	,
fusion_oss_subscriptions.enable_ui_actions_yn	subscriptions_enable_ui_actions_yn	,
fusion_oss_subscriptions.source_number	subscriptions_source_number	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.approved_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_approved_date	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.signed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_signed_date	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.canceled_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_canceled_date	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.renewed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_renewed_date	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.closed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_closed_date	,
fusion_oss_subscriptions.pricing_strategy_id	subscriptions_pricing_strategy_id	,
fusion_oss_subscriptions.pricing_segment	subscriptions_pricing_segment	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.priced_on_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_priced_on_date	,
fusion_oss_subscriptions.pricing_segment_explan	subscriptions_pricing_segment_explan	,
fusion_oss_subscriptions.pricing_strategy_explan	subscriptions_pricing_strategy_explan	,
fusion_oss_subscriptions.pricing_system	subscriptions_pricing_system	,
fusion_oss_subscriptions.segment_explan_msg_name	subscriptions_segment_explan_msg_name	,
fusion_oss_subscriptions.currency	subscriptions_currency	,
fusion_oss_subscriptions.net_price	subscriptions_net_price	,
fusion_oss_subscriptions.estimated_tax	subscriptions_estimated_tax	,
fusion_oss_subscriptions.canceled_amount	subscriptions_canceled_amount	,
fusion_oss_subscriptions.closed_amount	subscriptions_closed_amount	,
fusion_oss_subscriptions.total	subscriptions_total	,
fusion_oss_subscriptions.invoiced_amount	subscriptions_invoiced_amount	,
fusion_oss_subscriptions.credited_amount	subscriptions_credited_amount	,
fusion_oss_subscriptions.suppressed_credit_amount	subscriptions_suppressed_credit_amount	,
fusion_oss_subscriptions.usage_invoiced_amount	subscriptions_usage_invoiced_amount	,
fusion_oss_subscriptions.usage_credited_amount	subscriptions_usage_credited_amount	,
fusion_oss_subscriptions.usage_suppressed_credit_amt	subscriptions_usage_suppressed_credit_amt	,
fusion_oss_subscriptions.bill_to_acct_id	subscriptions_bill_to_acct_id	,
fusion_oss_subscriptions.bill_to_site_use_id	subscriptions_bill_to_site_use_id	,
fusion_oss_subscriptions.ship_to_party	subscriptions_ship_to_party	,
fusion_oss_subscriptions.ship_to_party_site_id	subscriptions_ship_to_party_site_id	,
fusion_oss_subscriptions.transaction_type_name	subscriptions_transaction_type_name	,
fusion_oss_subscriptions.invoicing_rule_id	subscriptions_invoicing_rule_id	,
fusion_oss_subscriptions.accounting_rule_id	subscriptions_accounting_rule_id	,
fusion_oss_subscriptions.billing_frequency	subscriptions_billing_frequency	,
fusion_oss_subscriptions.bill_service	subscriptions_bill_service	,
fusion_oss_subscriptions.billing_system	subscriptions_billing_system	,
fusion_oss_subscriptions.billing_date_code	subscriptions_billing_date_code	,
fusion_oss_subscriptions.bill_on_day	subscriptions_bill_on_day	,
fusion_oss_subscriptions.billing_offset_days	subscriptions_billing_offset_days	,
fusion_oss_subscriptions.subscription_invoice_text	subscriptions_invoice_text	,
fusion_oss_subscriptions.coverage_invoice_text	subscriptions_coverage_invoice_text	,
fusion_oss_subscriptions.payment_term_id	subscriptions_payment_term_id	,
fusion_oss_subscriptions.payment_method	subscriptions_payment_method	,
fusion_oss_subscriptions.po_number	subscriptions_po_number	,
fusion_oss_subscriptions.wire_number	subscriptions_wire_number	,
fusion_oss_subscriptions.trxn_extension_id	subscriptions_trxn_extension_id	,
fusion_oss_subscriptions.instr_assignment_id	subscriptions_instr_assignment_id	,
fusion_oss_subscriptions.curr_conversion_rate_type	subscriptions_curr_conversion_rate_type	,
fusion_oss_subscriptions.curr_conversion_rate	subscriptions_curr_conversion_rate	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.curr_conversion_rate_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_curr_conversion_rate_date	,
fusion_oss_subscriptions.tax_exemption_control	subscriptions_tax_exemption_control	,
fusion_oss_subscriptions.exempt_certificate_number	subscriptions_exempt_certificate_number	,
fusion_oss_subscriptions.exempt_reason	subscriptions_exempt_reason	,
fusion_oss_subscriptions.output_tax_classification	subscriptions_output_tax_classification	,
fusion_oss_subscriptions.doc_fiscal_classification	subscriptions_doc_fiscal_classification	,
fusion_oss_subscriptions.renewal_pricing_method_used	subscriptions_renewal_pricing_method_used	,
fusion_oss_subscriptions.price_adjustment_type_used	subscriptions_price_adjustment_type_used	,
fusion_oss_subscriptions.price_adjustment_pct_used	subscriptions_price_adjustment_pct_used	,
fusion_oss_subscriptions.days_before_expiry_used	subscriptions_days_before_expiry_used	,
fusion_oss_subscriptions.renewal_process_used	subscriptions_renewal_process_used	,
fusion_oss_subscriptions.days_before_expiry	subscriptions_days_before_expiry	,
fusion_oss_subscriptions.quote_to_contact_id	subscriptions_quote_to_contact_id	,
fusion_oss_subscriptions.quote_to_cc_email	subscriptions_quote_to_cc_email	,
fusion_oss_subscriptions.renewal_process	subscriptions_renewal_process	,
fusion_oss_subscriptions.renewal_sales_rep	subscriptions_renewal_sales_rep	,
fusion_oss_subscriptions.min_renewal_duration_used	subscriptions_min_renewal_duration_used	,
fusion_oss_subscriptions.min_renewal_period_used	subscriptions_min_renewal_period_used	,
fusion_oss_subscriptions.communication_channel	subscriptions_communication_channel	,
fusion_oss_subscriptions.customer_acceptance	subscriptions_customer_acceptance	,
fusion_oss_subscriptions.enable_renewal_reminders_yn	subscriptions_enable_renewal_reminders_yn	,
fusion_oss_subscriptions.internal_approval	subscriptions_internal_approval	,
fusion_oss_subscriptions.negotiation_language	subscriptions_negotiation_language	,
fusion_oss_subscriptions.renewal_customer_acceptance	subscriptions_renewal_customer_acceptance	,
fusion_oss_subscriptions.renewal_internal_approval	subscriptions_renewal_internal_approval	,
fusion_oss_subscriptions.renewal_price_adj_type	subscriptions_renewal_price_adj_type	,
fusion_oss_subscriptions.renewal_price_adj_basis	subscriptions_renewal_price_adj_basis	,
fusion_oss_subscriptions.renewal_price_adj_percent	subscriptions_renewal_price_adj_percent	,
fusion_oss_subscriptions.layout_template	subscriptions_layout_template	,
fusion_oss_subscriptions.terms_layout_template	subscriptions_terms_layout_template	,
fusion_oss_subscriptions.perpetual_yn	subscriptions_perpetual_yn	,
fusion_oss_subscriptions.task_id	subscriptions_task_id	,
fusion_oss_subscriptions.correlation_id	subscriptions_correlation_id	,
fusion_oss_subscriptions.pricing_error	subscriptions_pricing_error	,
fusion_oss_subscriptions.object_version_number	subscriptions_object_version_number	,
fusion_oss_subscriptions.created_by	subscriptions_created_by	,
CAST(to_timestamp_tz(fusion_oss_subscriptions.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	subscriptions_creation_date	,
fusion_oss_subscriptions.last_updated_by	subscriptions_last_updated_by	,
fusion_oss_subscriptions.last_update_date	subscriptions_last_update_date	,
fusion_oss_subscriptions.last_update_login	subscriptions_last_update_login	,
fusion_oss_subscriptions.corp_currency_code	subscriptions_corp_currency_code	,
fusion_oss_subscriptions.curcy_conv_rate_type	subscriptions_curcy_conv_rate_type	,
fusion_oss_subscriptions.extn_attribute_char003	Customer_Termination_Notification_Period	,
fusion_oss_subscriptions.extn_attribute_char007	Price_Increase_Notification_Day	,
fusion_oss_subscriptions.extn_attribute_char008	Renewal_Duration	,
fusion_oss_subscriptions.extn_attribute_char009	Hard_Commencement_Date	,
fusion_oss_subscriptions.extn_attribute_char004        Facility_Address,
fusion_oss_subscriptions.extn_attribute_char005        Location,
fusion_oss_subscriptions.extn_attribute_char006        MSA_Contract_Number,
fusion_oss_subscriptions.extn_attribute_char010        Suite_Identifier,
fusion_oss_parties.subscription_party_id	parties_subscription_party_id	,
fusion_oss_parties.party_puid	parties_party_puid	,
fusion_oss_parties.version_type	parties_version_type	,
fusion_oss_parties.party_role	parties_party_role	,
fusion_oss_parties.party_id	parties_party_id	,
fusion_oss_parties.signed_by	parties_signed_by	,
CAST(to_timestamp_tz(fusion_oss_parties.signed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	parties_signed_date	,
fusion_oss_parties.primary_yn	parties_primary_yn	,
fusion_oss_parties.internal_yn	parties_internal_yn	,
fusion_oss_parties.signer_role	parties_signer_role	,
fusion_oss_parties.object_version_number	parties_object_version_number	,
fusion_oss_parties.created_by	parties_created_by	,
CAST(to_timestamp_tz(fusion_oss_parties.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	parties_creation_date	,
fusion_oss_parties.last_updated_by	parties_last_updated_by	,
fusion_oss_parties.last_update_date	parties_last_update_date	,
fusion_oss_parties.last_update_login	parties_last_update_login	,
fusion_oss_products.subscription_product_id	products_subscription_product_id	,
fusion_oss_products.version_type	products_version_type	,
fusion_oss_products.product_number	products_product_number	,
fusion_oss_products.subscription_product_puid	products_subscription_product_puid	,
fusion_oss_products.sales_product_type	products_sales_product_type	,
fusion_oss_products.product_name	products_product_name	,
fusion_oss_products.status	products_status	,
CAST(to_timestamp_tz(fusion_oss_products.start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_start_date	,
CAST(to_timestamp_tz(fusion_oss_products.end_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_end_date	,
fusion_oss_products.close_set_id	products_close_set_id	,
fusion_oss_products.close_reason	products_close_reason	,
fusion_oss_products.close_credit_method	products_close_credit_method	,
fusion_oss_products.cancel_set_id	products_cancel_set_id	,
fusion_oss_products.cancel_reason	products_cancel_reason	,
fusion_oss_products.amend_reason	products_amend_reason	,
CAST(to_timestamp_tz(fusion_oss_products.amend_effective_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_amend_effective_date	,
fusion_oss_products.amend_description	products_amend_description	,
fusion_oss_products.amend_credit_method	products_amend_credit_method	,
fusion_oss_products.quantity	products_quantity	,
fusion_oss_products.item_uom	products_item_uom	,
fusion_oss_products.inventory_item_id	products_inventory_item_id	,
fusion_oss_products.definition_org_id	products_definition_org_id	,
fusion_oss_products.source_system	products_source_system	,
fusion_oss_products.source_key	products_source_key	,
fusion_oss_products.source_number	products_source_number	,
fusion_oss_products.monthly_recurring_revenue	products_monthly_recurring_revenue	,
fusion_oss_products.source_line_key	products_source_line_key	,
fusion_oss_products.source_line_number	products_source_line_number	,
CAST(to_timestamp_tz(fusion_oss_products.closed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_closed_date	,
CAST(to_timestamp_tz(fusion_oss_products.canceled_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_canceled_date	,
CAST(to_timestamp_tz(fusion_oss_products.renewed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_renewed_date	,
fusion_oss_products.price_list_id	products_price_list_id	,
fusion_oss_products.price_uom	products_price_uom	,
fusion_oss_products.unit_price	products_unit_price	,
fusion_oss_products.pricing_error	products_pricing_error	,
fusion_oss_products.override_pricelist_yn	products_override_pricelist_yn	,
fusion_oss_products.price_as_of	products_price_as_of	,
fusion_oss_products.price_transaction_on	products_price_transaction_on	,
fusion_oss_products.price_during_billing_yn	products_price_during_billing_yn	,
fusion_oss_products.perpetual_yn	products_perpetual_yn	,
fusion_oss_products.product_net_price	products_product_net_price	,
fusion_oss_products.estimated_tax	products_estimated_tax	,
fusion_oss_products.product_total	products_product_total	,
fusion_oss_products.onetime_amount	products_onetime_amount	,
fusion_oss_products.recurring_amount	products_recurring_amount	,
fusion_oss_products.invoiced_amount	products_invoiced_amount	,
fusion_oss_products.canceled_amount	products_canceled_amount	,
fusion_oss_products.closed_amount	products_closed_amount	,
fusion_oss_products.credited_amount	products_credited_amount	,
fusion_oss_products.suppressed_credit_amount	products_suppressed_credit_amount	,
fusion_oss_products.usage_invoiced_amount	products_usage_invoiced_amount	,
fusion_oss_products.usage_credited_amount	products_usage_credited_amount	,
fusion_oss_products.usage_suppressed_credit_amt	products_usage_suppressed_credit_amt	,
fusion_oss_products.currency	products_currency	,
fusion_oss_products.bill_to_acct_id	products_bill_to_acct_id	,
fusion_oss_products.bill_to_site_use_id	products_bill_to_site_use_id	,
fusion_oss_products.ship_to_party_id	products_ship_to_party_id	,
fusion_oss_products.ship_to_party_site_id	products_ship_to_party_site_id	,
fusion_oss_products.transaction_type_name	products_transaction_type_name	,
fusion_oss_products.billing_date_code	products_billing_date_code	,
fusion_oss_products.bill_on_day	products_bill_on_day	,
fusion_oss_products.billing_offset_days	products_billing_offset_days	,
fusion_oss_products.billing_date_code_used	products_billing_date_code_used	,
fusion_oss_products.bill_on_day_used	products_bill_on_day_used	,
fusion_oss_products.billing_offset_days_used	products_billing_offset_days_used	,
fusion_oss_products.billing_freq	products_billing_freq	,
fusion_oss_products.billing_freq_used	products_billing_freq_used	,
fusion_oss_products.invoicing_rule_id	products_invoicing_rule_id	,
fusion_oss_products.invoicing_rule_id_used	products_invoicing_rule_id_used	,
fusion_oss_products.accounting_rule_id	products_accounting_rule_id	,
fusion_oss_products.invoice_text	products_invoice_text	,
fusion_oss_products.payment_term_id	products_payment_term_id	,
fusion_oss_products.payment_method	products_payment_method	,
fusion_oss_products.po_number	products_po_number	,
fusion_oss_products.wire_number	products_wire_number	,
fusion_oss_products.instr_assignment_id	products_instr_assignment_id	,
fusion_oss_products.trxn_extension_id	products_trxn_extension_id	,
fusion_oss_products.payment_set_id	products_payment_set_id	,
fusion_oss_products.tax_exemption_control	products_tax_exemption_control	,
fusion_oss_products.exempt_certificate_number	products_exempt_certificate_number	,
fusion_oss_products.exempt_reason	products_exempt_reason	,
fusion_oss_products.output_tax_classification	products_output_tax_classification	,
fusion_oss_products.product_fisc_classification	products_product_fisc_classification	,
fusion_oss_products.product_type	products_product_type	,
fusion_oss_products.trx_business_category	products_trx_business_category	,
fusion_oss_products.tax_error	products_tax_error	,
fusion_oss_products.coverage_schedule_id	products_coverage_schedule_id	,
fusion_oss_products.renewal_type	products_renewal_type	,
fusion_oss_products.object_version_number	products_object_version_number	,
fusion_oss_products.created_by	products_created_by	,
CAST(to_timestamp_tz(fusion_oss_products.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_creation_date	,
fusion_oss_products.last_updated_by	products_last_updated_by	,
fusion_oss_products.last_update_date	products_last_update_date	,
fusion_oss_products.last_update_login	products_last_update_login	,
fusion_oss_products.corp_currency_code	products_corp_currency_code	,
fusion_oss_products.curcy_conv_rate_type	products_curcy_conv_rate_type	,
fusion_oss_products.external_asset_key	products_external_asset_key	,
fusion_oss_products.external_parent_asset_key	products_external_parent_asset_key	,
fusion_oss_products.external_root_asset_key	products_external_root_asset_key	,
CAST(to_timestamp_tz(fusion_oss_products.next_pricing_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_next_pricing_date	,
fusion_oss_products.price_list_name	products_price_list_name	,
fusion_oss_products.external_price_book_id	products_external_price_book_id	,
fusion_oss_products.external_price_book_name	products_external_price_book_name	,
fusion_oss_products.pricing_term_type	products_pricing_term_type	,
fusion_oss_products.pricing_term_duration	products_pricing_term_duration	,
fusion_oss_products.pricing_term_period	products_pricing_term_period	,
CAST(to_timestamp_tz(fusion_oss_products.pricing_term_start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_pricing_term_start_date	,
fusion_oss_products.pricing_term_pricing_method	products_pricing_term_pricing_method	,
fusion_oss_products.pricing_term_adjustment_pct	products_pricing_term_adjustment_pct	,
fusion_oss_products.enable_pricing_term_yn	products_enable_pricing_term_yn	,
CAST(to_timestamp_tz(fusion_oss_products.next_bill_start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_next_bill_start_date	,
fusion_oss_products.summarized_billing_yn	products_summarized_billing_yn	,
CAST(to_timestamp_tz(fusion_oss_products.suspended_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	products_suspended_date	,
fusion_oss_products.suspend_reason	products_suspend_reason	,
fusion_oss_products.suspend_credit_method	products_suspend_credit_method	,
fusion_oss_products.churn_probability	products_churn_probability	,
fusion_oss_products.early_termination_penalty	products_early_termination_penalty	,
fusion_oss_products.grace_period	products_grace_period	,
fusion_oss_products.penalty_value	products_penalty_value	,
fusion_oss_products.early_termination_fee	products_early_termination_fee	,
fusion_oss_products.credit_issued_yn	products_credit_issued_yn	,
fusion_oss_products.churn_prediction_trend	products_churn_prediction_trend	,
fusion_oss_products.price_adjustment_type	products_price_adjustment_type	,
fusion_oss_products.price_adjustment_basis	products_price_adjustment_basis	,
fusion_oss_products.price_adjustment_percent	products_price_adjustment_percent	,
fusion_oss_products.interface_offset_days	products_interface_offset_days	,
fusion_oss_products.extn_attribute_clob001 transaction_description,
fusion_oss_charges.charge_id	charge_id	,
fusion_oss_charges.charge_puid	charge_puid	,
fusion_oss_charges.version_type	charges_version_type	,
fusion_oss_charges.charge_currency	charge_currency	,
fusion_oss_charges.charge_applies_to	charge_applies_to	,
fusion_oss_charges.can_adjust_flag	charges_can_adjust_flag	,
fusion_oss_charges.charge_definition	charge_definition	,
fusion_oss_charges.sequence_number	charges_sequence_number	,
fusion_oss_charges.charge_subtype	charge_subtype	,
fusion_oss_charges.charge_type	charge_type	,
fusion_oss_charges.charge_name	charge_name	,
fusion_oss_charges.external_key	charges_external_key	,
fusion_oss_charges.external_parent_key	charges_external_parent_key	,
fusion_oss_charges.unit_list_price	charges_unit_list_price	,
fusion_oss_charges.allowance	charges_allowance	,
fusion_oss_charges.block_size	charges_block_size	,
fusion_oss_charges.tiered_yn	charges_tiered_yn	,
fusion_oss_charges.tier_type	charges_tier_type	,
fusion_oss_charges.lock_usage_tiers_yn	charges_lock_usage_tiers_yn	,
fusion_oss_charges.parent_entity	charges_parent_entity	,
fusion_oss_charges.parent_entity_id	charges_parent_entity_id	,
fusion_oss_charges.priced_quantity	charges_priced_quantity	,
fusion_oss_charges.priced_quantity_uom	charges_priced_quantity_uom	,
fusion_oss_charges.price_periodicity	charges_price_periodicity	,
fusion_oss_charges.price_type	charges_price_type	,
fusion_oss_charges.primary_flag	charges_primary_flag	,
fusion_oss_charges.rollup_flag	charges_rollup_flag	,
fusion_oss_charges.payment_set_id	charges_payment_set_id	,
fusion_oss_charges.object_version_number	charges_object_version_number	,
fusion_oss_charges.created_by	charges_created_by	,
CAST(to_timestamp_tz(fusion_oss_charges.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	charges_creation_date	,
fusion_oss_charges.last_updated_by	charges_last_updated_by	,
fusion_oss_charges.last_update_date	charges_last_update_date	,
fusion_oss_charges.last_update_login	charges_last_update_login	,
fusion_oss_charges.corp_currency_code	charges_corp_currency_code	,
fusion_oss_charges.curcy_conv_rate_type	charges_curcy_conv_rate_type	,
fusion_oss_bill_lines.bill_line_id	lines_bill_line_id	,
fusion_oss_bill_lines.bill_line_puid	lines_bill_line_puid	,
fusion_oss_bill_lines.version_type	lines_version_type	,
fusion_oss_bill_lines.charge_id	lines_charge_id	,
fusion_oss_bill_lines.sequence_number	lines_sequence_number	,
fusion_oss_bill_lines.bill_instance_number	lines_bill_instance_number	,
fusion_oss_bill_lines.date_to_interface	lines_date_to_interface	,
fusion_oss_bill_lines.date_billed_from	lines_date_billed_from	,
fusion_oss_bill_lines.date_billed_to	lines_date_billed_to	,
fusion_oss_bill_lines.amount	lines_amount	,
fusion_oss_bill_lines.recurring_flag	lines_recurring_flag	,
-- fusion_oss_bill_lines.manual_yn	lines_manual_yn	,
fusion_oss_bill_lines.list_price	lines_list_price	,
fusion_oss_bill_lines.usage_yn	lines_usage_yn	,
fusion_oss_bill_lines.usage_acquired_yn	lines_usage_acquired_yn	,
fusion_oss_bill_lines.usage_priced_yn	lines_usage_priced_yn	,
fusion_oss_bill_lines.sent_yn	lines_sent_yn	,
fusion_oss_bill_lines.trx_class	lines_trx_class	,
CAST(to_timestamp_tz(fusion_oss_bill_lines.trx_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	lines_trx_date	,
fusion_oss_bill_lines.trx_number	lines_trx_number	,
fusion_oss_bill_lines.trx_tax	lines_trx_tax	,
fusion_oss_bill_lines.trx_amount	lines_trx_amount	,
fusion_oss_bill_lines.invoice_text	lines_invoice_text	,
fusion_oss_bill_lines.invoice_bill_line_id	lines_invoice_bill_line_id	,
fusion_oss_bill_lines.charge_definition	lines_charge_definition	,
CAST(to_timestamp_tz(fusion_oss_bill_lines.usage_capture_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	lines_usage_capture_date	,
fusion_oss_bill_lines.usage_quantity	lines_usage_quantity	,
fusion_oss_bill_lines.charge_period	lines_charge_period	,
fusion_oss_bill_lines.pricing_error	lines_pricing_error	,
fusion_oss_bill_lines.revenue_line_id	lines_revenue_line_id	,
fusion_oss_bill_lines.object_version_number	lines_object_version_number	,
fusion_oss_bill_lines.created_by	lines_created_by	,
CAST(to_timestamp_tz(fusion_oss_bill_lines.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	lines_creation_date	,
fusion_oss_bill_lines.last_updated_by	lines_last_updated_by	,
fusion_oss_bill_lines.last_update_date	lines_last_update_date	,
fusion_oss_bill_lines.last_update_login	lines_last_update_login	,
fusion_oss_bill_lines.currency_code	lines_currency_code	,
fusion_oss_bill_lines.corp_currency_code	lines_corp_currency_code	,
fusion_oss_bill_lines.curcy_conv_rate_type	lines_curcy_conv_rate_type	,
fusion_oss_bill_adjustment.bill_adjustment_id	adjustment_bill_adjustment_id	,
fusion_oss_bill_adjustment.bill_adjustment_puid	adjustment_bill_adjustment_puid	,
fusion_oss_bill_adjustment.charge_adjustment_id	adjustment_charge_adjustment_id	,
fusion_oss_bill_adjustment.charge_key	adjustment_charge_key	,
fusion_oss_bill_adjustment.adjustment_name	adjustment_name	,
fusion_oss_bill_adjustment.adjustment_value	adjustment_value	,
fusion_oss_bill_adjustment.adjustment_type	adjustment_type	,
fusion_oss_bill_adjustment.basis_element	adjustment_basis_element	,
fusion_oss_bill_adjustment.reason	adjustment_reason	,
fusion_oss_bill_adjustment.effectivity	adjustment_effectivity	,
fusion_oss_bill_adjustment.number_of_periods	adjustment_number_of_periods	,
fusion_oss_bill_adjustment.period_from	adjustment_period_from	,
fusion_oss_bill_adjustment.period_until	adjustment_period_until	,
fusion_oss_bill_adjustment.valid_from	adjustment_valid_from	,
fusion_oss_bill_adjustment.valid_until	adjustment_valid_until	,
fusion_oss_bill_adjustment.effective_day_from	adjustment_effective_day_from	,
fusion_oss_bill_adjustment.effective_day_to	adjustment_effective_day_to	,
fusion_oss_bill_adjustment.effective_month_from	adjustment_effective_month_from	,
fusion_oss_bill_adjustment.effective_month_to	adjustment_effective_month_to	,
fusion_oss_bill_adjustment.sequence_number	adjustment_sequence_number	,
fusion_oss_bill_adjustment.adjustment_amount	adjustment_amount	,
fusion_oss_bill_adjustment.auto_adjustment_yn	adjustment_auto_adjustment_yn	,
fusion_oss_bill_adjustment.object_version_number	adjustment_object_version_number	,
fusion_oss_bill_adjustment.created_by	adjustment_created_by	,
CAST(to_timestamp_tz(fusion_oss_bill_adjustment.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM' ) AS DATE)	adjustment_creation_date	,
fusion_oss_bill_adjustment.last_updated_by	adjustment_last_updated_by	,
fusion_oss_bill_adjustment.last_update_date	adjustment_last_update_date	,
fusion_oss_bill_adjustment.last_update_login	adjustment_last_update_login	
    FROM
        ods.fusion_oss_subscriptions
        INNER JOIN ods.fusion_oss_parties ON fusion_oss_parties.subscription_id = fusion_oss_subscriptions.subscription_id and 
            fusion_oss_subscriptions.PRIMARY_PARTY_ID = fusion_oss_parties.PARTY_ID
        INNER JOIN ods.fusion_oss_products ON fusion_oss_products.subscription_id = fusion_oss_subscriptions.subscription_id
        INNER JOIN ods.fusion_oss_charges ON fusion_oss_products.subscription_product_id = fusion_oss_charges.subscription_product_id
        INNER JOIN ods.fusion_oss_bill_lines ON fusion_oss_bill_lines.charge_id = fusion_oss_charges.charge_id
        LEFT JOIN ods.fusion_oss_bill_adjustment ON fusion_oss_bill_lines.bill_line_id = fusion_oss_bill_adjustment.bill_line_id
        LEFT JOIN dw.w_customer_d  c ON to_char(fusion_oss_subscriptions.primary_party_id) = c.l4_legal_entity_src_key 
        and c.current_flag = 'Y'
        LEFT JOIN dw.w_property_d  p ON fusion_oss_subscriptions.extn_attribute_char005 = p.master_site_code
                                    AND p.live_flag = 1
                                    AND p.leaf_level = 'Location'
 left join dw.w_product_d  w_product_d on w_product_d.INTEGRATION_ID = fusion_oss_products.INVENTORY_ITEM_ID||'~'||fusion_oss_products.DEFINITION_ORG_ID
;
  GRANT SELECT ON "DW"."VW_SUBSCRIPTIONS_F" TO "DW_RO";
  GRANT READ ON "DW"."VW_SUBSCRIPTIONS_F" TO "DW_RO";
