--------------------------------------------------------
--  DDL for View VW_SUBSCRIPTION_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DW"."VW_SUBSCRIPTION_D" ("SUBSCRIPTION_ID", "MAJOR_VERSION", "VERSION_TYPE", "SUBSCRIPTION_NUMBER", "CUSTOMER_NAME", "START_DATE", "END_DATE", "APPROVED_DATE", "SIGNED_DATE", "CANCELED_DATE", "RENEWED_DATE", "CLOSED_DATE", "PRICED_ON_DATE", "CURR_CONVERSION_RATE_DATE", "STATUS", "SHORT_DESCRIPTION", "DESCRIPTION", "VERSION_DESCRIPTION", "ELECTRONIC_SIGN_YN", "TEMPLATE_YN", "CLOSE_SET_ID", "CLOSE_REASON", "CLOSE_CREDIT_METHOD", "CANCEL_SET_ID", "CANCEL_REASON", "APPROVAL_NOTE", "TEMPLATE_USED", "BUSINESS_UNIT_ID", "PRIMARY_PARTY_ID", "LEGAL_ENTITY_ID", "DEFINITION_ORG_ID", "PARTIAL_PERIOD_TYPE", "PARTIAL_PERIOD_START", "USER_STATUS", "ASSIGNEE_ID", "ASSIGNEE_TYPE", "STATE_TRANSITION_FLOW_STATE", "SOURCE_SYSTEM", "SOURCE_KEY", "ENABLE_UI_ACTIONS_YN", "SOURCE_NUMBER", "PRICING_STRATEGY_ID", "PRICING_SEGMENT", "PRICING_SEGMENT_EXPLAN", "PRICING_STRATEGY_EXPLAN", "PRICING_SYSTEM", "SEGMENT_EXPLAN_MSG_NAME", "CURRENCY", "NET_PRICE", "ESTIMATED_TAX", "CANCELED_AMOUNT", "CLOSED_AMOUNT", "TOTAL", "INVOICED_AMOUNT", "CREDITED_AMOUNT", "SUPPRESSED_CREDIT_AMOUNT", "USAGE_INVOICED_AMOUNT", "USAGE_CREDITED_AMOUNT", "USAGE_SUPPRESSED_CREDIT_AMT", "BILL_TO_ACCT_ID", "BILL_TO_SITE_USE_ID", "SHIP_TO_PARTY", "SHIP_TO_PARTY_SITE_ID", "TRANSACTION_TYPE_NAME", "INVOICING_RULE_ID", "ACCOUNTING_RULE_ID", "BILLING_FREQUENCY", "BILL_SERVICE", "BILLING_SYSTEM", "BILLING_DATE_CODE", "BILL_ON_DAY", "BILLING_OFFSET_DAYS", "SUBSCRIPTION_INVOICE_TEXT", "COVERAGE_INVOICE_TEXT", "PAYMENT_TERM_ID", "PAYMENT_METHOD", "PO_NUMBER", "WIRE_NUMBER", "TRXN_EXTENSION_ID", "INSTR_ASSIGNMENT_ID", "CURR_CONVERSION_RATE_TYPE", "CURR_CONVERSION_RATE", "TAX_EXEMPTION_CONTROL", "EXEMPT_CERTIFICATE_NUMBER", "EXEMPT_REASON", "OUTPUT_TAX_CLASSIFICATION", "DOC_FISCAL_CLASSIFICATION", "RENEWAL_PRICING_METHOD_USED", "PRICE_ADJUSTMENT_TYPE_USED", "PRICE_ADJUSTMENT_PCT_USED", "DAYS_BEFORE_EXPIRY_USED", "RENEWAL_PROCESS_USED", "DAYS_BEFORE_EXPIRY", "QUOTE_TO_CONTACT_ID", "QUOTE_TO_CC_EMAIL", "RENEWAL_PROCESS", "RENEWAL_SALES_REP", "MIN_RENEWAL_DURATION_USED", "MIN_RENEWAL_PERIOD_USED", "COMMUNICATION_CHANNEL", "CUSTOMER_ACCEPTANCE", "ENABLE_RENEWAL_REMINDERS_YN", "INTERNAL_APPROVAL", "NEGOTIATION_LANGUAGE", "RENEWAL_CUSTOMER_ACCEPTANCE", "RENEWAL_INTERNAL_APPROVAL", "RENEWAL_PRICE_ADJ_TYPE", "RENEWAL_PRICE_ADJ_BASIS", "RENEWAL_PRICE_ADJ_PERCENT", "LAYOUT_TEMPLATE", "TERMS_LAYOUT_TEMPLATE", "PERPETUAL_YN", "TASK_ID", "CORRELATION_ID", "PRICING_ERROR", "OBJECT_VERSION_NUMBER", "CREATION_DATE", "CUSTOMER_TERMINATION_NOTIFICATION_PERIOD", "PRICE_INCREASE_NOTIFICATION_DAYS", "RENEWAL_DURATION", "HARD_COMMENCEMENT_DATE", "FACILITY_ADDRESS", "LOCATION", "MSA_CONTRACT_NUMBER", "SUITE_IDENTIFIER", "ACCOUNT_NUMBER") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        fusion_oss_subscriptions.subscription_id               SUBSCRIPTION_ID,
        fusion_oss_subscriptions.major_version                 major_version,
        fusion_oss_subscriptions.version_type                  version_type,
        fusion_oss_subscriptions.subscription_number           subscription_number,
        fusion_hz_customer.PARTYNAME                           customer_name,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.start_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) start_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.end_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) end_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.approved_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) approved_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.signed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) signed_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.canceled_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) canceled_date,
        
        CAST(to_timestamp_tz(fusion_oss_subscriptions.renewed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) renewed_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.closed_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) closed_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.priced_on_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) priced_on_date,
        CAST(to_timestamp_tz(fusion_oss_subscriptions.curr_conversion_rate_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) curr_conversion_rate_date,
        fusion_oss_subscriptions.status                        status,
        fusion_oss_subscriptions.short_description             short_description,
        fusion_oss_subscriptions.description                   description,
        fusion_oss_subscriptions.version_description           version_description,
        fusion_oss_subscriptions.electronic_sign_yn            electronic_sign_yn,
        fusion_oss_subscriptions.template_yn                   template_yn,
        fusion_oss_subscriptions.close_set_id                  close_set_id,
        fusion_oss_subscriptions.close_reason                  close_reason,
        fusion_oss_subscriptions.close_credit_method           close_credit_method,
        fusion_oss_subscriptions.cancel_set_id                 cancel_set_id,
        fusion_oss_subscriptions.cancel_reason                 cancel_reason,
        fusion_oss_subscriptions.approval_note                 approval_note,
        fusion_oss_subscriptions.template_used                 template_used,
        fusion_oss_subscriptions.business_unit_id              business_unit_id,
        fusion_oss_subscriptions.primary_party_id              primary_party_id,
        fusion_oss_subscriptions.legal_entity_id               legal_entity_id,
        fusion_oss_subscriptions.definition_org_id             definition_org_id,
        fusion_oss_subscriptions.partial_period_type           partial_period_type,
        fusion_oss_subscriptions.partial_period_start          partial_period_start,
        fusion_oss_subscriptions.user_status                   user_status,
        fusion_oss_subscriptions.assignee_id                   assignee_id,
        fusion_oss_subscriptions.assignee_type                 assignee_type,
        fusion_oss_subscriptions.state_transition_flow_state   state_transition_flow_state,
        fusion_oss_subscriptions.source_system                 source_system,
        fusion_oss_subscriptions.source_key                    source_key,
        fusion_oss_subscriptions.enable_ui_actions_yn          enable_ui_actions_yn,
        fusion_oss_subscriptions.source_number                 source_number,
        
        fusion_oss_subscriptions.pricing_strategy_id           pricing_strategy_id,
        fusion_oss_subscriptions.pricing_segment               pricing_segment,
        
        fusion_oss_subscriptions.pricing_segment_explan        pricing_segment_explan,
        fusion_oss_subscriptions.pricing_strategy_explan       pricing_strategy_explan,
        fusion_oss_subscriptions.pricing_system                pricing_system,
        fusion_oss_subscriptions.segment_explan_msg_name       segment_explan_msg_name,
        fusion_oss_subscriptions.currency                      currency,
        fusion_oss_subscriptions.net_price                     net_price,
        fusion_oss_subscriptions.estimated_tax                 estimated_tax,
        fusion_oss_subscriptions.canceled_amount               canceled_amount,
        fusion_oss_subscriptions.closed_amount                 closed_amount,
        fusion_oss_subscriptions.total                         total,
        fusion_oss_subscriptions.invoiced_amount               invoiced_amount,
        fusion_oss_subscriptions.credited_amount               credited_amount,
        fusion_oss_subscriptions.suppressed_credit_amount      suppressed_credit_amount,
        fusion_oss_subscriptions.usage_invoiced_amount         usage_invoiced_amount,
        fusion_oss_subscriptions.usage_credited_amount         usage_credited_amount,
        fusion_oss_subscriptions.usage_suppressed_credit_amt   usage_suppressed_credit_amt,
        fusion_oss_subscriptions.bill_to_acct_id               bill_to_acct_id,
        fusion_oss_subscriptions.bill_to_site_use_id           bill_to_site_use_id,
        fusion_oss_subscriptions.ship_to_party                 ship_to_party,
        fusion_oss_subscriptions.ship_to_party_site_id         ship_to_party_site_id,
        fusion_oss_subscriptions.transaction_type_name         transaction_type_name,
        fusion_oss_subscriptions.invoicing_rule_id             invoicing_rule_id,
        fusion_oss_subscriptions.accounting_rule_id            accounting_rule_id,
        fusion_oss_subscriptions.billing_frequency             billing_frequency,
        fusion_oss_subscriptions.bill_service                  bill_service,
        fusion_oss_subscriptions.billing_system                billing_system,
        fusion_oss_subscriptions.billing_date_code             billing_date_code,
        fusion_oss_subscriptions.bill_on_day                   bill_on_day,
        fusion_oss_subscriptions.billing_offset_days           billing_offset_days,
        fusion_oss_subscriptions.subscription_invoice_text     subscription_invoice_text,
        fusion_oss_subscriptions.coverage_invoice_text         coverage_invoice_text,
        fusion_oss_subscriptions.payment_term_id               payment_term_id,
        fusion_oss_subscriptions.payment_method                payment_method,
        fusion_oss_subscriptions.po_number                     po_number,
        fusion_oss_subscriptions.wire_number                   wire_number,
        fusion_oss_subscriptions.trxn_extension_id             trxn_extension_id,
        fusion_oss_subscriptions.instr_assignment_id           instr_assignment_id,
        fusion_oss_subscriptions.curr_conversion_rate_type     curr_conversion_rate_type,
        fusion_oss_subscriptions.curr_conversion_rate          curr_conversion_rate,
        
        fusion_oss_subscriptions.tax_exemption_control         tax_exemption_control,
        fusion_oss_subscriptions.exempt_certificate_number     exempt_certificate_number,
        fusion_oss_subscriptions.exempt_reason                 exempt_reason,
        fusion_oss_subscriptions.output_tax_classification     output_tax_classification,
        fusion_oss_subscriptions.doc_fiscal_classification     doc_fiscal_classification,
        fusion_oss_subscriptions.renewal_pricing_method_used   renewal_pricing_method_used,
        fusion_oss_subscriptions.price_adjustment_type_used    price_adjustment_type_used,
        fusion_oss_subscriptions.price_adjustment_pct_used     price_adjustment_pct_used,
        fusion_oss_subscriptions.days_before_expiry_used       days_before_expiry_used,
        fusion_oss_subscriptions.renewal_process_used          renewal_process_used,
        fusion_oss_subscriptions.days_before_expiry            days_before_expiry,
        fusion_oss_subscriptions.quote_to_contact_id           quote_to_contact_id,
        fusion_oss_subscriptions.quote_to_cc_email             quote_to_cc_email,
        fusion_oss_subscriptions.renewal_process               renewal_process,
        fusion_oss_subscriptions.renewal_sales_rep             renewal_sales_rep,
        fusion_oss_subscriptions.min_renewal_duration_used     min_renewal_duration_used,
        fusion_oss_subscriptions.min_renewal_period_used       min_renewal_period_used,
        fusion_oss_subscriptions.communication_channel         communication_channel,
        fusion_oss_subscriptions.customer_acceptance           customer_acceptance,
        fusion_oss_subscriptions.enable_renewal_reminders_yn   enable_renewal_reminders_yn,
        fusion_oss_subscriptions.internal_approval             internal_approval,
        fusion_oss_subscriptions.negotiation_language          negotiation_language,
        fusion_oss_subscriptions.renewal_customer_acceptance   renewal_customer_acceptance,
        fusion_oss_subscriptions.renewal_internal_approval     renewal_internal_approval,
        fusion_oss_subscriptions.renewal_price_adj_type        renewal_price_adj_type,
        fusion_oss_subscriptions.renewal_price_adj_basis       renewal_price_adj_basis,
        fusion_oss_subscriptions.renewal_price_adj_percent     renewal_price_adj_percent,
        fusion_oss_subscriptions.layout_template               layout_template,
        fusion_oss_subscriptions.terms_layout_template         terms_layout_template,
        fusion_oss_subscriptions.perpetual_yn                  perpetual_yn,
        fusion_oss_subscriptions.task_id                       task_id,
        fusion_oss_subscriptions.correlation_id                correlation_id,
        fusion_oss_subscriptions.pricing_error                 pricing_error,
        fusion_oss_subscriptions.object_version_number         object_version_number,
        
        CAST(to_timestamp_tz(fusion_oss_subscriptions.creation_date DEFAULT NULL ON CONVERSION ERROR, 'YYYY-MM-DD"T"HH24:MI:SS.ff3 TZH:TZM'
        ) AS DATE) creation_date,

        fusion_oss_subscriptions.extn_attribute_char003        Customer_Termination_Notification_Period,
        fusion_oss_subscriptions.extn_attribute_char007        Price_Increase_Notification_Days,
        fusion_oss_subscriptions.extn_attribute_char008        Renewal_Duration,
        fusion_oss_subscriptions.extn_attribute_char009        Hard_Commencement_Date,
		fusion_oss_subscriptions.extn_attribute_char004        Facility_Address,
        fusion_oss_subscriptions.extn_attribute_char005        Location,
        fusion_oss_subscriptions.extn_attribute_char006        MSA_Contract_Number,
        fusion_oss_subscriptions.extn_attribute_char010        Suite_Identifier,
        (select max(ACCOUNTNUMBER) from ods.FUSION_HZ_CUST_ACCOUNTS where CUSTACCOUNTID = fusion_oss_subscriptions.bill_to_acct_id) ACCOUNT_NUMBER
    from ods.fusion_oss_subscriptions
    join ods.fusion_hz_customer on partyid = PRIMARY_PARTY_ID
;
  GRANT SELECT ON "DW"."VW_SUBSCRIPTION_D" TO "DW_RO";
  GRANT READ ON "DW"."VW_SUBSCRIPTION_D" TO "DW_RO";
